- src/components/Loader/indes.stories.js
- src/components/Loader/index.jsx
- src/components/NoSafe/index.jsx
- src/components/forms/validator.js
- src/components/layout/Link/index.jsx
- src/components/layout/Link/index.scss
- src/routes/open/components/SafeForm/Confirmations/index.test.js
- src/routes/open/components/SafeForm/Owners/index.jsx
- src/routes/open/components/SafeForm/Owners/index.test.js
- src/routes/open/components/SafeForm/index.jsx
- src/routes/safe/component/Layout.jsx
- src/routes/safe/component/Layout.stories.js
- src/routes/safe/container/index.jsx
- src/routes/safe/container/selector.js
- src/routes/safeList/components/Layout.jsx
- src/routes/safeList/components/Layout.stories.js
- src/routes/safeList/container/index.jsx
- src/routes/safeList/container/selector.js
- src/routes/welcome/components/Layout.jsx
This PR fixes the error when owner addresses are repeated, showing an error in the form. This PR includes a DOM test simulating this effect.
- [See video](https://drive.google.com/open?id=1FHkqwc6CxWBEkFPww-UqUIa6hnETdt2J)
Also, it fixes the string comparison between number fields, forcing to convert them to integers. Now when owners are 2 and confirmations are 014 it raises an error:
**## Refactors**
- Improved async routes Loader (now it is centered and slightly bigger)
- CREATE SAFE button across the app is disabled if you are not connected to METAMASK (check storybook)
> WA-280 - Feature not allowing similar owners accounts

- src/components/layout/Paragraph/index.scss
- src/routes/safe/component/Layout.jsx
- src/routes/safe/component/Layout.stories.js
- src/routes/safe/component/Safe.jsx
- src/routes/safe/container/actions.js
- src/routes/safe/container/index.jsx
- src/routes/safe/container/selector.js
- src/routes/safe/store/selectors/index.js
- src/routes/safe/store/test/balance.reducer.js
- src/routes/safe/store/test/balance.selector.js
- src/routes/safe/store/test/safe.spec.js
- src/store/index.js
This PR is the second part of the "display safe funds feature", it includes the selectors for fetching the balance of certain safe from redux store. The address of the safe to fetch comes from the url, taking advantage of the injected react-router props.
> WA-230 Adding get balance selector

- src/routes/open/container/Open.jsx
- src/routes/safe/component/AddTransaction/createTransactions.js
- src/routes/safe/component/Transactions/processTransactions.js
- src/routes/safe/component/Withdrawn/withdrawn.js
- src/routes/safe/test/Safe.multisig.3owners1threshold.test.js
- src/wallets/ethTransactions.js
Before those changes I was relying on try/catch for identifying errors, it seems on ```mainnet``` and ```rinkeby``` and ```mainnet```, if the **tx** fails no exception is raised, so I had to check the status field.
> WA-238 Checking tx receipt status on withdrawn mutlsig txs

- src/routes/safe/component/Safe/index.jsx
- src/routes/safe/component/Withdraw/actions.js
- src/routes/safe/component/Withdraw/index.jsx
- src/routes/safe/component/Withdraw/withdraw.js
- src/routes/safe/component/Withdraw/withdraw.test.js
- src/routes/safe/store/test/builder/deployedSafe.builder.js
- src/routes/safe/test/Safe.multisig.1owners1threshold.test.js
- src/routes/safe/test/Safe.withdraw.test.js
- src/test/safe.dom.test.js
- src/test/utils/transactions/withdraw.helper.js
In this PR we implement the logic of showing the withdraw funds movements as transactions, displaying them when you click on "SEE TXs"
**User expectations**
Basically,
see the withdrawn movements listed. See:
> WA-438 - Feature include withdraw movements as transactions

- src/routes/tokens/component/Layout.jsx
- src/routes/tokens/component/RemoveToken/Review.jsx
- src/routes/tokens/component/RemoveToken/index.jsx
- src/routes/tokens/component/Token/index.jsx
- src/routes/tokens/container/actions.js
- src/routes/tokens/container/index.jsx
- src/routes/tokens/store/actions/removeToken.js
- src/routes/tokens/store/reducer/tokens.js
- src/test/tokens.dom.removing.test.js
- src/test/tokens.redux.remove.test.js
- src/utils/localStorage/tokens.js
This PR enables the functionality for removing the custom ERC 20 tokens. Just click on the trash icon close the checkbox for enabling and disabling it in the settings view.
**Note for developers**
DOM test and also redux test simulating token removal is also uploaded
* **0xcc8405bccf09dbb5bdc47bbfbb7f9f13bad32635** This is the address of a valid token deployed on Rinkeby
* **0x8648767978239dcfa97e8cba3c2ac511fc95043c** This is the address of a valid token but without human readable information (symbol, decimals, name). Also deployed on Rinkeby.
* **0x85fb868e8b7f9e5bb3b31993ecba71b81f644b9a** This is the address of another smart contract which is not a token
* **0x0bf35169f79c22f2503970a5d8aea1e74a46adc4** This is the address of a valid token which is **not** deployed in …
> WA-232 - Feature:  remove custom ERC20 tokens

- src/config/development.js
- src/config/index.js
- src/config/names.js
- src/config/production.js
- src/config/testing.js
- src/logic/contracts/safeContracts.js
- src/logic/safe/safeBlockchainOperations.js
- src/logic/safe/safeTxSigner.js
- src/test/safe.redux.transactions.test.js
- src/test/utils/ethereumErrors.js
- src/utils/localStorage/signatures.js
In this PR I have included a feature flag for allowing sign PersonalSafe transactions via Web's HttpProvider, instead of calling the contracts themselves.
The logic for storing the signatures is a mocked service storing info in browser's localstorage
> WA-521 - PoC: Use EIP-712 signedTypedData in Web3's HttpProvideras signer

- src/components/Stepper/OpenPaper/index.jsx
- src/routes/load/components/DetailsForm/index.jsx
- src/theme/mui.js
- Get a substring of last 40 characters when getting proxy from storage (comment in the code explains it better)
- Add zIndex to MuiHelperText aka input label in our case fix it not showing in firefox
- Small prettier change
> Bugfixes: Load Safe, Firefox input labels

- src/routes/safe/container/actions.js
- src/routes/safe/container/index.jsx
- src/routes/safe/store/actions/fetchEtherBalance.js
- src/routes/safe/store/actions/fetchTokenBalances.js
This PR:
- Create an action `fetchEtherBalance` and add it to `checkForUpdates` in Safe Page Container. Previously we fetched ether balance in fetchSafe action, but then we stopped using it inside an interval because it can mess up owners/threshold updates
> BUG: Ether balance is not updated automatically

- src/logic/tokens/utils/tokensStorage.js
- src/test/tokens.dom.enabling.test.js
Add test for a bug we recently experienced (Active tokens were not saved to local storage). Also remove unused storage helper function
> Test: Active tokens saved to localstorage

- src/routes/safe/components/Balances/SendModal/index.jsx
This PR:
- Wrap modal screens which are lazy loaded with `Suspense` component with fallback to displaying loading spinner
> BUG: Page reloads when switching screens in send funds modal

- contracts/DevDependencies.sol
- src/routes/safe/components/Balances/SendModal/screens/ReviewTx/index.jsx
- src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/index.jsx
- src/test/contracts/Token6Decimals.sol
- src/test/safe.dom.funds.threshold=1.test.js
- src/test/utils/tokenMovements.js
- src/test/utils/transactions/moveFunds.helper.js
- Hotfix #218 
- Add a test case for sending token with non-18 decimals (6)
Testing:
- Get USDC coin (6 decimals) from compound: https://app.compound.finance/asset/cUSDC
- Send it to the safe and then send it back
> BUG: Hotfix #218 Non-18 decimals tokens transfer

- src/components/forms/validator.js
This PR:
- Fixes #205 
- Use parseFloat in maxValue validator so it respects decimals and thus works for numbers with same integer
> BUG 205: Max value validator doesn't work when entering tx value

- src/components/CopyBtn/index.jsx
- src/utils/clipboard.js
This PR:
- Fixes #234 
So previously I added a check (just in case) to hide copy button if the `navigator.clipboard` was undefined. Turned out to be worth it 😄. Found the polyfill and replaced `copyToClipboard` function with it: https://gist.github.com/lgarron/d1dee380f4ed9d825ca7
> Bug #234: Click to copy buttons are not shown in safari

- src/routes/safe/store/actions/fetchTransactions.js
For some reason, small part of the refactor for new tx history service was lost and it resulted in showing executed TXs as "awaiting confirmations"
> Bug: Executed tx shown as awaiting

- src/routes/load/components/DetailsForm/index.jsx
This PR:
- Adds missing whitespaces in load safe flow
> Bug 280: Missing whitespaces in load safe flow

- src/routes/safe/components/Transactions/TxsTable/Status/index.jsx
- src/routes/safe/components/Transactions/TxsTable/Status/style.js
- src/routes/safe/container/selector.js
- src/routes/safe/store/actions/createTransaction.js
- src/routes/safe/store/actions/processTransaction.js
- src/routes/safe/store/models/transaction.js
This PR:
- Implements #208, except 
> user can also access the transaction hash in the tx details
because we don't have information about what hash will final transaction use
> Feature #208: Show pending state for newly created transactions

- package.json
- src/components/Table/TableHead.jsx
- src/theme/mui.js
- yarn.lock
This PR:
- Fixes #188 
I set max-width for the owner's name table cell to 150px, which works for all width above 1366 (inclusive). But unfortunately it resulted in 18 symbols, not 30 as expected in ticket description
> Bug 188: Long owner names cause UI glitch

- src/components/Modal/index.jsx
This PR:
- Fixes #196 by allowing user to scroll modal view if it overflows the viewport
> Bug 196: Modals incorrectly displayed on smaller screen resolutions

- src/routes/safe/components/Layout.jsx
- src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/index.jsx
- src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/index.jsx
- src/routes/safe/components/Settings/ManageOwners/index.jsx
- src/routes/safe/components/Settings/index.jsx
- src/routes/safe/container/actions.js
- src/routes/safe/container/index.jsx
- src/routes/safe/store/actions/fetchSafe.js
Closes #215 
- Now before removing/replacing owners on the localStorage, checks that the threshold is 1, otherwise, it will wait until the transaction is confirmed by all the required owners.
- Also adds a `checkAndUpdateSafeOwners` function on the `checkForUpdates` function in order to check if the owner's list has changed and updates it (for instance: when the threshold is 2 and the first user is waiting for the other account to confirm the transaction). This is maybe not the most-performance way, because the polling is running each 5 seconds, maybe we can do it in another way or add two different pollings with different intervals, I'm open to suggestions :)
> Feature #215: Update owner list fix

- src/logic/safe/transactions/send.js
- src/logic/safe/transactions/txHistory.js
- src/logic/wallets/ethAddresses.js
- src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/utils.js
- src/routes/safe/components/Transactions/TxsTable/ExpandedTx/index.jsx
- src/routes/safe/container/selector.js
- src/routes/safe/store/actions/createTransaction.js
- src/routes/safe/store/actions/fetchTransactions.js
- src/routes/safe/store/actions/processTransaction.js
- src/routes/safe/store/models/confirmation.js
- src/routes/safe/store/models/transaction.js
Currently the react app always assumes that the confirmations returned by the backend are confirmed on-chain, but the backend also support off-chain signatures. This PR add support for that.
> Feature #176: Support off chain sigs

- .travis.yml
- config/travis/deploy_pull_request.sh
This PR:
- Exclude building docker image of transaction-history-service, building and deploying storybook because we don't use it anymore to save some time on deployment
> exclude unneeded stuff from travis.yml

- src/routes/safe/components/Balances/SendModal/screens/SendFunds/TokenSelectField/index.jsx
> Feature #258: Use medium font size for 'select an asset' label

- src/routes/safe/container/index.jsx
- src/routes/safe/container/selector.js
Closes #340 
- Description
- There was an race condition between `fetchSafe` and `fetchTransactions` in which the transactions tried to load before the safe and then the `undefined safe`  error came, I just make the `fetchTransactions` promise to wait until `fetchSafe` ends.
> Feature #340: Threshold undefined

- src/logic/tokens/store/actions/activateTokensByBalance.js
- src/utils/storage/index.js
Closes #348 
- The tokenBalances list updated to localStorage by the function `activateTokensByBalance` where in wrong format [balance] instead of [tokenAddress, balance]. When the app loads the info from the localStorage, an exception was thrown trying to load the balances and the safe was just removed from the available lists.
> Bug #348: Safelist entries get removed

- src/routes/safe/components/Transactions/TxsTable/columns.js
This PR closes #356, by:
Using the `submissionDate` of the outgoing transactions for the `date` field in the Transactions table.
> Bug #356: Oldest executed transaction goes on top of transaction list after execution

- src/routes/safe/store/actions/fetchSafe.js
This PR closes #352, by:
- ensuring we're not comparing checksummed vs lowercased addresses for the `owners` addresses
As stated in https://github.com/gnosis/safe-react/issues/351#issuecomment-566455101, it's related to #351 and the solution is similar.
> Bug #352: Owner shown multiple times

- src/logic/safe/safeTxSigner.js
- src/logic/safe/transactions/gasNew.js
- src/routes/safe/store/actions/processTransaction.js
- src/test/signatures.blockchain.test.js
- yarn.lock
Inside the function `generateSignaturesFromTxConfirmations` the keys of the confirmationsMap must be set to lower case before sorting them.
If not, there are cases like the following one that will make the contract to not pass this condition (currentOwner > lastOwner): https://github.com/gnosis/safe-contracts/blob/development/contracts/GnosisSafe.sol#L254
Safe with 2 owners and threshold 2
Owner1: 0xeA...
Owner 2: 0xEe...
`checksum(Owner1) > checksum(Owner2)` but `toLowerCase(Owner1) < toLowerCase(Owner2)`
The order of the confirmations in the `txData`would be different.
> Fix signatures order in txData

- src/routes/safe/store/actions/fetchTransactions.js
Things that are done in this PR:
- treat DCD particularly and hardcode `symbol` and `decimal` values
- for those ALTERNATIVE_TOKEN_ABI contracts, we were converting the `symbol` to ASCII, and we had to convert from hex to string instead
- the `incoming-transactions` endpoint is returning the `executionDate`, so no request for that value to the blockchain is required
> (Fix) Transaction List not loading and handle DCD token

- src/components-v2/dataDisplay/DividerLine/arrow-down.svg
- src/components-v2/dataDisplay/DividerLine/index.js
- src/components-v2/dataDisplay/TextBox/index.js
- src/components-v2/dataDisplay/index.js
- src/components-v2/feedback/Loader/index.jsx
- src/components-v2/feedback/index.js
- src/components-v2/index.js
- src/components-v2/layouts/ListContentLayout/Layout.jsx
- src/components-v2/layouts/ListContentLayout/List.jsx
- src/components-v2/layouts/ListContentLayout/index.js
- src/components-v2/layouts/ListContentLayout/style.js
- src/components-v2/layouts/index.js
- src/components-v2/safeUtils/AddressInfo/index.js
- src/components-v2/safeUtils/index.js
- src/components-v2/surfaces/Collapse/index.js
- src/components-v2/surfaces/index.js
- src/components-v2/utils/index.js
- src/components-v2/utils/modals/GenericModal/index.js
- src/components-v2/utils/modals/index.js
- src/components-v2/utils/modals/utils.js
Ticket: https://app.zenhub.com/workspaces/safe-multisig-5ce554debb310a35b2f8b6f8/issues/gnosis/safe-react/530
We have discussed with @mikheevm and the rest of the team to start structuring the components in a better way. Also, adding and integrating `styled-components` will help us with this task.
Current status
* Components folder contains a lot of components without any semantic grouping.
* There are a lot of duplicated code, we want to create re-usable components for these cases.
* There are different ways to write css (inline, .scss, as Components with MUI). The goal is to normalize the existing variants with styled-components/MUI
We suggest to create a new temporary folder called `components-v2` where we can start to write new components with unified criteria. As time goes by, most …
> Components V2

- package.json
- yarn.lock
setting "^1.0.0-beta.25" in the package.json and running yarn install, it brings 1.0.0-beta.32 and produces the bug previously reported here: https://github.com/gnosis/safe-react/pull/572.
I suggest to remove the `^` and fix the version to "1.0.0-beta.25"
> Fix web3connect version

- src/logic/contracts/__mocks__/safeContracts.js
- src/logic/safe/transactions/send.js
- src/logic/safe/transactions/txHistory.js
- src/routes/safe/components/Apps/index.jsx
- src/routes/safe/components/Apps/sendTransactions.js
- src/routes/safe/store/actions/__tests__/utils.test.js
- src/routes/safe/store/actions/createTransaction.js
- src/routes/safe/store/actions/processTransaction.js
- src/routes/safe/store/actions/utils.js
* Send the origin field when saves the TX
* Refactor of `getApprovalTransaction` and getExecutionTransaction
* Fixes issue #563
> (feature)  Adding origin for Apps Transactions

- src/components/Sidebar/SafeList/index.jsx
Closes #454
It should work as intended now.
> (fix) sidebar contents' scrolling

- src/logic/wallets/store/middlewares/providerWatcher.js
So the reason for this problem was that:
```js
const watchedActions = [ADD_PROVIDER, REMOVE_PROVIDER]
```
in the production build became `[undefined, undefined]` and thus `  if (watchedActions.includes(action.type)) {` didn't work in providerWatcher
I don't know the exact reason for this, whether it's a circular dependency, we messed up the imports or some webpack bundling bug but by using an absolute path it works
> Bug: Accounts/Network are not updated in production build

- src/routes/safe/store/actions/processTransaction.js
Adding the same fix as in `createTransaction`. When sending more than 1 tx to multisend, the second one fails because a wrong gas estimation.
> processTransaction: add gasLimit in development

- src/logic/collectibles/sources/OpenSea.js
- src/logic/collectibles/store/actions/fetchCollectibles.js
- src/routes/safe/components/Balances/Collectibles/types.js
This PR closes #669
Instead of picking the network Id from the web3 provider, we rely on the network name specified in the env variable.
> (Fix) Collectibles not displayed while disconnected

- src/logic/tokens/utils/tokenHelpers.js
- src/routes/safe/components/Balances/SendModal/screens/ReviewCollectible/index.jsx
- src/routes/safe/store/actions/fetchTransactions.js
The wrong attempt to differentiate an ETH from an ERC-721 token `transfer` was to look for a `name` method, in the ERC-721 token code.
That assumption missed completely the existence of ERC-20 tokens.
This fix looks for a `decimals` method. If it's not there, then it's considered an ERC-721 token.
We're assuming that an ERC-721 token won't have a `decimal` method, based on the standard and also in the list of the `ERC721Full` OpenZeppelin contract:
```bash
➜ eth abi:methods ./ERC721Full.json
095ea7b3	approve(address,uint256)
70a08231	balanceOf(address)
6c0360eb	baseURI()
081812fc	getApproved(uint256)
e985e9c5	isApprovedForAll(address,address)
06fdde03	name()
6352211e	ownerOf(uint256)
42842e0e	safeTransferFrom(address,address,uint256)
b88d4fde …
```
> (Fix) Wrong value for ERC-20 tokens transfers

- src/logic/safe/transactions/awaitingTransactions.js
- src/routes/safe/container/selector.js
- Set `cancelled` on transaction to true if there's executed transaction with the same nonce which is not cancellation transaction
- Don't reassign `transaction` in `getAwaitingTransactions` because it won't do anything (Since we're inside .filter method), instead use a boolean variable
> BUG: Transactions with the same nonce won't show "Cancelled" status if one of them was executed

- src/routes/safe/store/models/incomingTransaction.js
This PR solves an issue with the upcoming `type` that will be sent from the backend for the `incoming transactions`.
It sets a default/generic `INCOMING` type, for those unspecified types.
@francovenica, In staging env everything must remain the same, there shouldn't be any differences.
> (Fix) set `INCOMING` as the default `type` for incoming txs

- src/logic/safe/transactions/txHistory.js
- src/routes/safe/store/actions/utils.js
This PR closes #730, by changing the expected SUCESS_STATUS from `202` to `201`: https://github.com/gnosis/safe-react/commit/7c7d3f38a32a9e81a64973887698abed1978b239
Also fixes an issue with the newly created Safes where it fails to create the first transaction: https://github.com/gnosis/safe-react/commit/8f48d3c27a3d8273aa17bf24a92e53fa56f3f88b
> (Fix) Adapt app to back-end changes

- src/logic/tokens/utils/tokenHelpers.js
- src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/utils.js
This PR fixes the wrong identification of the upgrade transactions.
The `isUpgradeTransaction` method was looking for methods in the wrong order (#599). This worked fine before the #610, which set the proper order for the upgrade methods.
**Note:** Added the last fix, the version wasn't properly extracted from the data object: https://github.com/gnosis/safe-react/pull/740/commits/1161b213fedb59654032503cae70049f8d7590a9
> (Fix) Change the order of the upgrade methods lookup

- package.json
- src/logic/safe/transactions/offchainSigner/ethSigner.js
- src/logic/safe/transactions/offchainSigner/index.js
- src/routes/safe/store/actions/createTransaction.js
- src/routes/safe/store/actions/processTransaction.js
- yarn.lock
Onboard.js fixed their bug for `eth_sign` for hardware wallets, now we can check if the connected wallet is a HW wallet and fallback to `eth_sign`
To be updated and merged when onboard.js releases a new version
> Feature: Use eth_sign for hardware wallets connected via onboard.js

- src/logic/contracts/methodIds.js
- src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/index.jsx
- src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/utils.js
This PR fixes #746, by fixing a typo for the ~`changedThreshold`~ `changeThreshold` action
| before fix | after fix |
|---|---|
|![image](https://user-images.githubusercontent.com/3315606/78837856-59cab400-79cb-11ea-9f6f-0439097c49ad.png)|![image](https://user-images.githubusercontent.com/3315606/78837868-5fc09500-79cb-11ea-887c-66e3257844f7.png)|
> (Fix) Properly decode threshold value in tx details

- src/logic/tokens/store/actions/fetchTokens.js
- src/logic/tokens/utils/tokenHelpers.js
- src/routes/safe/store/actions/fetchTransactions.js
- yarn.lock
This PR fixes #678, by checking for `decimals` method in transferredTokens.
Previously we were looking for `decimals` hash in the contract `code`.
There are some contracts like `USDC` tokens who happen to be behind a `FiatTokenProxy` making it upgradable, but also giving false positives for the `decimals` hash lookup in the code.
By directly calling the `decimals()` method, we interact with the contract and can be sure that the `decimals()` method is present.
> (Fix) Display proper values for ERC20 tokens

- src/routes/safe/store/actions/fetchTransactions.js
So the reason for this bug was that the recipient address was a contract who had methods from ERC20 standard implemented (name, decimals, transfer, totalSupply, etc) and therefore we thought that this was a token transfer transaction.
This PR fixes it by falling back to custom transaction in case we get any error when fetching token info
> Bug #766: Safe shows only incoming transactions

- package.json
- src/logic/wallets/utils/walletList.js
- yarn.lock
There was a problem with wallet check pending forever when you connect with walletconnect, this was probably because walletconnect's bridge returns 500, this PR solves that by replacing the bridge with gnosis' one
> Feature: Replace walletconnect's wc bridge with gnosis one

- src/config/index.js
Service will still support the old endpoint alias, but as it's already deployed in every environment this can be merged
EDIT: Deployment is still ongoing as travis is stuck, but should be ready in a few minutes
> Rename incoming-transactions url to incoming-transfers

- src/logic/tokens/store/reducer/tokens.js
- src/logic/tokens/utils/formatAmount.js
- src/routes/safe/components/Transactions/TxsTable/ExpandedTx/IncomingTxDescription/index.jsx
- src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/index.jsx
- src/routes/safe/components/Transactions/TxsTable/ExpandedTx/index.jsx
- src/routes/safe/components/Transactions/TxsTable/columns.js
- src/routes/safe/store/actions/fetchTransactions.js
- src/routes/safe/store/models/incomingTransaction.js
This PR works on the requirement stated on https://github.com/gnosis/safe-react/pull/799#issuecomment-619045019, by:
- Creating a common function to format values for incoming and outgoing txs (https://github.com/gnosis/safe-react/commit/e94a448de6e7ae551eecec92ec7b084dc8087b97, https://github.com/gnosis/safe-react/pull/812/commits/a9bde84fa0237ed6bc62253b766c3d19bb00a0d6)
- Displaying unformatted value in the tx detailed view (https://github.com/gnosis/safe-react/commit/9a18d1d9f8a823291cf972c0acf3447e98878537)
- Making a few improvements around the Incoming Txs:
- No more `Nonce` label in the details (https://github.com/gnosis/safe-react/commit/d45199bef0494bc07197f0d72fd11e0f264a2955)
- Properly formatting amount column in the overview …
> (Feature) Tx Table amount notations

- src/routes/safe/components/Apps/ManageApps.js
- src/routes/safe/components/Apps/utils.js
Closes #834: Do not remove trailing slash from Safe app url
- `cleanedAppUrl` (url without trailing slash) should only be used for loading the `manifest.json`  and the icon. Else relative paths (required for ipfs) in the Safe app will break.
> Fix #834: Do not remove trailing slash from Safe app url

- src/theme/mui.ts
In `safe-react-components` we do not have a custom mui theme so I included the fix there and not inside safe-react-components
**BEFORE:**
**AFTER:**
> Bug: Stepper component non-transparent bg

- src/logic/safe/transactions/awaitingTransactions.ts
- src/routes/safe/store/actions/fetchTransactions.ts
It happened to me when I created a new safe. After a few seconds and no matter what tab I was in, the app was crashing with this message:
> Fix app crashing when safeTransactions is undefined

- src/routes/safe/components/Balances/index.tsx
- There was a bug on balances tab: when the user wanted to change his safe using the sidebar he couldn't.
- Also, the collectibles tab was available for 1.0.0 users, now it's hidden.
> (Fix) Balances tabs fixs

- src/logic/contractInteraction/sources/ABIService/index.ts
This PR closes #994, by changing the way we identify which type of method the safe can interact with
> (Fix) Properly identify methods to interact with

- src/components/forms/validator.ts
- src/routes/safe/components/Balances/SendModal/screens/AddressBookInput/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/SendFunds/index.tsx
- Working on #1013 I found that was possible to add a value on the send funds modal without selecting an asset
This prs fixs that by disabling the review button:
> (Fix) Fix undefined for maxValue validator  in case there is no token selected

- package.json
- src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/utils.ts
- yarn.lock
In `getTxData`, if the transaction fulfils `if (tx.dataDecoded)` but neither of nested if statements, getTxData would return an empty object, but `TxDescription` relies on recipient address returned from this function
This PR solves it by falling back to `tx.recipient` in case no if statement worked 
Example tx (safeTxHash 0x626ffc5f7b3f3dfb551d57d62cc489f6d9f66d38bb61dda913ce444692d675b5) https://safe-transaction.mainnet.gnosis.io/api/v1/safes/0xEb3107117FEAd7de89Cd14D463D340A2E6917769/transactions/
> Bugfix: 2.3.0 Cannot read property lowercase of undefined when expanding a transaction

- src/config/development-mainnet.ts
- src/logic/tokens/utils/tokenHelpers.ts
- src/routes/safe/store/actions/transactions/utils/transactionHelpers.ts
So the problem was that the safe included a contract interaction with ENS contract which implements `safeTransferFrom` method, but no proper ERC721 standard. Thus we were trying to get symbol for it and it returned an error which was uncatched.
This PR:
- Hardcode ens contract address to `isSendERC721Transaction`
- Wrap all methods getting token info with try/catch so it doesn't fail with tokens not implementing standard properly
Will create a follow up issue on how we can prevent this in the future
> Bug: 2.3.1 Outgoing transactions not showing

- package.json
- src/routes/safe/store/actions/transactions/fetchTransactions/loadOutgoingTransactions.ts
Currently the interface treats every empty transaction as a cancellation, which is not true. Even if there's no transaction for the "cancellation" transaction to cancel, it wouldn't display it in the transactions table. This PR fixes it by checking if there's a pending transaction to actually cancel
TODO: 
- Fix the label (currently an empty transaction is shown as cancellation transaction). Let's address this in the new transactions UI
> Bug 2.5.1: Can't execute a transaction if one of the previous transactions was empty

- package.json
- src/logic/tokens/store/actions/fetchTokens.ts
- src/logic/tokens/utils/tokenHelpers.ts
- src/routes/safe/store/actions/transactions/fetchTransactions/loadOutgoingTransactions.ts
- src/routes/safe/store/actions/transactions/utils/transactionHelpers.ts
Related to #1068 
- There was a problem with different safes in which the symbols of the tokens were not displayed. 
- After some research, we found that this [PR](https://github.com/gnosis/safe-react/pull/1067) was related, basically and else condition was missing when checking if storedTokenInfo was null and then we were just returning the default value, this adds that condition
Before:
After:
> (Hotfix) Tx decoding

- src/logic/wallets/store/selectors/index.ts
- src/routes/load/components/Layout.tsx
- src/routes/load/container/Load.tsx
This PR closes #1103, by fixing a condition and logging an error if there's any.
On a personal note, I don't think this is necessary at all. The existence of the `safeAddress` should be verified way back in the Stepper.
I left a TODO in place so we can better review later.
> (Fix) Load Safe if the address exist

- src/routes/safe/components/Apps/confirmTransactions.tsx
It was working for ETC20 tokens because the value was encoded in the data field.
> Allow HX values

- src/routes/safe/components/Apps/index.tsx
This PR solves the issue in `development` that prevents the app from starting up
> (Fix) Prevent accessing `contentWindow` if `iframe` is `null`

- src/routes/safe/components/AddressBook/CreateEditEntryModal/style.ts
- src/routes/safe/components/AddressBook/DeleteEntryModal/style.ts
- src/routes/safe/components/Balances/SendModal/index.tsx
- src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/index.tsx
- src/routes/safe/components/Settings/ManageOwners/EditOwnerModal/style.ts
- src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/index.tsx
- src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/index.tsx
Closes #1147 
Now all modals have the same alignment settings (120px from top navbar).
Maybe we have to think to implement Generic Modal from [safe-react-component](https://components.gnosis-safe.io/?path=/docs/utils-modals-generic--modal).
> Fix: Standardized modal alignment settings

- src/routes/safe/components/Balances/SendModal/screens/SendFunds/index.tsx
This PR:
- Fixes https://github.com/gnosis/safe-react/issues/1192 by setting inclusive param to false for minValue validator in send funds form
> BUG 1192: Set inclusive false for minValue validator in sendfunds form

- package.json
- src/routes/safe/components/Apps/utils.ts
This hotfix closes #1262, by:
- updating the Balancer Pool URL
- also setting the Safe's version to `2.10.1`
> (Hotfix) Update Balancer Pool IPFS URL

- src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/CustomDescription.tsx
- src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/Value.tsx
I had to mock a long value. The result is like so:
Once it's merged, we can re-test on staging.
> Long values break Transaction decoding UI

- src/logic/contracts/generateBatchRequests.ts
- src/logic/safe/store/actions/transactions/fetchTransactions/loadIncomingTransactions.ts
Dani recently spot this error on this rinkeby safe 0x32d6F7bf55b6692E0d16bFB26317b7D36b494f4a
It failed to request gas used by a transaction and then a destructure statement was used on a null value. This PR checks if the returned values are valid
> Bug: incoming transactions do not load if it fails to fetch gas for a transaction

- src/routes/safe/components/Balances/SendModal/screens/AddressBookInput/index.tsx
This PR closes #1386, by preventing the use of the eth address as `name`. And by extracting the contract information from the Address Book if it exist.
Note: despite this fixes the issue. I think we should review the whole `AddressBookInput` component, as its growing big and hard to maintain.
> (Fix) Recipient address used as name as well

- src/logic/safe/store/reducer/safe.ts
Closes #1398 
- Fixes the issue generated by a race condition between `checkAndUpdateSafe` and `sendAddOwner`. 
- The main issue was that the `addSafeOwner` action wasn't avoiding add an owner if it already exists in the owner's list
> (Bugfix) Owners duplicated

- src/config/index.ts
This PR:
- Replaces any with a more strict type
As a general reminder, we shouldn't use any in the new code
> Remove any in src/config/index.ts

- src/config/index.ts
In a discussion related to how to deal with `getExplorerInfo` (it's a function that returns the explorer URL to inspect an address or transaction). Pablo and I suggested that we should have a separate file in order to define all the functions that should handle a particular case depending on the current network. 
The intention was that at the moment of creating a new network, a developer should go to `src/config` folder and replicate all the existing files with the new network. Giving it a second thought I think it is an overkill, at the moment `getExplorerInfo` it's the only function that needs a special treatment depending on the network.
Another alternative is to create another file `utils.ts (?)` where we can handle all these particular cases, but we will end having an index.ts and a …
> Make getExplorerInfo return values per network

- src/routes/safe/container/index.tsx
This PR closes #1474, by:
- adding an equality function to the `useAction` hook for the featuresEnabled selector
> (Fix) "Approve transaction" modal closes

- src/config/index.ts
Etherscan links are not working properly. A / is missing on link creation funcion
Fixes #1495
> Fix etherscan links

- .travis.yml
When adding `Volta` to be deployed on PRs development environment could end up having Rinkeby or Volta version.
Ensure that only rinkeby version is deployed on development environment
> Fix development deployment to always use rinkeby network

- src/components/ConnectButton/index.tsx
When a user disconnected the Safe from the wallet, the Safe didn't remove the provider leading to the error: `Provided address "" is invalid, the capitalization checksum test failed, or it's an indirect IBAN address which can't be converted.`
This PR solves that issue by disconnecting the provider when there's no address provided by the connected wallet.
> (Fix) Remove the provider when the site is disconnected

- package.json
- yarn.lock
There are issues when using walletconnect in all networks after updating web3 to v1.3.0
We are going to rollback to v1.2.11 that is the latest version working correctly
> Rollback web3 to v1.2.11 to avoid issues with walletconnect

- package.json
- yarn.lock
Desktop build for Windows is breaking due to some dependencies. We have to update @truffle/contracts in order to use web3@1.2.9 to solve them. We also force the use of latest version of node-gyp to minimize memory leaks in Windows machines
> Fix v2.14.1 build for Windows

- src/logic/collectibles/utils/index.ts
- src/logic/safe/store/actions/transactions/fetchTransactions/loadIncomingTransactions.ts
Closes #1587 by:
- Fixed default condition for incoming transactions: instead of using native symbol if fetching the symbol fails, first check if it's an ENS address, because the ENS contract address does not support `symbol()` method
- For outgoing transactions, there was a missing await on `symbol()` so I added it
> (Fix) #1587 - Ens mislabeled as eth

- src/routes/safe/components/AddressBook/EllipsisTransactionDetails/index.tsx
- src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/index.tsx
This PR closes #1665, by displaying the "native coin" outgoing transactions.
Also, I ran into an error in the console when expanding the tx view:
I fixed that by replacing a react-fragment with an array, as it's suggested in the log.
> (Fix) Native Coin transfer not shown

- package.json
- yarn.lock
Use resolutions to handle `babel` versions
Upgrade two minor dependency versions to remove incorrect version warning
> Clean dependencies warnings

- src/logic/safe/store/reducer/safe.ts
Fix minor typo left behind after fixing #1693 
Not critical because this branch is used in very limited cases. Information is updated in case is needed but wouldn't prevent closing modals or transaction details if no update is necessary.
> Fix typo in ADD_OR_UPDATE_SAFE reducer

- src/components/TransactionsFees/index.tsx
- src/logic/contracts/safeContracts.ts
- src/logic/hooks/useEstimateTransactionGas.tsx
- src/logic/safe/transactions/gas.ts
- src/logic/wallets/ethTransactions.ts
- We are having a problem with walletConnect, seems that `web3.call` is not returning a value of `requiredTxGas`, instead it's returning `undefined`. We put the same params (to, from and data) that we used on a test on metamask but the problems seems still there. So I'll disable the feature until we find a solution for walletConnect
> (Feature) Disable gas estimation for WalletConnect

- src/logic/hooks/__tests__/useEstimateTransactionGas.test.ts
- src/logic/hooks/useEstimateTransactionGas.tsx
Closes #1804 by:
- Fixing the `checkIfTxIsExecution` method to validate that if there is preApprovingOwner: it should also reach the threshold to be considered an `executionTransaction` and not a `transactionApproval`
- Add tests
> (Fix) - #1804 Tx gas estimation fail for threshold >= 3

- src/routes/safe/components/Apps/utils.ts
Update balancer management app with new keys to avoid rate limiting
@francovenica this app can only be tested on mainnet:
https://ipfs.io/ipfs/QmQsmxUVtcEWmKcXxKwYsZFKJ2kDdqqjqdExujiGY1g3tV
> Update balancer pool management app with new keys

- src/routes/safe/components/Apps/utils.ts
Update balancer exchange app to latest version
@francovenica this app can only be tested on mainnet:
https://ipfs.io/ipfs/QmRb2VfPVYBrv6gi2zDywgVgTg3A19ZCRMqwL13Ez5f5AS/
> Update balancer exchange app

- src/routes/open/components/SafeOwnersConfirmationsForm/index.tsx
Quite a few users have pointed out that it was not clear that owners can be changed after the Safe is created. E.g. "- Once I’ve created a wallet, it seems it’s possible to revoke and change a signer, but it wasn’t immediately clear if I can change the threshold."
> Update copy during onboarding

- package.json
- src/routes/safe/components/Apps/components/ConfirmTransactionModal.tsx
- src/routes/safe/components/Transactions/helpers/EditTxParametersForm/index.tsx
This is a patch to restore all safe transactions to be multisends.
- Safe Apps have failing transactions in some cases like issue #1848 
- Remove safeTxGas validation where it always have to be lower than gasLimit
> Hotfix v2.19.2

- src/routes/safe/components/Apps/components/ConfirmTransactionModal.tsx
This PR:
- Fixes https://github.com/gnosis/safe-react/issues/1848
Thanks to @dasanra for debugging
> Bug: if we don't use multisend, ethereum value is not passed

- src/logic/hooks/useEstimateTransactionGas.tsx
- src/logic/safe/transactions/gas.ts
- src/routes/safe/components/Apps/components/ConfirmTransactionModal.tsx
- src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/Review/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/ReviewCollectible/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/ReviewSendFundsTx/index.tsx
- src/routes/safe/components/Settings/Advanced/RemoveModuleModal.tsx
- src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/screens/Review/index.tsx
- src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/screens/Review/index.tsx
- src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/Review/index.tsx
- src/routes/safe/components/Settings/SpendingLimit/NewLimitModal/Review.tsx
- src/routes/safe/components/Settings/SpendingLimit/RemoveLimitModal.tsx
- src/routes/safe/components/Settings/ThresholdSettings/ChangeThreshold/index.tsx
- src/routes/safe/components/Transactions/TxsTable/ExpandedTx/ApproveTxModal/index.tsx
- src/routes/safe/components/Transactions/helpers/EditTxParametersForm/index.tsx
Closes #1849 by:
- Re-enabling the validation of `safeTxGas < gasLimit` but allowing the user to edit the `gasLimit` value
- Now when the user modifies the `safeTxGas` manually, the estimation will run again to check if the amount if enough or the transaction will fail
Closes #1846 by:
- Sending the user `txParameters` to `createTransaction` method
> (Fix) - Safe tx gas capped

- src/routes/safe/components/Transactions/GatewayTransactions/TxCollapsedActions.tsx
Previously the tooltip for the action buttons was tied to the icon, now it's related to the whole button.
> [Transaction List v2] Action buttons tooltip

- src/routes/safe/components/Transactions/GatewayTransactions/OwnerRow.tsx
If the owner's name is not in the Address Book, show nothing.
> [Transaction List v2] Avoid displaying `UNKNOWN` in owner's list

- src/routes/safe/components/Apps/components/ConfirmTransactionModal.tsx
Now that we allow that safe apps create only one tx this transaction should use Ether value if required.
Some apps could send the ETH value as Hex, but the transaction service doesn't expect this but an integer string.
We should parse the value first so the transaction service is able to handle it
> Allow hex value for transaction value in safe apps

- src/routes/safe/components/Settings/Advanced/RemoveModuleModal.tsx
- On `removeModule` we were passing the `user nonce` instead of the current `safe nonce`, which then lead to creating a transaction with a potentially higher nonce that leaves the safe in blocked status until the user creates more transactions with lower nonces
> (Fix) - CreateTransaction nonce usage on removeSelectedModule

- src/routes/safe/components/Transactions/GatewayTransactions/TxCollapsed.tsx
- src/routes/safe/components/Transactions/GatewayTransactions/styled.tsx
This PR closes #1895, by applying styles to the tx row whose status is 'failed'
> [Transaction List v2] Transaction with 'failed' status has different appereance

- src/routes/safe/components/Transactions/GatewayTransactions/MultiSendDetails.tsx
When we have a multisend action that it's an ETH transfer is not being shown in transaction details
Before:
After:
> Fix decoded multisend actions not showing for eth transfers

- src/routes/safe/components/Settings/ThresholdSettings/ChangeThreshold/index.tsx
- src/routes/safe/components/Transactions/helpers/EditableTxParameters.tsx
Closes #1905 and #1919
Stores threshold value if edited when changing transaction parameters
Fix threshold update issues
> Fix threshold reset when edit tx parameters

- src/logic/collectibles/sources/Gnosis.ts
- src/logic/tokens/api/fetchSafeCollectibles.ts
Closes #1965 by:
- Fixing the type of the returned object from the relayer and updating the usage of that object to load the list of collectibles
> (Fix) Collectibles display 

- src/routes/safe/components/Transactions/GatewayTransactions/QueueTxList.tsx
When we execute a transaction there is an issue when the queue gets empty. Add a check on transaction list before trying to assign guard element to infinite scroll in pending list
> Fix UI break after transaction is executed

- src/routes/safe/components/Apps/utils.ts
Mushroom was having rate limit issues with RPC endpoint. We replaced it with one provided by them
Lido finance was having a fixed "Rinkeby" label in Mainnet environment
> Update Mushrooms and Lido apps for release

- src/components/forms/validator.test.ts
- src/components/forms/validator.ts
- src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/screens/OwnerForm/index.tsx
- src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/OwnerForm/index.tsx
Closes #1991 by:
- Adding `addressIsNotSafe` validator and using it on both `replace` and `addOwner` modal
> (Feature) - #1991 Prevent that a Safe adds itself as an owner

- src/routes/safe/components/Balances/SendModal/screens/SendFunds/TokenSelectField/index.tsx
Discovered by @francovenica, in `development`
The fix updates where the token's balance is extracted.
> (Fix) Invalid amounts in Send Funds modal

- docs/networks.md
- src/config/networks/energy_web_chain.ts
- src/config/networks/local.ts
- src/config/networks/mainnet.ts
- src/config/networks/rinkeby.ts
- src/config/networks/volta.ts
- src/config/networks/xdai.ts
- src/logic/safe/hooks/useTokenInfo.tsx
- src/logic/safe/utils/spendingLimits.ts
- src/logic/tokens/store/actions/fetchSafeTokens.ts
- src/routes/safe/components/Settings/SpendingLimit/NewLimitModal/Review.tsx
- src/routes/safe/container/selector.ts
Based on an issue found by @francovenica, this PR migrates the `nativeCoin.address` identifier from `0x000` to `ZERO_ADDRESS`
> (Chore) Update `nativeCoin` address to ZERO_ADDRESS

- src/routes/safe/components/Apps/communicator.ts
**The problem:**
Safe App communicator (class listening to messages from a safe app) sometimes may not initialize properly and it resulted in a safe app failing to communicate.
**The reason:**
The communicator has two constructor parameters - iframe and safe app info. It uses the iframe element to send messages to the app, but AppFrame component has quite some logic that may result in safe app iframe not rendering:
https://github.com/gnosis/safe-react/blob/development/src/routes/safe/components/Apps/components/AppFrame.tsx#L279-L293
But the `useAppCommunicator` hook is still called and inside the hook it checked if `iframeRef.current` exists. The thing is that if it doesn't exist at the time of execution, it wont trigger the hook again because it's a ref.. So I changed the function …
> Bug: Safe app communicator is not properly initialized sometimes, thus app fails to communicate

- src/routes/open/components/SafeOwnersConfirmationsForm/index.tsx
- src/routes/open/components/SafeOwnersConfirmationsForm/tests/calculateValuesAfterRemoving.test.ts
- src/routes/open/components/fields.ts
- src/routes/open/utils/padOwnerIndex.ts
This PR closes #2082, by:
- fixing the owner's discovery in the list
- due to recent changes (#2020), the number of the owner in the list has changed
- moving the zero-padding for owners order into a helper function
- reviewing if there's no other place where this padding will affect the app
Edit: fixed tests for `calculateValuesAfterRemoving` [`db17edb` (#2084)](https://github.com/gnosis/safe-react/pull/2084/commits/db17edb6403d16914f912b73f790e839f02a105b)
> (Fix) Delete the correct owner during Safe creation

- src/components/App/index.tsx
- src/logic/safe/hooks/useLoadSafe.tsx
- src/logic/safe/hooks/useSafeScheduledUpdates.tsx
- src/logic/safe/store/actions/fetchSafe.ts
- src/logic/safe/store/selectors/index.ts
- src/logic/tokens/store/actions/fetchSafeTokens.ts
Closes #2083 
Send funds form balance was shifting from 0 to real value in send fund form. It was caused by a front running issue while fetching ETH balance from blockchain and from client gateway at the same time. Value from the client gateway wasn't parsed correctly giving as a result the base hardcoded value -> 0.
- Added parsing to avoid overwritting the correct value.
- Remove fetch ETH value from blockchain to be consistent with value showed in assets
While fixing this issue I also fixed a front running issue setting totalFiatBalance value to 0
- Fetch current value from local state
- Overwrite hardcoded totalFiatBalance value if we already have a value in the state
> Fix balance value in send funds form

- src/routes/safe/components/Transactions/helpers/EditTxParametersForm/index.tsx
This issue closes #2087 
From this version we will be showing Ethereum transaction parameters only when we execute an onchain transaction. This causes that when estimating if someone changes safeTxGas won't be able to see gasLimit but we will be enforcing to set it lower. This was not a hard requirement, just a help for the user that safeTxGas doesn't need to be over gasLimit.
- Remove safeTxGas validator checking is lower than gasLimit
> Remove validator to check that safeTxGas is lower than gasLimit

- src/routes/safe/components/Apps/utils.ts
Wallet connect app wasn't correctly displaying the banner. We uploaded a new version of walletConnect to IPFS with this issue solved
> Update wallet connect to correctly show the banner

- package.json
- src/routes/safe/components/Apps/components/ConfirmTxModal/ReviewConfirm.tsx
- txValue in Safe Apps transaction was converted from wei to display in the interface and sent as Eth when creating the transaction while the createTransaction method is expecting this value in wei
> Hotfix v3.3.1

- package.json
- src/logic/safe/transactions/offchainSigner/index.ts
Offchain signing is not working propperly for v1.0.0 of the smart contracts as reported in #2130 
We are rolling back this change to avoid issues for people using safes with smart contract version v1.0.0
> [Hotfix v3.3.2] Rollback offchain signing to require v >= 1.1.1

- src/logic/safe/store/models/types/gateway.d.ts
- src/routes/safe/components/Transactions/TxList/TxData.tsx
Closes #2136.
As franco a Lylia reported, some tx could explode when the details are opened in the tx list. It only happens when it's consuming the client gateway in production, but it does not in staging. That's why we requested Jose to verify this via slack.
Independently of what Jose says, we could add a simple fix to prevent this error and that's validating if `toInfo` is defined before accessing its data.
> Fix: toInfo could be null

- src/routes/safe/components/Apps/components/AppFrame.tsx
closes #1753.
The problem is produced because of a loading placeholder we are using while the safe-app is being fetched. That placeholder pushed down the iframe. To fix this problem I added a `display` property (css) to hide the Iframe while the safe-app loads. 
@dasanra perhaps we can include this fix in the current sprint as the fix is really straightforward, with no risk that anything could break.
> Prevent rendering safe-app outside its container while loading

- src/routes/safe/components/Apps/utils.ts
Add Gnosis Auction Starter app
This app is used to start new auctions on Gnosis Auction.
The app is available on Mainnet and Rinkeby
> Add Gnosis Auction Starter app

- src/logic/addressBook/store/middleware/addressBookMiddleware.ts
Fixes the 1st bug in #2189.
Not sure what the intention of this code was (introduced in #2101) but it seems to be breaking some of the existing use cases.
Let's revert it for now and re-think what we wanted to achieve there.
> Fix the address book, don't filter the addresses

- .storybook/preview.js
The storybook was completely broken because it needs a Redux provider.
> Fix the storybook: add a redux provider

- package.json
- src/routes/safe/container/selector.ts
- When opening a safe that is stored locally after v3.5.0 update the app crashes
There was a type change in one of the parameters in local store. For already loaded safes is not stored correctly. The object is properly created once the information is fetch from the client-gateway again.
We will return an empty list when we detect an error and wait until we update the information from the client-gateway to show the assets list
> Fix v3.5.1

- src/routes/safe/components/Apps/communicator.ts
**The problem:**
curve.fi links to their DAO app from their safe app, when you land there, it won't work.
**The reason:**
We use apps URL when sending a message to the app and the URL gets changed within the iframe
**The solution:**
Use a wildcard for sending messages. We cannot listen to URL changes within the iframe because browsers restrict it for cross-origin iframes. I'm not 100% sure about possible security risks, the only one I can think of is if someone can load a malicious app within the iframe.
**Testing**
1. Add curve.fi as a custom app
2. Click "DAO" in the app header
Current production:
3. DAO app doesn't connect to a safe
This PR:
3. DAO app connects to a safe
> Bug: Apps SDK won't work if you change an origin within iframe

- src/routes/safe/components/Apps/hooks/useIframeMessageHandler.ts
This PR:
- removes console.error about a message without a message-id
Safe Apps developers are overwhelmed with this message thinking this is an error. This message comes from sdk v0.1 beta integration and doesn't really mean anything
> Feature: Remove logging about message without a messageId in Safe Apps

- src/logic/tokens/store/actions/fetchSafeTokens.ts
**What**:
Fixes #2224
<br />
**Why**:
> We use exponential backoff to refetch the balances in case of an error with increasing delay. Because the initial delay is not set this will result in an increased amount of balances request in case of an error.
<br />
**How**:
Getting rid of the exponential backoff strategy as it's not necessary to have balances up to date.
We're already polling (every 15s) for updated data.
Also, by accessing the `balances` URL, there's an additional request for balances https://github.com/gnosis/safe-react/blob/15ae933a18c2fbd6c092e3cd95445678247621c6/src/routes/safe/components/Balances/index.tsx#L56
<br />
* go to "Network" tab in devTools
* filter by "trusted=false" or "balances/USD" (the latter will depend on the currency you've selected)
* …
> (Fix) Remove exponential back-off strategy for balance fetching

- .github/PULL_REQUEST_TEMPLATE.md
**What**:
remove `- [ ] TypeScript definitions updated` from PR template
**Why**:
As we are not a third-party library, we shouldn't use make use TS definition (.d.ts) https://stackoverflow.com/questions/21247278/about-d-ts-in-typescript/21247316#21247316. 
Indeed, we should remove them from our code.
An example of misuse can be found here 
In the PR there was no .d.ts file modified but the checkbox was checked. 
So to avoid confusion about checking it when we haven't modified any `.d.ts` file, I propose removing it. 
Also **we should not use .d.ts** at all.
**How**:
-
-
**Checklist**:
> Remove TS definition from checklist

- package.json
- src/components/CookiesBanner/index.tsx
- src/logic/cookies/utils/index.ts
- src/utils/googleAnalytics.ts
- yarn.lock
Closes #1930.
Some GA reports were being sent even so the user has disabled them in preferences. 
I wrapper `trackPage` method of `useAnalytics` hook to be recalculated when `analyticsAllowed` changes
> Fix GA problem after disabling cookies.

- src/components/forms/AddressInput/index.tsx
- src/components/forms/validator.test.ts
- src/components/forms/validator.ts
Closes #1928.
When users enter all-lower case address, we checksum them automatically. That's nice. But it's not safe.
This PR removes the auto-checksum address and modifies the error message. I removed the word `Ethreum` for two reasons, it a hardcoded blockchain and also because the message was too long and wasn't fitting in the input.
> Fix: remove auto checksum address from InputAddress

- src/routes/safe/components/Apps/components/AppFrame.tsx
**What**:
- Add `chainId` property to getSafeInfo response in safe apps communicator.
- Closes #2287 
**Why**:
To avoid using hardcoded network names in sdks and let consumers take care of naming.
**How**:
- Uses chainId from config
- use any safe app, look for the response in the console. It logs every incoming message
**Checklist**:
> Add chain id to getSafeInfo response

- src/routes/safe/components/Settings/SpendingLimit/FormFields/ResetTime.tsx
- src/routes/safe/components/Settings/SpendingLimit/NewLimitModal/Review.tsx
- src/routes/safe/components/Settings/SpendingLimit/RemoveLimitModal.tsx
- src/routes/safe/components/Transactions/TxList/SpendingLimitDetails.tsx
**What**:
We are lowering the reset times for spending limits module in Rinkeby so it's easier to test.
When we first implemented this we weren't thinking of allowing reset times lower than 1 day. There are also changes to allow specifying lower resetTimes down to a minute (as the smart contract allows) so it's easier to implement this change for Rinkeby
**Why**:
Currently it takes long to test spending limits in web. We want to change the values that can be set on spending limits.
Just check on spending limits. The default spending limits should be keep for any other network
**Checklist**:
> Set lower reset time functions for Rinkeby

- src/logic/safe/utils/spendingLimits.ts
- src/logic/safe/utils/upgradeSafe.test.ts
- src/logic/safe/utils/upgradeSafe.ts
- src/routes/safe/components/Settings/SpendingLimit/LimitsTable/dataFetcher.ts
- src/routes/safe/components/Settings/SpendingLimit/NewLimitModal/Review.tsx
**What**:
This PR is an integration branch for changes of the following PRs:
#2262
#2295
#2299 
Following issues can be tested on this PR
Fixes #1700 #1698 #1896 #2298
**Why**:
In order to make full regression easier for QA without taking changes to `development` yet
Changes from #2262
1. Allow an owner 1 of a token (ETH for example)
2. With the owner use the 0.5 ETH
3. Edit the Spending limit, from 1ETH to 0.25 ETH
4. You should see the new spending limit with the spent on 0
Changes from #2299
1. create a new safe
2. add a new spending limit
3. it shows the tx with 3 actions (`enableModule`, `addDelegate`, and `seAllowance`)
**Checklist**:
> [Spending Limit] Integration PR

- src/routes/load/components/DetailsForm/index.tsx
Closes issue #2321 problems validating that an address is a safe when adding a new safe
When we send an address that is nota Safe we get an error from the `client-gateway`. We are not catching this error so the validation script is broken and no error message is shown.
We catch the error and we show an error message in the form
Try to add an invalid address in add safe form.
Check that the correct error is shown
> 2321 - Catch backend error and send controlled form error

- src/logic/safe/store/actions/fetchSafe.ts
- src/logic/safe/store/models/safe.ts
- src/logic/safe/store/selectors/index.ts
- src/logic/safe/utils/__tests__/shouldSafeStoreBeUpdated.test.ts
- src/routes/safe/components/Settings/SafeDetails/index.tsx
- src/routes/safe/components/Settings/index.tsx
The "Safe added via URL" behavior
By re-adding the `loadedViaUrl` flag to the Safe object, but changing a bit the approach on how to use it.
Previously it was based on the `safe.name` value (if it was "Gnosis Safe", then it was considered as added via URL). Now, `safe.name` has been removed, so we no longer have that field to do the verification.
The current solution assumes all safes as being loaded via URL except for those added via Load/Open forms or when a Safe's name is being updated via Settings.
Check that all the "safe loaded via URL" functionality work as expected.
it's using the PR #2336 as base branch
> add back `loadedViaUrl` flag

- src/logic/exceptions/CodedException.test.ts
- src/logic/exceptions/CodedException.ts
- src/logic/exceptions/registry.ts
- src/logic/tokens/store/actions/fetchSafeTokens.ts
- src/logic/tokens/store/actions/fetchTokens.ts
In https://github.com/gnosis/safe-react/pull/2316 I and @katspaugh started a discussion on how to handle exceptions when using safe apps. The tricky thing about safe apps that in the essence there are two errors: one is about the safe app and one about some of the underlying functions we have in our codebase plus we need additional data to have enough context for debugging: app name, URL, what method it was trying to call, arguments, etc. The only possible way to do that with the current `CodedException` is to fit everything into an error message which is not ideal. Luckily, sentry supports enriching error events with additional context: https://docs.sentry.io/platforms/javascript/enriching-events/context/
Allows passing additional context to the `CodedException` class. 
It adds a test …
> Feature: Allow passing additional context to CodedException

- src/routes/safe/components/Apps/communicator.ts
- src/routes/safe/components/Apps/utils.ts
Sentry error logging for failing safe app loading and a failed attempt to fetch a safe balance from the sdk
It makes use of additional error contexts introduced in https://github.com/gnosis/safe-react/pull/2334. The initial solution makes use of a generic safe app request error code (_901). If it doesn't work out, we may introduce an error code for each request method.
There are two errors added:
* `900: Error loading Safe App`
* `901: Error processing Safe Apps SDK request`
They will be both logged to the console.
To reproduce:
1. Safe app loading - Using chrome dev tools turn off the internet after opening the safe apps tab
2. The 901 error will be logged when an app tries to call an SDK method but it fails.
E.g. the error when fetching safe balances. Via safe apps SDK attempt to fetch …
> Feature: Better error handling for Safe apps things

- src/routes/safe/components/AddressBook/EllipsisTransactionDetails/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/Review/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/ReviewCollectible/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/SendCollectible/index.tsx
- src/routes/safe/components/Settings/SpendingLimit/InfoDisplay/AddressInfo.tsx
- src/routes/safe/components/Transactions/TxList/OwnerRow.tsx
- src/routes/safe/components/Transactions/TxList/TxInfoDetails.tsx
- src/routes/safe/components/Transactions/TxList/hooks/useKnownAddress.ts
Closes #1603 to ensure the use of values stored in the address book over the ones from backend for known addresses
In this PR we check those places where we use Known Addresses to have higher priority showing Address book information over information from backend
Go through the app checking that we use correct names when stored in address book. Always assume highest priority for the name stored in address book. When name is not stored in the address book, if the address is a `knownAddress`we should display the values from backend
There were just few changes and long revision. Detected some places where even the name weren't used (SendCollectibles review and Contract Interaction review). In general it's also fixing some hardcoded values that I found
In Rinkeby Compound app uses a "known …
> [Address Book v2] 1603 Use addressbook over known addresses

- src/components/forms/validator.ts
- src/logic/addressBook/store/reducer/index.ts
- src/routes/load/container/Load.tsx
- src/routes/open/container/Open.tsx
- src/routes/safe/components/AddressBook/ImportEntryModal/index.tsx
- src/routes/safe/components/AddressBook/index.tsx
- src/routes/safe/components/Settings/ManageOwners/EditOwnerModal/index.tsx
- src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/index.tsx
- src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/screens/CheckOwner/index.tsx
- src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/screens/Review/index.tsx
- src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/index.tsx
- src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/OwnerForm/index.tsx
- src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/Review/index.tsx
- src/routes/safe/components/Settings/ManageOwners/dataFetcher.ts
- src/routes/safe/components/Settings/ManageOwners/index.tsx
- src/utils/__tests__/checksumAddress.test.ts
- src/utils/__tests__/isValidAddress.test.ts
- src/utils/checksumAddress.ts
- src/utils/isValidAddress.ts
Removes the usage of `checksumAddress` inside addressBook reducers (https://github.com/gnosis/safe-react/pull/2296#discussion_r636134963 and https://github.com/gnosis/safe-react/pull/2296#discussion_r636135680)
I added a couple of functions. `isValidAddress` and `isChecksumAddress`.
- `isValidAddress` is used to prevent calling `checksumAddress` with an invalid data (thus, prevents unhandled errors).
- reviewed all the dispatch calls for all the addressBook/actions and ensured that the `address` provided was checksummed.
All the addresses stored in the addressBook store must be _checksummed_
There's a better solution proposed by @katspaugh where we can type the data returned by `checksumAddress`. 
But doing so required a huge amount of work/refactor that will surely delay the release of …
> [AddressBook v2] - Avoid using `checksumAddress` inside reducer

- src/routes/safe/components/AddressBook/ExportEntriesModal/index.tsx
- src/routes/safe/components/AddressBook/HelpInfo/index.tsx
- src/routes/safe/components/AddressBook/ImportEntryModal/index.tsx
See [this comment](https://github.com/gnosis/safe-react/pull/2280#issuecomment-852904740) from @tschubotz 
Adds a new component `HelpInfo` that is used in both import and export modals.
Click on the link
Make sure it opens the right help article
> Use the same link in the import and export modals

- src/routes/safe/components/Settings/RemoveSafeModal/index.tsx
- src/routes/safe/components/Settings/SafeDetails/index.tsx
fixes #2353
Stop from dispatching `addressBook/remove` action when deleting a Safe
Follow steps in issue #2353
> [Address Book v2] - Avoid deleting addressBook entry when deleting a safe

- src/components/CookiesBanner/index.tsx
- src/logic/hooks/useGetSafeAppUrl.tsx
- src/logic/hooks/useSafeAppUrl.tsx
- src/routes/safe/components/Apps/index.tsx
Closes #2238 
Checks if the current view is the safe app view and hides the intercom
Enter any safe app view and check if intercom is hidden in the bottom right side
> Fix: don't display Intercom in Safe Apps

- src/components/forms/validator.ts
- src/routes/load/components/DetailsForm/index.tsx
- src/routes/load/components/Layout.tsx
- src/routes/load/components/OwnerList/index.tsx
- src/routes/load/components/ReviewInformation/index.tsx
- src/routes/load/container/Load.tsx
Closes #2366 Allowing empty names for owners when loading a safe
This PR removes the requirement of adding all the owner names when loading a Safe. Owners are no longer displayed using Owner #X naming.
Load a safe and check that if the name is added it's stored in the address book, or that you leave the names empty nothing is stored in the address book.
> [Address Book v2] Allow empty owner names when loading a safe

- src/logic/safe/store/middleware/safeStorage.ts
- src/logic/safe/store/selectors/index.ts
- src/routes/open/container/Open.tsx
Fixes #2386
By stop filtering out those safes without name from being listed, and by storing safes without `name` leaving outside only those whose `loadedViaUrl` flag is set to `true`
Follow steps specified in the issue
> keep safes with no name for the list of safes

- package.json
- src/components/AppLayout/Header/components/ProviderDetails/UserDetails.tsx
- src/logic/safe/store/actions/fetchTransactionDetails.ts
- src/logic/safe/transactions/api/fetchSafeTransaction.ts
- src/routes/safe/components/Apps/communicator.ts
- src/routes/safe/components/Apps/components/AppFrame.tsx
- src/utils/css.ts
- yarn.lock
Relaying transaction details API call from the SDK, some type enhancements needed for https://github.com/gnosis/safe-apps-sdk/issues/104
Adds a handler for the new message method `getTxBySafeTxHash` and a new API function 
1. Use https://github.com/gnosis/safe-test-app
2. Paste some transaction hash to the input
3. Click "Get Transaction by safe tx hash"
4. You should see the response with the transaction in the console
> Feature: Relay safe apps sdk getBySafeTxHash api request

- src/routes/safe/components/AddressBook/index.tsx
Close #2378 where order was by adding date. Instead we will set default order by name.
Just setting the defaultOrderBy to use the name column
Add a bunch of entries to the address book. Avoid using alphabetic order when introducing them
Check that whenever you open the address book entries are listed by name ascending
> [Address Book v2] Set default order by name

- src/components/Table/index.tsx
- src/components/Table/sorting.ts
- src/components/Table/types.d.ts
- src/routes/safe/components/Settings/ManageOwners/dataFetcher.ts
This PR fixes #459 
We extended the sorting functionality in order to allow custom sorting methods for each column of the table.
1. Open/Load a safe with owners
2. Go to Settings 
3. Go to Owners tab
4. Sort Name column by clicking on the column name
> Bugfix - Owners table sorting is not working correctly

- package.json
- yarn.lock
Closes https://github.com/gnosis/safe-react/issues/2377
It seemed that the @truffle/contract package was trying to do something synchronously and blocked the main thread. See the attached screenshot.
There even is an error message in the console:
> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience
I did some profiling and found out the @truffle/contract package. The first thing I tried is to update the version to a newer one and it seemed to fix the issue.
1. Check the original ticket for a video with the bug
2. Try to reproduce it on https://safe-team.dev.gnosisdev.com/
3. Now try to reproduce it on the PR deployment
4. Make sure the error is not there
> Bug: App freezes on initial load if you switch to Assets tab

- package.json
- src/logic/addressBook/utils/v2-migration.ts
- src/logic/safe/store/models/safe.ts
If you had safes loaded via URL in your localStorage, it would kill all the safes resulting in an empty object in the storage.
> 🔥 Fix disappearing safes after migration

- src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/screens/ThresholdForm/index.tsx
Closes #1649
When removing an owner and threshold==num_owners then preselect old threshold - 1
When removing an owner and threshold<num_owners then preselect the ol threshold
Add 3 owners with threshold 2
Remove an owner
It should set the default threshold to 2
> Dont lower threshold if owner amount is the same as current threshold

- src/components/forms/AddressInput/index.tsx
- src/logic/addressBook/utils/v2-migration.ts
- src/logic/exceptions/CodedException.test.ts
- src/logic/exceptions/CodedException.ts
- src/logic/exceptions/registry.ts
- src/logic/tokens/store/actions/fetchSafeTokens.ts
- src/logic/tokens/store/actions/fetchTokens.ts
- src/routes/load/components/ReviewInformation/index.tsx
- src/routes/safe/components/Apps/communicator.ts
- src/routes/safe/components/Balances/SendModal/screens/AddressBookInput/index.tsx
Resolves #1728.
Resolver errors weren't caught.
It wasn't throwing on every keypress like the linked issue says (this has been apparently already fixed), but it was still throwing.
Catches the errors and logs them.
I've added a new function `trackError` to complement `logError`. We don't have to pass `undefined, false` anymore.
Two test cases:
* create an owner
* send funds
In both cases, enter `brad.crypto` in the address field and observe a 101 error in the console.
> Catch ENS/unstoppable errors; split logError and trackError

- src/routes/load/components/OwnerList/index.tsx
Fixes #2419 
By removing an invalid entry in the `useEffect` hook dependency array
Follow steps in the associated issue.
> (Fix) - App crashes on Safe Load

- src/routes/safe/components/Balances/SendModal/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/ReviewCustomTx/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/SendCustomTx/index.tsx
fixes #2384
By following the same strategy as in `SendFunds` modal. That is, lookup the name in AB, then pass it as param between screens.
Follow steps in the issue.
> (Fix) Preserve contract name in custom contract interaction flow

- src/routes/safe/components/Balances/utils/setTokenImgToPlaceholder.ts
Fixes #2423.
Checks if the fallback image is already set.
1. Load the assets
2. Switch off the network just before the tokens appear on the screen
3. Check the console, it shouldn't load the fallback image infinitely anymore
> Fix infinite placeholder loop

- src/routes/safe/components/CurrencyDropdown/index.tsx
Fixes #941.
Imports the currency flags on menu open.
* Open the Network in devtools
* Click on the currency menu
* Observe the JS chunk and icons loading
* The menu itself should work like before
> Load currency flags on menu open

- src/logic/safe/store/actions/transactions/fetchTransactions/index.ts
Fixes #2434
Updates the store when queued tx list comes empty from the backend
Create a safe(preferably use 2 owners with threshold 2 because with 1 owner the queued tx might not even appear(
Create a tx (send funds for example)
Wait for it to be confirmed
Tx should be erased from the queue list and added to the history list
> Erase queued transactions if confirmed

- src/components/App/index.tsx
https://github.com/gnosis/safe-react/pull/2410#issuecomment-859195755
By using the safe address from the URL, if `safeAddress` is not available in the store.
Paste any Safe link that is not stored in the session. Try with: https://pr2439--safereact.review.gnosisdev.com/rinkeby/app/#/safes/0x9913B9180C20C6b0F21B6480c84422F6ebc4B808/balances
> [Address Book v2] - [Fix] - Safe loaded via URL is not working

- src/logic/safe/store/actions/utils.ts
- src/logic/safe/utils/safeInformation.ts
Fixes #2440.
Falls back to an empty array if modules are null.
This was the only place I could find. The module list component was already checking for null.
* Create a new safe
* Go to settings > modules
* Everything should work as before
> Modules can be null

- src/logic/exceptions/registry.ts
- src/logic/safe/store/actions/createTransaction.ts
- src/logic/safe/store/actions/processTransaction.ts
- src/routes/safe/components/Balances/SendModal/screens/ReviewSendFundsTx/index.tsx
Fixes #2432.
Catches the "Signatures data too short" error, plus a few others.
* Set policy to > 1
* Create a tx and set the nonce to a lower number (of an existing tx)
* Check the console
Plus added this extra messages for spending limit tx errors:
> Catch tx errors

- .github/workflows/cla.yml
- .github/workflows/deploy-ewc.yml
- .github/workflows/deploy-mainnet.yml
- .github/workflows/deploy-rinkeby.yml
- .github/workflows/deploy-volta.yml
- .github/workflows/deploy-xdai.yml
- .github/workflows/release-mainnet-desktop.yml
- .github/workflows/test.yml
- README.md
- docs/release-procedure.md
- scripts/github/deploy_pull_request.sh
- scripts/github/prepare_production_deployment.sh
* Replaced the branch names in deployment scripts
* Updated the docs
As per the discussion with @francovenica, I've also disabled the automatic mainnet deployment on each PR.
@francovenica almost never uses it. He'd like to keep the option to explicitly deploy on mainnet, though.
The deployment to mainnet will happen only on PRs created against the main branch now.
> Rename development -> dev, master -> main

- src/components/ButtonHelper/index.tsx
- src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/screens/Review/index.tsx
- src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/screens/Review/index.tsx
- src/routes/safe/components/Settings/ManageOwners/index.tsx
Fixes https://github.com/gnosis/safe-react-e2e-tests/issues/8
Adds the data test ids needed to fix the add-remove-owner e2e tests
Use this PR to run the add-remove-owner e2e test
> Added data test ids needed to fix add remove owner e2e test

- src/routes/load/components/DetailsForm/index.tsx
Resolves #2450.
Adds a paragraph with a help link.
- Go to Add existing safe
- Click on the help link
> Add a help link in Load Safe

- src/routes/safe/components/Balances/SendModal/screens/SendCollectible/TokenSelectField/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/SendCollectible/TokenSelectField/style.ts
- src/routes/safe/components/Balances/SendModal/screens/SendFunds/TokenSelectField/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/SendFunds/TokenSelectField/style.ts
Fixes #2267.
Adds a class name to the img.
- Send funds
- Open the token menu
> Add a margin for token icons

- src/logic/contracts/safeContracts.ts
Fallback to latest smart contract default address if network is not found. This way we can still use networks that are deployed but not added to safe-deployments when smart contract addresses match with the default ones
Just fallback to the latest default version without filtering by network
> Fallback to latest default contract if network not found

- src/routes/safe/components/Settings/SpendingLimit/LimitsTable/index.tsx
- src/routes/safe/components/Settings/SpendingLimit/style.ts
Closes #2459
Increasing the min-height of the table, the pagination isn't overlapped by a line.
> (Bugfix)Spending Limit UI

- docs/networks.md
- src/config/networks/energy_web_chain.ts
- src/config/networks/local.ts
- src/config/networks/mainnet.ts
- src/config/networks/network.d.ts
- src/config/networks/rinkeby.ts
- src/config/networks/volta.ts
- src/logic/wallets/ethTransactions.ts
Some gas price oracles are not using the most standard way to return the gas price (gwei), for example eth gas station is returning "gwei x 10"
We set `gweiFactor` as a config parameter in order to know the required unit to get the gas price value in `wei`
This is necessary to add compatibility to the gas provider from BSC that is setting the units in gwei and there for we are getting 10x lower gas price values.
To test in this PR just check that gas values still fit to mainnet ones. Once merged to BSC PR check that value for BSC is not returned as low gas price value
> [L2] Add gweiFactor to gas price oracle

- package.json
- patches/ethereum-cryptography++secp256k1+4.0.2.patch
- yarn.lock
Wrong patch for secp256k1 dependency. The patch introduced in https://github.com/gnosis/safe-react/pull/2472 was wrong because it removed the assert statement
By bringing assert statement back.
Tests should cover it. You can do a few transactions tho
> Fix secp256k1 patch

- src/logic/addressBook/utils/index.ts
- src/logic/addressBook/utils/v2-migration.ts
Resolves a customer support report.
> I'm trying to interact with a contract that had ownership transferred to a gnosis multisig safe. When going to new transaction -> contract interaction -> paste contract address, I get this error. Is this a known issue and if so, does it affect mainnet or only testnet?
> This is the contract address: 0xee589ec00c4320f24fcb2a49d1d5f8f256fbb0f5
This is the console output on chrome
I don't know the root cause of the bug but it seems that some Address Book entries are created without a name property.
The Autocomplete code assumes there's aways a name and it's a string. I've added a fallback for it.
Update: the root cause might be that [we aren't checking if name exists](https://github.com/gnosis/safe-react/pull/2484/files#diff-3be536ee86eb7568410fb632994c25 …
> 🔥 Fix "Cannot read property'toLowerCase' of undefined" in autocomplete

- src/components/AppLayout/Header/components/ProviderDetails/UserDetails.tsx
- src/components/AppLayout/Header/index.tsx
- src/logic/wallets/__tests__/network.test.ts
- src/logic/wallets/utils/network.ts
An addendum to #2477. Resolves the [defect](https://github.com/gnosis/safe-react/pull/2477#issuecomment-868475392) found by @liliya-soroka.
When the wallet isn't MetaMask (and it's the only wallet we know to support chain switching), don't show the Switch Network button.
Checks if the wallet is MetaMask.
Connect with some other wallet, the button shouldn't be there.
> Hide switch button when not MetaMask

- src/routes/opening/utils/getSafeAddressFromLogs.ts
Resolves #2493 
`abi-decoder` package returns a lowercase address and it's used in the address-book entry: https://github.com/ConsenSys/abi-decoder/blob/a9ed4923433ad32069e2ea963d683ed2ff49fa07/index.js#L111.
By checksumming address returned from abi-decoder
Create a safe on this branch, it should have a name displayed right after creation
> Bug: No safe name displayed after creation

- src/routes/safe/components/Apps/components/AppCard/index.tsx
Resolves #2478
By adding an ellipsis to the description. We show 3 lines (max) and add a ellipsis at the end.
1. Go to the admin panel -> safe apps
2. add a new app with a very long description
> Text ellipsis for sApp description

- src/components/Collapse/index.tsx
- src/components/SafeListSidebar/SafeList/UnsavedAddress.tsx
- src/components/SafeListSidebar/SafeList/index.tsx
- src/components/SafeListSidebar/index.tsx
- src/logic/addressBook/store/selectors/index.ts
- src/logic/exceptions/registry.ts
- src/logic/safe/api/fetchSafesByOwner.ts
- src/logic/safe/hooks/useOwnerSafes.ts
- src/routes/index.tsx
- src/routes/load/components/DetailsForm/index.tsx
- src/routes/load/container/Load.tsx
When testing the safe interface, oftentimes you clear the localStorage and lose all your safes.
Related to #510.
Your safes can be still retrieved via an endpoint, so I've made a little custom hook that fetches safes by their owner.
Connect your wallet and see your unsaved safes in the sidebar. Should not be visible on production.
> Display the list of owned safes

- package.json
- src/logic/exceptions/registry.ts
- src/logic/safe/transactions/__tests__/txMonitor.test.ts
- src/logic/safe/transactions/txMonitor.ts
- src/routes/open/container/Open.tsx
- yarn.lock
Refactor `txMonitor` from #2362.
I tried to break down the code a bit, and converted the callback to a promise.
Also caught potential rejections.
The same as #2362 itself.
> Refactor tx monitor

- src/config/networks/bsc.ts
- src/config/networks/energy_web_chain.ts
- src/config/networks/mainnet.ts
- src/config/networks/polygon.ts
- src/config/networks/rinkeby.ts
- src/config/networks/volta.ts
- src/config/networks/xdai.ts
Resolves #2497.
Adds staging and dev URLs in the network configs.
Open the network menu and click on a link, then go back. Repeat for each of the links.
> Use staging and dev links in the network menu

- src/routes/safe/components/AddressBook/ExportEntriesModal/index.tsx
- src/routes/safe/components/AddressBook/ImportEntriesModal/index.tsx
- src/routes/safe/components/AddressBook/utils.ts
Resolves #2464.
Checks if chain id exists in the list of supported chains.
I've also fixed the Download button in the export modal. The clickable area wasn't covering the whole button.
Export the AB on the Arbitrum branch, try to import on this PR's branch. It will not recognize Arbitrum because it's not merged yet.
> Address book: validate chain id; fix download button

- src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/Review/index.tsx
Resolves e2e tests #15
This PR adds 2 test ids already used in other modals
This PR is used to test #15
> Adding data test ids for owner replacement modal

- src/components/AppLayout/Sidebar/useSidebarItems.tsx
- src/components/SafeListSidebar/SafeList/UnsavedAddress.tsx
- src/components/SafeListSidebar/SafeList/index.tsx
- src/logic/safe/store/actions/createTransaction.ts
- src/logic/safe/store/middleware/notificationsMiddleware.ts
- src/routes/index.tsx
- src/routes/load/container/Load.tsx
- src/routes/open/container/Open.tsx
- src/routes/routes.ts
- src/routes/safe/components/AddressBook/EllipsisTransactionDetails/index.tsx
- src/routes/safe/components/Apps/components/AddAppForm/index.tsx
- src/routes/safe/components/Apps/components/AppFrame.tsx
- src/routes/safe/components/Apps/components/AppsList.tsx
- src/routes/safe/components/Balances/index.tsx
- src/routes/safe/components/Settings/index.tsx
- src/routes/safe/container/index.tsx
Resolves #2525 
This PR will set all routes to be created programmatically from an enum that we can handle in `routes` file
This is mostly a code semantic improvement. As bugs can happen this can be tested as minimum, just playing a bit around navigating through the app and seeing the expected behavior. No deep check should be necessary, when merging to dev, we will test this in any other PRs
> Add centralized routing source

- src/components/forms/AddressInput/index.tsx
- src/routes/open/components/SafeOwnersConfirmationsForm/index.tsx
Browser was underlining the input text with a red wavy line. But an address isn't supposed to be spell-checked.
Browser: Chrome
Disabled HTML spellcheck for safe address input element.
Unfixed:
Fixed:
> Disable spellchecker in eth address field - re #2257

- src/config/__tests__/config.test.ts
- src/config/index.ts
- src/config/networks/bsc.ts
- src/config/networks/energy_web_chain.ts
- src/config/networks/local.ts
- src/config/networks/mainnet.ts
- src/config/networks/network.d.ts
- src/config/networks/polygon.ts
- src/config/networks/rinkeby.ts
- src/config/networks/volta.ts
- src/config/networks/xdai.ts
Remove unused configuration options: safe apps URL, safe relay service URL
Literally removes them and also fixes tests
Everything should work just fine as it used to
> Chore: remove unused options from the configs

- src/components/Stepper/index.tsx
Resolves #2515 
Safe name doesn't get reset if mm account is changed
- Select to create new safe
- Set a name and next step
- Change mm account
- Complete safe creation
> Dont reset variables that dont need update

- README.md
Recently Gnosis Safe added support for Binance Smart Chain and Polygon.
The readme did not have those listed yet, this pull request fixes that.
By adding both Polygon and Binance Smart Chain to the list.
> Adds Binance Smart Chain and Polygon to list

- src/routes/safe/components/AddressBook/__tests__/utils.test.ts
- src/routes/safe/components/AddressBook/utils.ts
Resolves #2578
It allows file type not to be defined but also includes a file extension validation in order to still do a minimum check that a valid file is being uploaded
It can only be tested using **Chrome** in **Windows 10**
If an office suite is installed it may be possible that the issue is not repeatable anymore. I can just confirm that it's possible with a clean Windows 10 or with LibreOffice installed
> Fix import in Windows 10 + Chrome

- src/routes/load/components/DetailsForm/index.tsx
Resolves #2539
Initializes the safeName variable with undefined so the required check is not made
-Open Add existing safe
The required error should be ther
> Don't show required error when loading a safe

- src/routes/safe/components/Apps/hooks/useAppList.ts
- src/routes/safe/components/Apps/utils.ts
- Resolves #2408 
- Adjusts origin string length to be in par with tx service https://github.com/gnosis/safe-transaction-service/blob/master/safe_transaction_service/history/models.py#L861
- Catches previously uncaught error in legacy app info fetch logic
It solves #2408 by creating an image element and setting src attribute to the image URL, this way the requested resource is not affected by cors
- Images, custom apps additions should work
- App transactions should work
> Feature: enhanced safe app info fetching logic

- .github/workflows/comment-on-e2e-success.yml
https://github.com/gnosis/safe-react-e2e-tests/pull/45 added test results in the payload, so that we can see what exactly failed if the tests fail.
> Add e2e test results in the comment

- src/config/networks/bsc.ts
- src/config/networks/energy_web_chain.ts
- src/config/networks/local.ts
- src/config/networks/mainnet.ts
- src/config/networks/network.d.ts
- src/config/networks/polygon.ts
- src/config/networks/rinkeby.ts
- src/config/networks/volta.ts
- src/config/networks/xdai.ts
- src/logic/contracts/safeContracts.ts
We were using L2 contract instance for all networks, but I was warned by @rmeissner  that on mainnet gas costs were much higher using this contract instance. So we are going to set explicitly L1 or L2 in config selecting the required smart contract for each case
It adds a config parameter setting which layer version is a network using
Should create L1 smart contract instances on rinkeby and mainnet. It can check which master copy is using to create smart contract
For upgrade step I can provide v1.1.1 or v1.0.0 safes if QA is not having more of them. They should check that also L1 master copy is used to upgrade in mainnet or rinkeby
> Use explicit config to set L1 or L2 smart contract

- src/index.tsx
Resolves #2600.
Also increases the Sentry sample rate 10 times (from every 100th error to every 10th).
MM (and probably other wallet extensions) throw uncaught exceptions from their content script.
We cannot catch them in our code (apart from `window.onerror`), although we do catch the corresponding errors from web3. So there's no point logging these to Sentry.
No need to test, these errors are very random. We'll see if they stop appearing on Sentry.
> Sentry: ignore wallet errors; set sample rate to 0.1

- README.md
Update the readme according to the recent Gateway SDK changes.
New diagram:
> Update the app diagram in the readme

- .dockerignore
- .github/workflows/cla.yml
- Dockerfile
- README.md
- docker-compose.yml
- package.json
The current listed version of electron (`9.0.0`) does not support the M1 chip (`darwin-arm64`).
There is another PR open to fix this: https://github.com/gnosis/safe-react/pull/2149
As an alternative, you can use docker to run the safe-react in a container.
[Install Docker](https://docs.docker.com/get-docker/) and  run `yarn start:docker`
> Dockerize safe react project

- src/components/DecodeTxs/__tests__/index.ts
- src/components/DecodeTxs/index.tsx
Resolves #2556 and #2613
Supports a joined list of hex strings. Swallows possible errors for any incompatible type.
* Open the Tx Builder app
* Use the test contract provided by Liliya in #2556
* Enter `["0x000000ea", "0x48656c6c6f2125"]` in the param value
* Send, review and decode
> Fix byte32[] decoding

- src/components/App/ReceiveModal.tsx
- src/components/App/index.tsx
Resolves #2593
Removes the safe name check when showing the QR code.
Open a safe w/o a name and click on the QR code button.
> Fix: show QR code even if no safe name

- package.json
- yarn.lock
Fixes a lot of console errors on dev in the notistack package: https://github.com/gnosis/notistack
- Mainly by stopping passing props to a component that don't need/want it
- Use `root` instead of `container` material UI object for classnames
> Fix material ui errors on dev

- package.json
- src/logic/contracts/safeContracts.ts
Resolves #
Issue with xDai, EWC and Volta that used L1 smart contracts while they are L2 networks and should be using those.
Check to use L1 or L2 instance is not taking into account that before version v1.3.0 there wasn't a L2 instance of the Safe smart contract. Just add a check to allow use L2 smart contract when we try to use on a L2 network and smart contract is >=1.3.0
> Hotfix v3.12.1

- src/components/SafeListSidebar/SafeList/OwnedAddress.tsx
- src/components/SafeListSidebar/SafeList/index.tsx
- src/components/SafeListSidebar/index.tsx
- src/logic/safe/hooks/useOwnerSafes.ts
@koeppelmann suggested that it would be useful to display _all_ owned safes, even the ones that you already added.
Removes the filtering by added, renames some vars/modules to reflect the new semantics.
Open the sidebar and expand the `All owned Safes` list.
> Display all owned safes incl. added safes

- src/components/TransactionFailText/index.tsx
- src/components/TransactionsFees/index.tsx
- src/routes/safe/components/Apps/components/AppFrame.tsx
- src/routes/safe/components/Apps/components/ConfirmTxModal/ReviewConfirm.tsx
- src/routes/safe/container/index.tsx
Resolves #2674
Removes the owner check from the App frame.
Also fixes the redirect to balances on the app URLs (`enabledFeatures` wasn't initialized on time).
* Open a safe as a non-owner
* View a Safe App
* Try to reload the page (it should stay in the app)
* Try creating a transaction (e.g. via the TX Builder or Drain Safe)
* The Submit button should be disabled
> Enable apps for non-owners; fix app URL redirect

- src/components/AppLayout/Sidebar/useSidebarItems.tsx
- src/routes/safe/container/index.tsx
Resolves #2665 
The useSidebarItems hook and Container component were calling the generatePath hook with an empty address. We are now preventing the app from doing that.
> Dont use generatePath for safe routes if there`s no safeAddress

- src/logic/addressBook/store/selectors/index.ts
- src/logic/addressBook/utils/v2-migration.ts
Resolves an issue where address book entries are not shown after changing chainId from number to string, because we have a strict comparison so string is not matching with number even they are the same value.
Consider that chainId value from address book has to always be casted to a string
Open the app in an environment where there is already an address book
You could load mixed values
You can store the following example in local storage and check that all values are still shown
```
[
{"address":"0x2b98ED26228aAaDf030BCA6184827490dE642c8f","name":"grateful-safe","chainId":4},{"address":"0x61a0c717d18232711bC788F19C9Cd56a43cc8872","name":"test1","chainId":"4"},{"address":"0xeB37f9Dc51FB74E8992A50cD23795fBA53e74a6A","name":"delighted-safe","chainId":4},{"address":"0x834C5e06f98cB129d142f0D99 …
```
> [Hotfix v3.13.1] Create basic migration for addressbook chain id

- src/components/App/index.tsx
- src/logic/addressBook/hooks/useAddressBookSync.ts
- src/logic/addressBook/store/actions/index.ts
- src/logic/addressBook/store/reducer/index.ts
Resolves #2646
Subscribes to the `storage` event and updates the Redux store on each localStorage write done outside of the current tab.
* Open two Safe tabs on the same URL
* Modify the address book in one of the tab (change the safe or one of the owners' name)
* The change should be immediately reflected in the other tab
> Fix address book sync across multiple tabs

- src/components/CookiesBanner/index.tsx
- src/logic/cookies/model/cookie.ts
- src/logic/cookies/utils/index.ts
- src/utils/intercom.ts
Resolves #2565 
It adds the property `user_id` to the method that initializes Intercom: `Intercom('boot', { ... }`.
The property `consent` was removed as it is not present in the documentation.
The value of `user_id` is randomly generated and stored in the cookie `v1_<NETWORK>__COOKIES_INTERCOM` if the cookie does not exist. If the cookie already exists, the `user_id` is obtained from that cookie. The cookie lasts a year and a new cookie with a new `user_id` will be automatically created after that period of time. This cookie is created as long as the "Customer Support" option is selected in the cookie preferences.
Using `user_id` property on Intercom allows to identify the current user with that id and users are not asked for their email. Using a different `user_id` will match with a …
> Handle Intercom security issue

- src/routes/load/Load.test.tsx
- src/setupTests.js
Removed act warnings in the unit tests console
> Removed act warnings in the unit tests console

- src/logic/wallets/__tests__/getWeb3.test.ts
- src/logic/wallets/getWeb3.ts
- src/types/definitions.d.ts
Resolves #2675
`web3Provider.eth.getCode` does checksum validation internally and can throw if the address is invalid. So I wrapped it in a try-catch.
The particular edge case when it throws is very hard to reproduce, so let's just verify that the wallet connection still works like before. Especially with WalletConnect and a Safe as a wallet.
> Fix: wrap web3Provider.eth.getCode in a try-catch

- src/routes/safe/components/Apps/components/SignMessageModal/ReviewMessage.tsx
After https://github.com/gnosis/safe-react/pull/2701 got merged, the dev branch didn't compile because the types were incompatible there.
- Make gas, etc. use string in ReviewMessage
I tested the signing flow with the safe-test-app, set manual gas, everything worked fine
> Use string for gas in ReviewMessage component

- package.json
- src/logic/safe/api/fetchSafeTxGasEstimation.ts
- src/logic/safe/api/fetchSafesByOwner.ts
- src/routes/safe/components/Apps/components/ConfirmTxModal/ReviewConfirm.tsx
- src/routes/safe/components/Apps/components/SignMessageModal/ReviewMessage.tsx
- src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/Review/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/ReviewCustomTx/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/ReviewCollectible/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/ReviewSendFundsTx/index.tsx
- src/routes/safe/components/Settings/Advanced/RemoveGuardModal.tsx
- src/routes/safe/components/Settings/Advanced/RemoveModuleModal.tsx
- src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/index.tsx
- src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/screens/Review/index.tsx
- src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/index.tsx
- src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/screens/Review/index.tsx
- src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/index.tsx
- src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/Review/index.tsx
- src/routes/safe/components/Settings/SpendingLimit/NewLimitModal/Review.tsx
- src/routes/safe/components/Settings/SpendingLimit/RemoveLimitModal.tsx
- src/routes/safe/components/Settings/ThresholdSettings/ChangeThreshold/index.tsx
- src/routes/safe/components/Settings/UpdateSafeModal/index.tsx
- src/routes/safe/components/Transactions/TxList/modals/ApproveTxModal.tsx
- src/routes/safe/components/Transactions/TxList/modals/RejectTxModal.tsx
- yarn.lock
Resolves https://github.com/gnosis/safe-react-gateway-sdk/issues/14
Uses new function in the gateway SDK in order to estimate safeTxGas
It also uses the function to fetch owned safes through the client gateway instead transaction service
- Check that safeTxGas estimations are still correct
- Check that owned safes are shown in sidebar correctly
> Add gas estimation endpoint from gateway SDK

- src/components/AppLayout/Header/components/Layout.tsx
- src/components/AppLayout/Header/components/ProviderDetails/ConnectDetails.tsx
- src/components/AppLayout/Header/components/ProviderInfo/ProviderDisconnected.tsx
- src/components/Spacer/index.tsx
- src/components/forms/GnoForm/index.tsx
- src/components/layout/Button/index.tsx
- src/components/layout/ButtonLink/index.tsx
- src/components/layout/Col/index.tsx
- src/components/layout/Divider/index.tsx
- src/components/layout/Hairline/index.tsx
- src/components/layout/Pre/index.tsx
- src/components/layout/Row/index.tsx
- src/components/layout/Table/index.tsx
- src/logic/notifications/notificationBuilder.tsx
- src/routes/safe/components/Balances/AssetTableCell/index.tsx
- src/routes/safe/components/Balances/Collectibles/components/Item.tsx
> Fix more ESLint errors

- src/logic/safe/transactions/multisend.ts
- src/routes/safe/components/Apps/components/ConfirmTxModal/ConfirmTxModal.test.tsx
- src/routes/safe/components/Apps/components/ConfirmTxModal/ReviewConfirm.tsx
- src/routes/safe/components/Apps/components/ConfirmTxModal/SafeAppLoadError.tsx
- src/routes/safe/components/Apps/components/ConfirmTxModal/index.tsx
Resolves #2709 
The PR adds tests for happy paths, malformed transactions and also checks backward compatibility with v0.X SDKs
It helped to catch few bugs:
- If transactions are malformed, we'd render the error message but still pass malformed transactions to the underlying functions (encoding, gas estimation, etc.), and they'd error
- Large eth values as numbers from v0.X SDKs can overflow
Good question
> Feature: Review Safe App Transaction modal tests

- src/logic/safe/hooks/useLoadSafe.tsx
Related to #2728
This PR fixes the selected currency (on the dropdown) not being persisted when app reloads
> Fix currency dropdown not updating

- src/logic/safe/hooks/useLoadSafe.tsx
- src/logic/safe/hooks/useSafeScheduledUpdates.tsx
- src/logic/safe/store/actions/__tests__/utils.test.ts
- src/logic/safe/store/actions/fetchSafe.ts
- src/logic/safe/store/actions/utils.ts
- src/logic/safe/store/models/safe.ts
- src/logic/safe/store/reducer/safe.ts
- src/logic/safe/utils/__tests__/shouldSafeStoreBeUpdated.test.ts
Resolves #2260
Three new flags (`collectiblesTag`, `txQueuedTag` and `txHistoryTag`) are saved in `store.safe` when the safe is fetched. Only when these flags change AND the user is on the relevant route are collectibles, tokens or transactions fetched again.
Check that the endpoints are not queried more than once in the Network tab. Make a transaction etc. and check that the correct endpoint(s) is queried again.
> Only poll when tags change on relevant paths

- src/routes/safe/components/Balances/SendModal/screens/SendFunds/index.tsx
Resolves #2711 
Looks like it was [a regression](https://github.com/gnosis/safe-react/pull/1637/files#diff-992f0b2127f35603d38b3ed7b99b326bdcf6d45084cc40879fc95fa3b4f173fdR127-R129) from when Spending Limits were introduced.
Returns a validation object when amount is not set.
Try to submit the Send Funds form with no amount.
> Fix amount validtion in Send Funds

- .github/workflows/cla.yml
- src/components/Table/TableHead.tsx
Resolves #N/A
Resolves the Material UI warning on the DevTools console
Updates the prop type
When navigating to the ASSETS>COINS which has a table, the warning should be gone
> Fix warning of renamed prop type from MaterialUI

- src/components/DecodeTxs/index.tsx
- src/logic/contractInteraction/sources/ABIService/index.ts
- src/logic/contracts/generateBatchRequests.ts
- src/logic/contracts/methodIds.ts
- src/logic/hooks/useEstimateTransactionGas.tsx
- src/logic/safe/transactions/__tests__/txMonitor.test.ts
- src/logic/safe/transactions/txMonitor.ts
- src/logic/safe/utils/spendingLimits.ts
- src/logic/wallets/getWeb3.ts
- src/routes/load/Load.test.tsx
- src/routes/new-load/Load.test.tsx
- src/routes/safe/components/Apps/components/ConfirmTxModal/ReviewConfirm.tsx
- src/routes/safe/components/Apps/components/SignMessageModal/SignMessageModal.test.tsx
- src/routes/safe/components/Apps/components/SignMessageModal/index.tsx
- src/routes/safe/container/hooks/useTransactionParameters.ts
Fixes the issue reported in this comment:
https://github.com/gnosis/safe-react/pull/2720#issuecomment-926118202
It wasn't only related to the create safe step, but in many places we were using a readOnly instance of web3. Most of the cases didn't had issues because it was not used to do queries to the blockchain but just for the unit conversion or parsing. But in those cases where we launch a query to the blockchain it was still initialized with the default chain RPC, so wrong RPC query was send in other chains
We create a new instance of web3ReadOnly for each network, but we cache them as singleton instance in order to avoid creating many new objects
Try to create a safe in a chain different than the default one and check that is correctly detected. Also RPC calls can be check in network …
> Fix web3 instance after switching chain

- src/components/SafeListSidebar/SafeList/index.tsx
Resolves console warning regarding `<li>` descendants:
Instead of using an `<li>` element, a `<div>` is used instead.
Open `Safes owned on ${network}` collapsed menu and check console that no warning is there.
> Fix unified li nesting error

- src/routes/safe/components/Apps/utils.ts
Resolves #
Came across a small typo while working on getting our `manifest.json` file up to spec.
> Fix small typo "fullfil" in error message displayed in UI

- .github/workflows/cla.yml
- src/components/AppLayout/index.tsx
- src/components/Table/TableHead.tsx
- src/routes/safe/components/Apps/components/AppFrame.tsx
- src/routes/safe/components/Transactions/TxList/styled.tsx
Resolves #2714
Renders the `Footer` component if the navigation is in the _Welcome Page_ or in the _Settings_ route
Navigate to the _Welcome Page_ or _Settings_ route and check the `Footer` is present. In all the others pages it shouldn't be displayed
> Render Footer component conditionaly

- src/routes/safe/components/Settings/UpdateSafeModal/index.tsx
Resolves #2787
Adds a piece of text in the upgrade popup
* Go to settings
* Click on upgrade safe
> Add a warning in the Safe upgrade modal

- .github/workflows/deploy-rinkeby.yml
We're going to use the dev site for l2-ux instead of the dev branch temporarily.
See https://github.com/gnosis/safe-react/commit/9d3d172a64a4bb46a05cea4b4c9fb8fd5972c846#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3R125
> Don't deploy Rinkeby on dev

- src/components/App/index.tsx
- src/logic/safe/hooks/useLoadSafe.tsx
- src/logic/safe/store/actions/fetchSafe.ts
Resolves #2786
As with the upcoming `l2-ux`, the safe address from the URL is now the source for safe loading. The `isSafeLoaded` flag now depends on this changing address and the removal the fetching `isCollectiblesPage` flag has been removed.
Open a safe that has collectibles, then switch to one that has none. The second one should not display collectibles from the first. Switching back to the first should also not show none.
> Fix collectibles being cached across safes

- src/routes/safe/components/Transactions/TxList/modals/ApproveTxModal.tsx
Resolves #2719
The API was deployed to prod, so we can safely remove this backwards-compatible casting.
Case 1:
* Create and approve a transaction
* Make sure the gas is passed to metamask
Case 2:
* Create a transaction
* Edit the gas in Advanced settings
* Make sure the gas is passed to metamask
> Chore: remove toString from gas params

- src/components/SafeListSidebar/SafeList/index.tsx
A small CSS fix for the Owned Safes to not have a top padding when it's a single element in the network section.
But it gets a padding when there are added safes:
> [L2-UX] Sidebar: owned safes padding only when there are added safes

- src/routes/safe/components/Settings/Advanced/index.tsx
- src/routes/safe/components/Settings/SafeDetails/index.tsx
- src/routes/safe/components/Settings/ThresholdSettings/index.tsx
- src/routes/safe/components/Settings/index.tsx
* Fixed the missing breadcrumbs text was missing
* Added an indication of the Safe's network in the settings
* Fixed title spelling (capitalized nouns) in the Settings
> [L2-UX] Fix Settings breadcrumbs; add ChainIndicator in Safe Details

- src/logic/wallets/onboard.ts
Resolves #2824
Restore setting network name to lower case when initializing onboard.js
- Use the app with Ledger.
- Try to create a Safe or execute a transaction
> Fix ledger/torus wallet transactions

- README.md
Resolves #2932
Network config docs are out of date, so we're removing them.
> Chore: remove obsolete docs from the readme

- src/routes/LoadSafePage/LoadSafePage.test.tsx
- src/routes/LoadSafePage/steps/LoadSafeAddressStep.tsx
Resolves #2920
The root cause was an async race condition when loading Safe info.
User first enters an un-checksummed address, it fetches Safe info. Then the address is automatically checksummed and fetched again. If the first request arrives _after_ the second request, it will mark the field as invalid.
Follow the steps from the linked issue.
> Fix: checksummed address still shown as invalid

- .github/workflows/deploy.yml
We treat the "staging" env as an env that is as close to prod as possible. That includes GA tracking, using production services etc.
This PR sets the production build flag for staging.
Alternatively, we could introduce a proper `staging` environment, but I don't see any value in this atm.
It can be tested only when pushed to the main branch.
> Fix: set REACT_APP_ENV=production on staging

- package.json
- src/logic/wallets/utils/walletList.ts
- yarn.lock
Add some fixes related to Wallet Connect and L2 networks. Also improves compatibility with EIP-1559 in general
It also includes changes from #2872
- Check that all wallets can be used in Rinkeby and any L2 chain
- Check that this issue is not happening any more #2092 
- Check that this issue is not happening any more #2740
> Bump bnc-onboard to v1.35

- src/components/ExecuteCheckbox/index.test.tsx
- src/components/ExecuteCheckbox/index.tsx
Resolves #2918
The checkbox won't be shown if there are unexecuted txns in the queue.
It makes a request to get the last tx and checks `isExecuted`.
* Create a tx but don't execute it
* Create another tx – the "Execute tx" checkbox shouldn't appear
> Fix: hide Execute tx checkbox when there are pending txns

- .gitignore
- src/components/ExecuteCheckbox/index.test.tsx
- src/components/ExecuteCheckbox/index.tsx
The tests that use ExecuteCheckbox were logging an error due to a missing mock.
I've added a check so that they don't do that.
> Chore: adjust ExecuteCheckbox tests to not log

- src/logic/hooks/useEstimateTransactionGas.tsx
Resolves #2862
The gas limit set in the "Advanced options" is used to calculate the tx gas cost, aligning with the value displayed in Metamask
Set a new transaction and tweak the Gas Limit in the "Advanced options". The _fee price_ shall be the _Gas price_ * _Gas limit_ that you see in the "Advanced options"
> Fix: use manual gas limit to calculate the gas cost estimation

- src/index.tsx
- src/logic/safe/store/models/safe.ts
- src/routes/safe/components/Settings/SafeDetails/index.tsx
During the migration from non-unified subdomains, the SAFES storage won't have `chainId` in its SafeInfo's.
`chainId` is a new field that has been added recently. It comes from the Gateway.
Since right now we can't guarantee that `chainId` is set on all safes, it should be optional.
Makes `chainId` optional and in the only place where it was used (Settings -> Safe Details), falls back to the current chain.
* Everything should work like before.
* Migrated Safes should _not_ have any `chainId` in the localStorage.
> Fix: init network early; don't set default network in SafeInfo.chainId

- src/routes/safe/components/Apps/components/ConfirmTxModal/ReviewConfirm.tsx
- src/routes/safe/components/Apps/components/ConfirmTxModal/index.tsx
Resolves #2178 
Drain Safe app needs a message being sent to the iframe in order to dismiss the loading spinner representing the app is waiting for the transactions to be processed. Safe Web is sending it when the main `<ReviewConfirm />` is closed but don't in the case we are in `<DecodedTxDetail />`
1) Add the deployed Drain Safe in this PR as a custom app in a Safe Web
2) Drain the account and see how the confirmation modal is being showed from main Safe Web
3) Navigate to any transaction detail and click the close button ('X'). The loading spinner in Drain Safe should disappear
> [Drain Safe] Loading spinner still visible in drain safe app when user close ConfirmTxModal

- src/components/AppLayout/Sidebar/SafeHeader/index.tsx
- src/components/SafeListSidebar/SafeList/SafeListItem.tsx
Resolves #2956
Safe names in the unified sidebar, as well as the current loaded safe name are now truncated with an ellipsis overflow.
1. Open the unified sidebar and expect long-named safes to be truncated.
2. Load said long-named safe and expect the name to be truncated.
> Truncate safe names in sidebar

- src/components/SafeListSidebar/SafeList/index.tsx
Resolves #2987
When the 'Create or add' sidebar placeholder link is clicked, the sidebar toggle function is called.
Open the sidebar on a network on which the user has no Safes and click on the link. If on the `/welcome` route, the sidebar will close and if on another, the route will change to `/welcome and sidebar close.
> fix: Toggle sidebar when link is clicked

- src/config/networks/arbitrum.ts
- src/config/networks/rinkeby.ts
- src/config/networks/xdai.ts
Partially resolves #2837
Resolves #2999
Instead of using a fixed gas price on xDai, request it from the blockchain.
I've done the same for Arbitrum, as it's recommended in their docs.
* Create a tx on xDai
* Check the gasPrice in the advanced settings
Same on Arbitrum.
> Fix: use eth_getGasPrice on xDai and Arbitrum

- src/components/SafeListSidebar/SafeList/SafeListItem.tsx
- src/components/SafeListSidebar/SafeList/index.tsx
- src/logic/safe/hooks/useLocalSafes.tsx
- src/logic/safe/utils/safeInformation.ts
- src/routes/LoadSafePage/fields/utils.ts
- src/utils/storage/index.ts
Resolves Franco's comment here: https://github.com/gnosis/safe-react/pull/3016#issuecomment-971557060
`addedSafes` and `localSafes` weren't in sync. Now we use only `localSafes` in the sidebar, but update it whenever the Safes store is updated.
Bug:
> Fix: update local safes in sidebar

- src/config/networks/bsc.ts
It partially solves #2571 as we finally deployed allowances smart contracts on BSC
After deploying smart contracts to BSC we can safely enable this feature
Just enable a spending limit on BSC and try to use it
> Enable allowance module for BSC

- src/components/AppLayout/Header/components/WalletIcon/index.tsx
We see people using mystery wallets (the Detected Wallet in onboard?), and having the app crashed on accessing a missing icon.
Don't display any icon if connected to a mystery wallet. Chances are, this wallet might just work.
> Fix: don't crash on missing wallet icons

- src/routes/safe/components/Apps/index.tsx
Resolves https://github.com/gnosis/safe-react-apps/issues/192
When showing the disclaimer and cancelling then user should be redirected to app list instead showing assets
1) Go to the app list in incognito or with storage initialized
2) Enter an app
3) Press `Cancel`buttons
4) Should redirect to the app list instead showing the safe assets
> When cancelling the apps disclaimer goback instead showing assets

- package.json
- src/logic/addressBook/store/reducer/index.ts
- src/logic/addressBook/utils/index.ts
- src/routes/safe/components/AddressBook/index.tsx
- yarn.lock
Resolves #2965
On searching for an existing AB entry we compare now the addresses checksum.
Before updating the Redux store we filter out AB entries with same _address_ and _chainId_
On any conditions, exporting and importing your address book should not generate any duplicated entries in the "Address Book"
> Filter the AddressBook sorted entries before displaying them

- src/logic/wallets/getWeb3.ts
Resolves #3032
using `getWeb3ReadOnly().eth.ens.getAddress(name)` instead of ` web3.eth.ens.getAddress(name)` in the `getAddressFromDomain` function to refresh the `web3` object when the user switches the network
Go to [Load Existing Safe in Rinkeby](https://pr3034--safereact.review-safe.gnosisdev.com/app/load) flow and type `alice.eth` in the Safe Address input.
Rinkeby endpoint should be used: `https://rinkeby.infura.io/v3/{API_TOKEN}`
Switch to `Mainnet` network:
Type `alice.eth` in the Safe Address input.
Mainnet endpoint should be used: `https://mainnet.infura.io/v3/{API_TOKEN}`
> Fix: ENS name recognition when switch the network

- src/components/PrefixedEthHashInfo/index.tsx
- src/routes/safe/components/Transactions/TxList/TxInfoCreation.tsx
- src/routes/safe/components/Transactions/TxList/TxSummary.tsx
- src/routes/safe/components/Transactions/TxList/styled.tsx
https://github.com/gnosis/safe-react/pull/3015#issuecomment-975201921 (Bug when uploading a QR code containing a chain prefix in the "Send Collectibles")
Resolves #3036
- Pass the Address without prefix to `EthHashInfo` and let the appearance settings decide if prefix should be displayed
- Removes the chain prefix from "Transaction hash" and "SafeTxHash" fields in the Tx List
From https://github.com/gnosis/safe-react/pull/3015#issuecomment-975201921
> Strip network prefix from the Address when calling EthHashInfo

- src/routes/safe/components/AddressBook/CreateEditEntryModal/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/EthAddressInput/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/SendCollectible/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/SendFunds/index.tsx
- src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/screens/OwnerForm/index.tsx
- src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/OwnerForm/index.tsx
- src/routes/safe/components/Settings/SpendingLimit/FormFields/Beneficiary.tsx
Resolves #3042
Strips the QR code read address from the chain prefix
Follow https://github.com/gnosis/safe-react/issues/3042#issue-1061140762 "Steps to reproduce"
> Strip the scanned address from the chain prefix

- src/components/App/index.tsx
- src/components/StoreMigrator/utils.ts
- src/index.tsx
- src/logic/safe/hooks/useLoadSafe.tsx
- src/logic/safe/store/actions/fetchSafe.ts
Resolves #3023
Resolves #3030
Removes the redirect that [was added](https://github.com/gnosis/safe-react/pull/2977/files#diff-c7124f4a6d36f8d5ad9e166103fce3bc3c5eb3d40bd5b4ede8a443ceb58733c1R30) in #2977.
Open a Safe that doesn't exist. Observe an infinite loader.
> Fix: remove the redirect on failed safe load

- src/components/forms/AddressInput/index.tsx
- src/components/forms/validator.ts
`mustBeEthereumAddress` is now checking also the prefix, so it shouldn't be memoized by the address alone. The same address can be valid on one network, but not valid on another.
So I just removed the memoization, it's completely useless. Who would enter the same address repeatedly?
> Fix: remove memoize on mustBeEthereumAddress

- package.json
- src/routes/safe/components/Apps/components/AppFrame.tsx
- src/routes/safe/components/Apps/components/SignMessageModal/index.tsx
- yarn.lock
Resolves https://github.com/gnosis/safe-react-apps/issues/185
We are going to get the chain info from the apps using the SDK (https://github.com/gnosis/safe-apps-sdk/pull/258). So in this PR we are adding the listener for retrieving the required info
1) Open the Transaction Builder app in https://github.com/gnosis/safe-react-apps/pull/215 inside the Gnosis Safe Web
2) Add a contract
3) Check the labels showing the native token are showing the native one and not always ETH
> Add get chain info listener

- src/config/index.ts
- src/logic/contracts/api/masterCopies.ts
- src/logic/tokens/store/actions/fetchTokens.ts
- src/utils/decodeTx.ts
There was a redundant selector for interacting with the transaction service, as well as dynamic URL creation dotted around the project.
The redudant safe info request URL has been removed. The other URL creation 'selectors' have been moved to the config file.
1. The master copies selector is used in the 'Safe Details' settings section to show the contract version. If it is visible, it works.
2. The decode data selector is used in the 'Review Confirm' fund sending modal. If the decoded transactions are visible, it works.
> Centralise transaction service selectors

- src/routes/safe/components/Balances/AssetTableCell/index.tsx
Resolves #2966
A button which opens Etherscan (or the relevant block explorer) to the token address was added next to the token name.
1. Open a safe with varying assets.
2. Click the button that opens the block explorer.
3. Verify that it is correct.
> Add token address in asset list

- package.json
- src/components/AppLayout/Sidebar/useSidebarItems.tsx
- src/components/forms/validator.ts
- src/config/cache/chains.ts
- src/config/chain-workarounds.ts
- src/config/chain.d.ts
- src/config/index.ts
- src/logic/safe/store/actions/__tests__/fetchSafe.test.ts
- src/logic/safe/store/actions/__tests__/utils.test.ts
- src/logic/safe/store/models/safe.ts
- src/logic/safe/transactions/gas.ts
- src/logic/safe/utils/__tests__/safeVersion.test.ts
- src/logic/safe/utils/safeVersion.ts
- src/routes/safe/components/Balances/SendModal/screens/AddressBookInput/index.tsx
- src/routes/safe/components/Transactions/helpers/useSafeTxGas.ts
- yarn.lock
Resolves #3121 #3118
Store both chain features and Safe version features in the `enabledFeatures`.
When checking if a feature is enabled, always use `hasFeature` which takes an optional Safe version param.
* Test optional safeTxGas for 1.3.0 Safes and that it's obligatory for 1.1.1
* Test maxFeePerGas vs gasLimit on mainnet (maxFeePerGas) vs Polygon (gasLimit)
* Test that Collectibles are disabled for 1.0.0 Safes and enabled for newer ones
> Refactor: chain features and versioned features

- src/config/index.ts
- src/logic/safe/utils/safeVersion.ts
- src/logic/wallets/ethTransactions.ts
- src/utils/constants.ts
Resolves #3124
Restores the ability to configure a fixed gas price on config-service.
* Open an xDai Safe
* Make a tx
* Gas price should be always 1
> Fix: restore the fixed gas price option

- src/routes/safe/components/Transactions/TxList/DelegateCallWarning.tsx
- src/routes/safe/components/Transactions/TxList/MultiSendDetails.tsx
- src/routes/safe/components/Transactions/TxList/TxSummary.tsx
- src/routes/safe/components/Transactions/TxList/styled.tsx
Resolves #3115
Nested delegate calls now display that they are a) a delegate call and b) (un-)expected. They also, like #3091, base their legitimacy on whether the address is known or not.
An unexpected, nested delegate call can be found [here](https://pr3122--safereact.review-safe.gnosisdev.com/app/rin:0x73a7AA145338587f7aB7f63c06d187C85dF4727e/transactions/multisig_0x73a7AA145338587f7aB7f63c06d187C85dF4727e_0xba28109747222d6cfb7f0fb75f03d49957e343674bc116162b038e244dbcc6d6).
The linked example transaction can be used as a PoC for this new warning.
In order to create another, it needs to be done via a script. You would have to use node.js or propose a transaction.
(The following "parent" delegate calls are "unexpected" because our MultiSend contract is not a known address on Rinkeby.) …
> Add nested delegate call warnings

- src/routes/safe/components/Transactions/TxList/MultiSendDetails.tsx
Resolves #3115
Unexpected delegate calls from nested transactions automatically expand their relevant multisend transaction by default.
- When viewing transaction 1 in the list [here](https://pr3143--safereact.review-safe.gnosisdev.com/app/rin:0x73a7AA145338587f7aB7f63c06d187C85dF4727e/transactions/multisig_0x73a7AA145338587f7aB7f63c06d187C85dF4727e_0xba28109747222d6cfb7f0fb75f03d49957e343674bc116162b038e244dbcc6d6), Action 3 (an unexpected delegate call) should be automatically expanded.
- Viewing it via deeplink [here](https://pr3143--safereact.review-safe.gnosisdev.com/app/rin:0x73a7AA145338587f7aB7f63c06d187C85dF4727e/transactions) should also automatically expand it.
Transaction list:
Deeplink:
> Expand nested, unexpected delegate calls by default

- src/components/forms/AddressInput/index.tsx
Resolves #3131
The resolved ENS address that was already in the AB wasn't displayed because we're not mutating the input value unless the new value is validated.
I've changed this condition to only check the value against the pre-mutation validators.
* Create an AB entry with alice.eth as the address
* Try to create another entry with the same alice.eth domain
* It should show the resolved address but not let you add the duplicate entry
> Fix: show AddressInput ENS resolution for existing AB entries

- src/components/TransactionFailText/index.tsx
Resolves #3102
If networks mismatch, it says "Your wallet is connected to a wrong chain" in the error message.
> Feature: add a wrong chain error message

- package.json
- yarn.lock
The interface was using an older version (0xa25b3579a295be016de5eb5F082b54B12d45F72C) of `safe-deployments`, it doesn't have any drawbacks but this version was meant to be used. The reason for that is that we forgot to release safe-deployments with the updated address (0xA65387F16B013cf2Af4605Ad8aA5ec25a2cbA3a2). 
By updating `safe-deployments` to version `1.5.0` that uses the new address
connect the safe to https://example.walletconnect.org/ and click use `eth_sign` button, the transaction pop up should call `0xA65387F16B013cf2Af4605Ad8aA5ec25a2cbA3a2`
> Upgrade safe-deployments 1.5.0

- src/logic/contracts/safeContracts.ts
Resolves #3142
Instead of using the `defaultAddress` for deployments, the chain-specific address is always used. If no chain-specific address is found, an error is thrown.
1. Creating a Safe on Optimistic should now work, and checking the `to` should now be the correct ProxyFactory address: https://optimistic.etherscan.io/address/0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC#code
> Don't use default deployment addresses

- src/components/SafeListSidebar/SafeList/SafeListItem.tsx
The removal of duplicate code. This may also fix the scrolling in long Safe lists.
> Remove duplicate scrollIntoView

- src/utils/storage/Storage.ts
- src/utils/storage/__tests__/local.test.ts
When `undefined` is saved into the localStorage, it cannot be parsed when read afterwards.
I've added a special handling for this case.
> Fix: parsing undefined in localStorage

- src/logic/safe/utils/mocks/remoteConfig.json
- src/logic/safe/utils/safeStorage.ts
- src/utils/storage/__tests__/index.test.ts
- src/utils/storage/index.ts
We used to use hard-coded chain names for local storage keys.
It was changed to use `chainName` from config-service. Those `chainNames` aren't the same as the old ones.
Restores a hard-coded config for old chains and uses `chainId` for new chains.
* Use old local storage
* See that your data is read correctly
> Fix: legacy storage keys

- src/logic/safe/store/actions/createTransaction.ts
- src/routes/safe/components/Transactions/TxList/utils.ts
Resolves #3069
Navigation to deeplinked transaction after transaction creation was enabled because the error was occurring with this feature. When a deeplinked transaction is opened, and hence loaded from backend via it's `txId`, the custom frontend-only `Transaction` typed object is created.
After the immediate creation of a transaction, the fetched transaction may lack a `timestamp`. As such, the fallback value was changed from `0` to the current timestamp because the transaction was effectively created 'now'. Later polls for transactions will overwrite this with the exact timestamp that is eventually fetched.
1. Create a transaction, adding it to the queue.
2. Reject said transaction and await for rejection execution.
3. The transaction details date label and/or list position should …
> Fix: deep-linked tx – use current timestamp as fallback

- src/config/__tests__/index.test.ts
- src/config/index.ts
- src/logic/safe/utils/mocks/remoteConfig.json
- src/logic/wallets/utils/network.ts
Resolves #2869
Uses the new config field.
- Delete previous wallet configs.
- Switch to an L2 network, accept suggested config
- Make sure it's a public RPC
> Feature: use public RPCs for suggested wallet configs

- src/logic/safe/utils/spendingLimits.ts
Resolves #3173
The Spending Limits feature is throwing on Avalanche, but the error wasn't caught properly.
The error is now caught and is logged.
* Open `Avalanche:0xbD99AB5EbD2a68e4Ad4b21dF73f5f393fe223411`
* Check the console
> Fix: catch spending limits error

- package.json
- src/logic/safe/utils/mocks/remoteConfig.json
- src/logic/wallets/onboard.ts
Issues with Trezor (and Ledger?) transactions on mainnet.
With the migration to the chains endpoint, 'Mainnet' was renamed to 'Ethereum'.
This PR includes a hardcoded quick fix to send `'mainnet'` when it would send `'ethereum'` to onboard's `networkName` configuration.
1. Perform a transaction on mainnet and expect it to succeed.
> Fix: incorrect mainnet networkName used in onboard

- src/routes/safe/components/Settings/Appearance/index.tsx
- src/utils/googleAnalytics.ts
Appearance setting tracking.
When a user opens the appearance setting tab a GA tracking event is dispatched. A dynamic (enable/disable) event is dispatched when a user changes their EIP-3770 prefix preferences.
1. Open the appearance settings pane and note the GA event.
2. Change the prefix preference and note the matching GA event.
> Add GA appearance/EIP-3770 tracking

- src/utils/constants.ts
Resolves #
If one wants to run his own stack of gnosis infra I think it needs to override GATEWAY_URL in safe-react.
> Chore: configurable GATEWAY_URL

- src/utils/constants.ts
Resolves #
React doesn't pick up env vars if not prefixed with `REACT_APP_`
adds prefixes REACT_APP_ to `GATEWAY_URL` and `CONFIG_SERVICE_URL`
> fix: prefix envs with REACT_APP_

- package.json
- src/components/StoreMigrator/index.tsx
- src/logic/safe/utils/mocks/remoteConfig.json
- src/utils/storage/index.ts
After the [localStorage refactoring](https://github.com/gnosis/safe-react/commit/134c787c76b7ef073264fe84c19aeadb953f71d9#diff-74d715bc7b3f7d56dd1259d277cfef3dbebdc48b65bd8a019adc6477e122060c) and removal of ImmortalDB, the L2-UX migration became broken.
* Renames the `v2_` keys to `_immortal|v2_` to fix existing broken data
* Adds the correct prefix so that new migrations are correct
**Case 1 (no prior migration):**
* Run app on localhost:3001 and open some L2 chain on there 
* Run another version of the app on localhost:3000, open mainnet
* Clear localStorage and refresh
* It should migrate data from localhost:3001
**Case 2 (with prior broken migration):**
* Run app on localhost:3001
* Run another version of the app on localhost:3000 on commit before this fix, open mainnet
* Clear …
> Fix: wrong keys after migration 🔥

- src/components/DecodeTxs/__tests__/index.ts
- src/components/DecodeTxs/index.tsx
- src/logic/safe/store/actions/createTransaction.ts
- src/logic/safe/store/actions/processTransaction.ts
- src/logic/safe/store/models/types/transaction.ts
- src/logic/safe/transactions/txHistory.ts
- src/routes/safe/components/Transactions/TxList/TxCollapsedActions.tsx
- src/routes/safe/components/Transactions/TxList/TxDataRow.tsx
- src/routes/safe/components/Transactions/TxList/TxDetails.tsx
- src/routes/safe/components/Transactions/TxList/TxExpandedActions.tsx
- src/routes/safe/components/Transactions/TxList/TxInfoCreation.tsx
- src/routes/safe/components/Transactions/TxList/TxInfoMultiSend.tsx
- src/routes/safe/components/Transactions/TxList/TxSummary.tsx
- src/routes/safe/components/Transactions/TxList/styled.tsx
- src/utils/getByteLength.ts
Resolves #2989
Now it should be possible to verify advanced Tx data in all types of transactions:
- safeTxHash
- nonce
- to
- value
- raw data - no need to display in full, being able to copy is sufficient
- operation
- safeTxGas
- baseGas
- gasPrice
- gasToken
- refundReceiver
- signatures
Go to the Transactions list.
Click on one of the entries.
The transactions details (queued/history) shall display the Tx advanced info
> Tx list tx details

- .github/workflows/release-mainnet-desktop.yml
This PR pins the action-electron-builder action to the full commit hash instead of the v1 tag. As [github states](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) pinning to tag has a risk, "because a tag can be moved or deleted if a bad actor gains access to the repository storing the action", i.e., the contents of the action can change. By using the full hash this cannot happen.
Changes the v1 tag to the corresponding commit hash. You can confirm the hash is correct here https://github.com/samuelmeuli/action-electron-builder/releases/tag/v1
> Pin the action-electron-builder action to a full commit hash instead of a tag

- public/electron.ts
Only the Electron application needs to access the server it creates in: https://github.com/gnosis/safe-react/blob/8815f8bee61acf5db5a8c0c6aa4277cb1e13a82c/public/electron.ts#L31
So, the server should only be exposed localhost.
This PR uses '127.0.0.1' as the second argument of the `listen` method to accomplish this.
Run `netstat -tulnp` to verify that worked.
Before:
```
tcp6       0      0 :::5000                 :::*                    LISTEN      81840/safe-react
```
After:
```
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      84561/safe-react    
```
> Make the Electron server listen only on localhost instead of on all interfaces

- public/electron.ts
This commit ensures that the Electron app allows only the Electron-created backend at https://localhost:5000 to have an invalid (self-signed) certificate.
Instead of appending `'ignore-certificate-errors'` to the command line, catch certificate errors and check the associated origin. 
Reference: https://www.electronjs.org/docs/latest/api/app#event-certificate-error
> Allow certificates errors only for the Electron-created back end

- src/logic/safe/store/reducer/gatewayTransactions.ts
- src/routes/routes.ts
- src/routes/safe/components/Transactions/TxList/TxShareButton.tsx
- src/routes/safe/components/Transactions/TxList/TxSingularDetails.tsx
- src/routes/safe/components/Transactions/TxList/TxSummary.tsx
- src/routes/safe/components/Transactions/TxList/hooks/useQueueTransactions.ts
- src/routes/safe/container/index.tsx
- src/utils/constants.ts
Resolves #3204
Queued transactions were sometimes lacking a `label` and ythere was no distinguishment between `queued.next` and `queued.queued`. All unlabelled transactions were being deemed as `queued.next`, therefore showing the confirmation buttons.
Successfully labeled transactions then prevented due to the `txQueuedTag` conditional polling. Queued transactions are now manually requested if the deeplink inconsistency is present: a `queued.next` transaction does **not** exist, but a `queued.queued` does.
Note: deeplink slug names were also clarified as `safeTxHash` within the project and regex matching was included.
1. Create a queued transaction.
2. Create a second queued transaction.
3. The second should have a disabled confirm button.
4. Navigating back to the queued list, both …
> Fix: deeplinked, out of nonce order transactions allow confirmation 

- src/logic/safe/store/reducer/gatewayTransactions.ts
Resolves #3202
When out of order nonced, grouped transactions move from 'queued' to 'next', all 'next' transactions are added under said nonce.
1. Create a 'next' transaction but do not execute it.
2. Create several transactions in the 'queue' with the same nonce.
3. Execute the 'next' transaction and observe all 'queue' transactions shift to 'next', remaining in a group.
> Move all grouped transactions from next to queue

- src/components/GlobalErrorBoundary/index.tsx
Resolves #3220
The `<ErrorBoundary>` component was updated to remove the email address and update the Discord invitation link.
Trigger the app to crash and observe no email link and an updated Discord link.
> Fix: remove email and update Discord link from error boundary

- README.md
- src/components/GlobalErrorBoundary/index.tsx
Use our generic Discord link in all places where we link to our Discord.
All instances of the Discord link were changed.
- Observe that the Discord link has changed in the `README.md`, as well as in the error boundary.
> Use generic Discord link

- src/routes/safe/components/Transactions/TxList/TokenTransferAmount.tsx
Resolves #2251
Long token names are truncated.
- Open eth:0x7fDc01fF064216493e7c695abA46Dcd4eCC376Ae and go to historical transactions: https://pr3237--safereact.review-safe.gnosisdev.com/app/eth:0x7fDc01fF064216493e7c695abA46Dcd4eCC376Ae/transactions/history
- Scroll down to the incoming txs with 1 MYDARKTWISTEDFANTASYOPENEDITIONBYDOTPIGEON and observe that it is now truncated
> Fix: truncate long token names

- src/components/ReviewInfoText/index.tsx
Resolves #3219
Suggests the **BE-services** recommended tx nonce when trying to create a tx with an already executed nonce
1. Start creating a transaction
2. Change the "Safe nonce" to an already executed nonce
3. You shall see the implemented warning message
> Fix: Use recommended nonce for already executed nonce message

- src/components/Root/index.tsx
- src/config/cache/chains.ts
- src/routes/routes.test.tsx
- src/routes/routes.ts
- src/utils/__tests__/history.test.ts
- src/utils/history.ts
- Connection issues when switching from production chain to staging CGW.
- Resolves #3218
- Checks the validity of the current `chainId` against the returned values from the CGW and redirects to "Welcome Page" when the URL chain prefix is not in the retrieved chains
Insert an URL with a invalid chain prefix like
https://pr3228--safereact.review-safe.gnosisdev.com/app/xdai:0x0209eB92EB883dBD9bD01fD207d588E24F947913/balances (`xdai` does not exist in _staging_)
OR
https://pr3228--safereact.review-safe.gnosisdev.com/app/dummy:0x0209eB92EB883dBD9bD01fD207d588E24F947913/balances (unexistant chain)
> Fix: redirect when invalid chain prefix in URL

- src/routes/safe/components/Transactions/TxList/hooks/useActionButtonsHandlers.ts
Resolves #3244
The `txLocation` context was not updating as it was wrapped in a `useRef`. Removing it allowed for the contextualised value to update when it changed in accordance with the `TxLocationProvider`.
**Ensure that the Safe has a 1/? threshold and that the transaction queue is empty**
1. Create a transaction but do not execute it.
2. When navigated to the deeplink view, the execution button should be enabled.
> Enable execution button on deeplink transactions

- src/components/ReviewInfoText/index.tsx
Resolves
The tx out of order warning shall not display if `transactionsToGo` is not a number
> Fix: return if transactionsToGo is NaN

- src/routes/safe/components/Transactions/TxList/TxDetails.tsx
Resolves #3252
The transaction 'actions' were not showing correctly because they referenced whether a user could execute or reject. If a transaction had been rejected, it would therefore not show actions because it, of course, could not be executed either.
This previous change was removed and the conditional rendering of the action buttons now depends on whether the user has connected their wallet.
1. Create a transaction on a 2/? threshold Safe.
2. Reject said transaction.
3. Observe that the actions displayed.
> Fix: show confirm button for rejection txns

- src/logic/safe/store/actions/processTransaction.ts
Uncaught promise when transaction executes
The contract error retrieval was removed because `txHash` is never set. An error was being thrown as the `''` fallback was being used to retrieve the contract error.
Execute a transaction and observe no error being thrown (and not caught) in the console.
> Remove uncaught transaction execution promise

- src/logic/safe/store/actions/processTransaction.ts
Resolves #3263
The thrown error message is appending to the error notification as it originally was before errors were retrieved from the contract.
- Reject a transaction via MetaMask and observe the rejection error message in the notification.
> Append error message to notification upon rejection

- src/logic/safe/store/reducer/gatewayTransactions.ts
Occasional app crash when queued transactions have not loaded quick enough
Optional chaining was added to the store interaction.
> Add optional chaining in transaction reducer

- src/logic/safe/store/actions/processTransaction.ts
Resolves #3261
Transactions need only be proposed if it is not immediately executing. The unnecessary proposal has been removed.
1. Create a transaction and ensure that it has sufficient confirmations, but do not execute it.
2. Execute it as a non-owner and expect it to be successful and not show an error in the console.
> Remove unnecessary transaction proposal

- src/routes/safe/components/Transactions/TxList/TxCollapsedActions.tsx
- src/routes/safe/components/Transactions/TxList/TxExpandedActions.tsx
Resolves unaccurate "Confirm" copies when the tx failed to execute
Adds local tx status `PENDING_FAILED` to the "awaiting execution" logic
1. Create a tx and reject executing it in Metamask
2. In the Next Queue you shall see the "Execute" copies instead of the "Confirm"
> fix: add PENDING_FAILED to the awaiting execution logic

- src/routes/safe/components/Transactions/TxList/TxSummary.tsx
Resolves #3275
The deeplink share button was only shown when `!IS_PRODUCTION`. This flag has been removed.
1. Open a Safe (on the PR, ensuring that it is the production environment).
2. View the transaction history and observe the share button on outgoing transacitons.
> Show deeplink share on production

- .github/workflows/cla.yml
Commits that go to main should have already been checked, so no need to run it again.
> Chore: don't check CLA for release branches

- src/components/TransactionFailText/index.tsx
Resolves #3197
When a transaction estimation status suggests that it will fail, the error now takes into whether the current user is granted and adjusts the error message accordingly:
```
isGranted
? This transaction will most likely fail. {{description}}
: isWrongChain
? Your wallet is connected to the wrong chain.
: You are currently not an owner of this Safe and won't be able to submit this tx.
```
Attempt to make a transaction via a Safe App as a non-owner and observe the error message.
> Add non-owner error message for Safe Apps

- src/routes/safe/components/Transactions/TxList/TxCollapsed.tsx
- src/routes/safe/components/Transactions/TxList/TxCollapsedActions.tsx
- src/routes/safe/components/Transactions/TxList/TxExpandedActions.tsx
- src/routes/safe/components/Transactions/TxList/utils.ts
Resolves #3280
The status checking logic was fixed to compare it against both `AWAITING_EXECUTION` AND `PENDING_FAILED`.
1. Create a transaction on a 2/? threshold Safe
2. Observe that the action button is 'Confirm', not 'Execute'
> Adjust awaiting execution status check

- src/routes/safe/components/Transactions/TxList/TxDetails.tsx
- src/routes/safe/components/Transactions/TxList/TxModuleInfo.tsx
- src/routes/safe/components/Transactions/TxList/TxSummary.tsx
- src/routes/safe/components/Transactions/TxList/styled.tsx
Resolves #2990
The module address and name, when in the address book or known, is now displayed when module-related transactions are expanded.
1. Open Safe `eth:0x1f8eaD1e6e10e6856d68be2217EDDC71D8b4eC87` on production CGW.
2. View historical transactions (all of which are module induced).
3. Observe module details below transaction data.
> Add module details to module transactions

- docs/transactions.md
- src/routes/safe/components/Transactions/TxList/hooks/useTransactionStatus.ts
Resolves https://github.com/gnosis/safe-react/issues/3286
Changes the TxDetails copy when the tx is rejected by the user
1. Try to execute a transaction
2. Reject with MetaMask
3. Check the "Next Queued" tx status copy
> Fix: Change tx queued copy

- src/components/AppLayout/Header/components/Layout.tsx
- src/components/AppLayout/Header/components/NetworkLabel.tsx
- src/components/AppLayout/index.tsx
- src/components/Root/index.module.scss
- src/components/SafeListSidebar/SafeList/index.tsx
- src/logic/hooks/useDarkMode.ts
- src/routes/safe/components/Settings/Appearance/index.tsx
A poor man's dark mode using a CSS filter.
> Feature: dark mode

- README.md
Incorrect docs link.
The relative path of the transactions docs was incorrect. It has been updated to match the document name.
Click the link in the readme and ensure that it navigates to the docs/transactions.md file.
> Update transaction docs link in readme

- src/routes/CreateSafePage/components/SafeCreationProcess.tsx
- src/routes/opening/index.tsx
It was saying just "Safe creation failed". I've added an actual error message.
> Show a meaningful error message on Safe creation

- src/components/Modal/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/ModalHeader/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/ModalHeader/style.ts
Resolves #3288
Adds `nowrap` to the modal header and and `overflow: hidden` to the ChainIndicator
When there's not enough space, the ChainIndicator will be cut off:
> Fix: CSS in modal header

- src/components/DecodeTxs/index.tsx
- src/routes/safe/components/Apps/components/ConfirmTxModal/ConfirmTxModal.test.tsx
- src/routes/safe/components/Transactions/TxList/MultiSendDetails.tsx
- src/routes/safe/components/Transactions/TxList/TxData.tsx
- src/routes/safe/components/Transactions/__tests__/utils.test.ts
- src/routes/safe/components/Transactions/helpers/utils.ts
Resolves #3254
All instances of "Send 0 {{symbol}} to:" have been changed to "Interact with:" and "Send {{amount}} {{symbol}} to:" changed to "Interact with (and send {{amount}} {{symbol}} to):"
1. Create/execute a contract interaction of 0 cost and observe the new title.
2. Create/execute a transaction of >0 cost and observe the new title.
> Fix: "Send 0 eth to" -> "Interact with"

- package.json
- src/routes/safe/components/Apps/components/AppsList.test.tsx
- yarn.lock
Resolves [this minor issue with the types in the gateway-sdk](https://github.com/gnosis/safe-react-apps/issues/286)
Updated `@gnosis.pm/safe-react-gateway-sdk` to `2.8.2` version and removed the `@ts-ignore` in the `AppList.test.js`
> Updated @gnosis.pm/safe-react-gateway-sdk to fix SafeAppsResponse types

- src/logic/safe/store/actions/createTransaction.ts
- src/logic/safe/store/actions/processTransaction.ts
Resolves #3305
The logic behind whether the transaction should execute now takes into account whether it is an approval transaction or not.
1. Create a transaction but do not execute it.
2. Execute it and observe that it doesn't request an off-chain signature, instead an execution.
> Execute depending on approval

- src/routes/safe/components/Transactions/TxList/MethodDetails.tsx
- src/routes/safe/components/Transactions/TxList/MethodValue.tsx
Resolves #3284
Adds line breaks to labels and values within `MethodDetails` if there is not enough space left and adds horizontal scroll.
1. Open https://pr3309--safereact.review-safe.gnosisdev.com/app/eth:0x4FeE396c8d940B801747CA84632580f917690E87/transactions/0x33eb21a8639f9411ae96a388f41b7af573e118771628b5d57c08f96817349ac9
2. Observe that `MethodDetails` data is visible/scrollable on smaller screens
> Display MethodDetails content on smaller screens

- src/components/App/index.tsx
- src/components/Root/index.tsx
- src/logic/config/store/middleware/index.ts
- src/logic/config/utils/index.ts
- src/logic/contracts/safeContracts.ts
- src/logic/safe/utils/safeVersion.ts
- src/logic/wallets/store/middlewares/providerWatcher.ts
- src/logic/wallets/store/reducer/provider.ts
- src/routes/CreateSafePage/CreateSafePage.tsx
- src/routes/opening/index.tsx
Resolves #3311
Contracts were being instantiated via the `web3` object, meaning that the `chainId` could be stale, i.e. the user is connected to Rinkeby but the unified app is on Avalanche.
Instead of relying on the `chainId` from the `web3` object, `_chainId` (a local mirror of that from the store) is used instead. This is kept in sync with the current network displayed in the UI via the config middleware (where the contracts are initiated).
1. Open a Safe on Rinkeby.
2. Create a MultiSend transaction via the Transaction Builder.
3. Switch to Avalanche (which uses a different addressed MultiSendOnly contract when compared to Rinkeby) via the network selector in the top right but do not connect via MetaMask.
4. Submit the transaction and observe that it does not show an unexpected …
> Instantiate contracts via `chainId` from loaded config

- src/logic/safe/store/actions/createTransaction.ts
- src/logic/safe/store/actions/processTransaction.ts
Resolves #3305
Instead of blanket establishing `isExecution` within `TxSender`, the logic is now extracted into the respective transaction creation/processing function as the previous logic was before the refactor.
On top of this, the transaction proposal to backend now depends on whether the user is an owner.
Every variation of transaction is affected by this. The cases are as follows:
1. Create and execute transaction immediately.
2. Queue transaction and execute later by owner.
3. Queue transaction and execute by non-owner.
1. Create and confirm transaction then execute by owner(s).
2. Create and confirm transaction then execute by non-owner.
1. Create Safe successfully.
> fix: transaction stage-relative execution

- src/routes/safe/components/Transactions/TxList/hooks/useAssetInfo.ts
- src/routes/safe/components/Transactions/TxList/utils.ts
Resolves #3241
ERC-721 token `name`s and `amountWithSymbol`s are now appended with a `(#tokenId)`.
1. Queue a ERC-721 token transfer.
2. Observe the token id appended to the title and transaction info.
This should also be present on receipts as well.
> feat: show ERC-721 token ids

- src/logic/safe/store/actions/createTransaction.ts
- src/logic/safe/store/actions/processTransaction.ts
Resolves #3326
Transaction proposal now takes whether the transaction is being immediately created and executed into account. Proposals now only occur when a transaction is being created, created and immediately executed (1 threshold) or confirmed. (Execution should not propose).
An extra flag is now passed from `processTransaction` to our `TxSender`: `approveAndExecute`. This flag is referenced to determine `isImmediateExecution` (a 1/? threshold Safe creating and immediately execution a transaction):
```ts
// Creation or confirmation
const isOffChainSigning = !isExecution && signature
// 1/? Safe is creating and executing transaction immediately
const isOnChainSigning = isExecution && !signature
const isImmediateExecution = isOnChainSigning && !approveAndExecute
if (isOffChainSigning || …
```
> fix: remove unnecessary transaction proposals

- package.json
- src/routes/safe/components/Apps/components/AppFrame.tsx
- src/routes/safe/components/Apps/hooks/useIframeMessageHandler.ts
- src/routes/safe/components/Apps/utils.ts
Resolves #3339
https://github.com/gnosis/safe-react-apps/issues/275
https://github.com/gnosis/safe-apps-list/issues/99
https://github.com/gnosis/safe-apps-list/issues/100
https://github.com/gnosis/safe-react-apps/issues/293
We overwritte Ethereum or Gnosis Chain names so apps still get legacy names, MAINNET and XDAI
Open xDai bridge and it should be possible to use it
Same for Pool Together, OpenZeppelin, and Idle V4
> Fix apps using legacy chain name as key

- src/components/AppLayout/Sidebar/DevTools/index.tsx
Queue transaction creation on 2+/? Safe dev tooling
The threshold of a Safe is now referenced when creating a queued transaction via the macros on a 2+/? Safe. If it is higher than 1:
1. The queue transaction macros does not attempt to uncheck the execute checkbox.
2. The "create transaction" button is disabled.
1. Open a 2+/? Safe and observe that the create transaction button is disabled.
2. Clicking the "queue transaction" button does not crash the app.
> fix: reference threshold in dev tool macros

- package.json
- src/routes/safe/components/Transactions/TxList/DelegateCallWarning.tsx
- src/routes/safe/components/Transactions/TxList/MultiSendDetails.tsx
- src/routes/safe/components/Transactions/TxList/TxSummary.tsx
- yarn.lock
Resolves #3099
The trust of a delegate is no longer based on whether it is named. We instead warn based on the `trustedDelegateCallTarget` flag and ALWAYS warn when they are nested.
- Observe the warning on an untrusted delegate call [here](https://pr3433--safereact.review-safe.gnosisdev.com/app/eth:0x1f7f8DA3eac80DBc0b4A49BC447A88585D8766C8/transactions/0xd880933f98f7805f5ff16a3370a4385c18a0893125b91a21329e0245840bd94e).
- Observe the default warning on nested delegate call [here](https://pr3433--safereact.review-safe.gnosisdev.com/app/rin:0x73a7AA145338587f7aB7f63c06d187C85dF4727e/transactions/0xba28109747222d6cfb7f0fb75f03d49957e343674bc116162b038e244dbcc6d6).
Untrusted warning
Default nested warning
> fix: adjust delegate call warnings

- src/logic/safe/store/actions/createTransaction.ts
Resolves #3355
When a user rejects a transaction, the `onlyConfirm` function throws and it was not returning. An on-chain transaction was then being attempted.
A created, but not immediately executed transaction now returns after an error is thrown.
1. Attempt to queue/confirm a transaction but reject it via MM.
2. Observe that no second MM popup is displayed.
> fix: return after rejecting an off-chain transaction

- src/components/AppLayout/Sidebar/DevTools/index.tsx
Resolves #3357
The transaction tab links and Safe status page links have been temporarily hidden, as well as the macro buttons adjusted to be inline with each other.
In the future we intend to show these links again and move the developer tools to a hideable pane on the right, or wherever seems best.
Open the Safe and observe, on a smaller resolution (13" MacBook), that the links are hidden and buttons are inline. The Sidebar should no hide entries, not showing a scrollbar.
> fix: hide developer tool links

- src/logic/hooks/useCanTxExecute.tsx
- src/logic/hooks/useEstimateTransactionGas.tsx
- src/routes/safe/components/Transactions/TxList/modals/ApproveTxModal.tsx
Resolves #3358
When approving a queued Transaction we only estimate gas when also executing it via checkbox.
1. Open a Multi Owner, 2+/n policy safe
2. Create a transaction without executing it
3. Switch to a different owner and confirm the queued transaction
> fix: Dont estimate gas in ApproveTxModal if checkbox is not checked

- src/routes/safe/components/Apps/components/AddAppForm/index.tsx
Resolves https://github.com/gnosis/safe-react-apps/issues/272
By changing the textfield from readOnly to disabled and tweaking some styles
Try to add a custom app and click in the safe app name field. Nothing should happen. The label remains in the same place and no animation is performed
Make the app fail for manifest not found. The label should be red and when you click nothing happens
> Change Safe App name TextField from readonly to disabled

- src/logic/exceptions/registry.ts
- src/logic/safe/store/actions/__tests__/fetchSafe.test.ts
- src/logic/wallets/getWeb3.ts
Removing logs when we cannot resolve ENS to have less noise in the console.
> Fix: don't log ENS errors

- src/routes/safe/components/Transactions/helpers/TxParametersDetail/index.tsx
Resolves #3061
More advanced parameters are now shown in the modals when they are present.
The order and render of them (whether they are `EthHashInfo` or copiable bytes) is based off of the 'Advanced Details' added to `TxSummary` a while back.
Expand the 'Advanced paramters' accordion on the transaction review modal and observe new parameters that correspond to the available information of the transaction.
> feat: add more advanced params to modals

- src/components/AppLayout/Sidebar/DevTools/index.tsx
Preventing queue macro spam.
The queue transaction macro function is now throttled. Clicking it invokes the macro but subsequent clicks don't.
- Click the queue transaction dev tool button and observe that it does not allow the creation of a transaction repeatedly.
> fix: throttle queue transaction macro

- src/components/SafeListSidebar/SafeList/SafeListItem.tsx
Auto-scroll in long sidebars.
The scrollbar no longer scrolls to the Safe when opening the sidebar. Instead, positioning the Safe in the middle of the sidebar.
- Open a Safe on a network with multiple Safes.
- Ensure that the sidebar has a scrollbar (requiring scrolling to position the loaded Safe in the middle of the sidebar).
- Close and open the sidebar, observing that no scrolling occurs. The sidebar opens with the Safe in the middle of the list (if it was either in the viewport before or out of view).
> fix: remove sidebar scroll behaviour

- src/components/AppLayout/Sidebar/index.tsx
Render flickering and Inspector tool inteference
The developer tools are memoized after being lazy loaded.
Observe the developer tools no longer flicker/source code change on poll.
> fix: memoize dev tools

- src/logic/safe/transactions/offchainSigner/index.ts
May solve #3388, but I couldn't reproduce the issue
Fixes error thrown while signing in brave (was reported internally in Slack) 
The error is only thrown when sending a native token. If you send ERC20 tokens, the error isn't thrown. There seems to be a problem with Brave wallet's EIP712 implementation.
When signing a transaction with brave wallet, if you try to sign with a non-supported signing method (`eth_signTypedData`), brave wallet throws a custom error that is not an instance of JS built-in `Error` class, but one of our error checkers expects error to be an instance of `Error` class
Test signing transactions in brave wallet, both tokens and native currency
> bug: signing fails in brave

- src/logic/wallets/getWeb3.ts
- src/routes/CreateSafePage/steps/NameNewSafeStep.tsx
- src/routes/CreateSafePage/steps/OwnersAndConfirmationsNewSafeStep.tsx
- src/routes/LoadSafePage/steps/LoadSafeAddressStep.tsx
After discussion we decided on keeping the TLD of the reverse ENS result when creating or loading a safe as it is more aligned with what users expect an ENS name to look like (with `.eth` at the end)
2. Create a new Safe with an owner that has a reverse ENS record
3. Load an existing Safe with an owner that has a reverse ENS record
4. Observe that the name placeholder is not shortened
> fix: Keep ENS TLD in safe creation and loading

- .github/workflows/lint.yml
Resolves https://github.com/gnosis/safe-apps-sdk/issues/276
As part of the [this ticket](v) we are updating the [safe-apps-sdk](https://github.com/gnosis/safe-apps-sdk) dependencies including the [gnosis/safe-react-eslint-plus-action](https://github.com/gnosis/safe-react-eslint-plus-action). These changes include a major `eslint` version bump from 7.x.x to 8.x.x. 
The list of affected Gnosis repos will be:
```
- https://github.com/gnosis/safe-react
- https://github.com/gnosis/safe-react-apps
- https://github.com/gnosis/safe-apps-sdk
- https://github.com/gnosis/safe-react-e2e-tests
- https://github.com/gnosis/safe-react-components
- https://github.com/gnosis/safe-react-gateway-sdk
- https://github.com/gnosis/safe-apps-dev-ui
```
ESLint 8 bring a [lot of …
> Update eslint action dependency

- src/routes/safe/components/Transactions/TxList/TxCollapsedActions.tsx
- src/routes/safe/components/Transactions/TxList/TxExpandedActions.tsx
Reverts the order of the  "Execute" and "Reject" buttons in the Collapsed Transaction as well as in the Expanded Transaction
Reverts the order of the buttons
1. Create a transaction that lands in the Queue.
2. Verify the buttons order
> fix: reverse the "Execute" and "Reject" buttons order

- src/routes/safe/components/Apps/components/ConfirmTxModal/ReviewConfirm.tsx
Resolves #3385
The recipient field wasn't passed to the estimation endpoint in the Safe App Tx Review modal.
* Create a tx with the Tx Builder
* Estimation should work
A cool trick learned from @DiogoSoaress: you can filter the network request by method like so:
```
-method:OPTIONS estimations
```
Minus means exclude.
> Fix: TxBuilder - pass txRecipient

- src/components/forms/validator.test.ts
- src/components/forms/validator.ts
- src/logic/hooks/useEstimateTransactionGas.tsx
- src/routes/safe/components/Transactions/helpers/EditTxParametersForm/index.tsx
- src/routes/safe/components/Transactions/helpers/EditableTxParameters.tsx
- src/theme/mui.ts
Resolves https://github.com/gnosis/safe-react/issues/3374
1. Restyles the forms input error label when introducing negative values
2. Shows a placeholder with the default value when `maxPrioFee` is left empty
1. Create a transaction
2. Edit the tx parameters
3. Set a negative value in one of the inputs and check the error label is not blocking the input anymore
4. Delete the "maxPrioFee" value and you shall see the 2.5 GWEI placeholder
> style: form input error label and maxPrioFee placeholder

- src/logic/safe/store/actions/createTransaction.ts
- src/logic/safe/store/actions/processTransaction.ts
- src/logic/safe/store/middleware/gatewayTransactionsMiddleware.ts
- src/logic/safe/store/middleware/notificationsMiddleware.ts
- src/logic/safe/store/reducer/pendingTransactions.ts
- src/logic/safe/store/selectors/pendingTransactions.ts
Resolves #3391
The `pendingTransactions` store now stores a hashmap for pending transactions as follows:
```ts
{
[chainId]: {
[txId]: true
}
}
```
All associated selectors and middlewares are updated to reflect this change, as well as an added pending status setter in `createTransaction` for immediately executed transactions on a 1/? Safe.
There should be no UI-noticeable changes.
All pending statuses should broadcast between tabs/windows, as well as reset (to awaiting) when a signing is rejected or (to successful) transaction succeeds.
- Create and immediately execute a transaction on a 1/? Safe. Observe that the transaction is pending.
- Queue a transaction on a X/? Safe. Upon executing, the execute/reject buttons should disappear in favour of the pending status.
- Rejecting this should …
> feat: track pending transactions by `txId`

- src/components/CookiesBanner/index.tsx
- src/utils/constants.ts
- src/utils/googleAnalytics.ts
- src/utils/googleTagManager.ts
Part of #3408 - cookie banner
The cookie banner now loads GTM instead of GA when the user accepts. GTM doesn't use cookies so no removal is required.
> fix: load GTM from cookie banner

- src/logic/hooks/useEstimateTransactionGas.tsx
Resolves #3412
It was a regression introduced in the [ApporveTxModal refactoring](https://github.com/gnosis/safe-react/pull/3369).
When estimating gas, it was always adding the current wallet address to the signatures list, even if full quorum had been reached.
It wasn't breaking anything for actual owners, but when a non-owner estimates a tx like this, it gets reverted with `GS026: Invalid owner provided`.
Strangely, such transactions would still execute fine.
Fixes a condition in `checkIfTxIsApproveAndExecution`.
* Create and fully sign a tx
* Try to execute with a non-owner
@francovenica we probably want to include a non-owner test in our read-only suite.
This bug had nothing to do with Trezor, btw.
> Fix: approve&execute conditions for non-owners

- src/routes/safe/components/Transactions/TxList/modals/RejectTxModal.tsx
Resolves #3423
The estimated fee dropdown is hidden when creating a Tx rejection by additionally checking `canTxExecute`. This change aligns with how `TxEstimatedFeesDetail` is handled for other transaction modals.
1. Open Safe App
2. Queue a Transaction
3. Reject the Transaction
4. Observe that the Estimated Fees dropdown is not displayed
~In single owner safes when the rejection is immediately executed `canTxExecute` is still false although it should be true.~
This is fixed in this PR, now passing `preApprovingOwner` to `canTxExecute` which then returns true in a single owner safe
> fix: Hide estimated fee dropdown when creating tx rejection

- src/routes/safe/components/Transactions/TxList/TxDetails.tsx
- src/routes/safe/components/Transactions/TxList/TxOwners.tsx
Resolves #3427
`TxOwners` is now always shown for `'MULTISIG'` transaction types and not dependant on confirmations.
- Create and immediately execute a transaction on a 1/? Safe.
- Observe the stepper now appearing
> fix: show stepper for immediate executions

- src/routes/safe/components/Transactions/TxList/modals/RejectTxModal.tsx
- src/routes/safe/components/Transactions/helpers/EditTxParametersForm/index.tsx
- src/routes/safe/components/Transactions/helpers/utils.tsx
- src/routes/safe/container/hooks/useTransactionParameters.ts
Resolves #3429 
Makes tx parameters editable for reject transactions and passes estimated values to the edit form instead of using 0 value fallback
1. Open a safe
2. Queue a transaction
3. Reject transaction
4. Observe that all parameters except the safe nonce are editable
5. Associated transactions/rejections should process without errors.
> fix: Make params editable when executing a reject transaction

- src/routes/safe/components/Transactions/TxList/ActionModal.tsx
- src/routes/safe/components/Transactions/TxList/modals/ApproveTxModal.tsx
- src/routes/safe/components/Transactions/TxList/modals/RejectTxModal.tsx
- src/routes/safe/components/Transactions/helpers/TxModalWrapper/index.tsx
Resolves #3429 
The previous PR #3434 didn't fully cover all cases when a reject tx modal should be editable. This PR refactors the `RejectTxModal` component to use `TxModalWrapper`. It slightly changes the existing UI when creating a reject tx in a 2+/x safe (see screenshot).
1. Open a safe
2. Queue a transaction
3. Reject the transaction
4. In case it can be immediately executed, observe that all parameters except the safe nonce are editable
5. In case it can't be immediately executed, observe that no paramters are visible
left: prod, right: current
> refactor: Use TxModalWrapper for RejectTxModal

- src/logic/wallets/ethTransactions.ts
Resolves down oracles
Gas price oracles that are down, namely Rinkeby (atm), do not throw when there is an issue but return a string. This was not breaking out of the oracle estimation loop we use.
The fetced gas price is first checked (`!isNaN()`), throwing if so, before returning it.
This is very hard to test because manually switching to another oracle in Django will likely throw. You would likely have to mock the response of an oracle, returning a string (that is not a number).
This is the error returned:
Hopefully this PR is reviewed whilst there is an Etherscan issue.
> fix: check that calculated gas price is a number

- src/components/AppLayout/Header/components/ProviderDetails/UserDetails.tsx
- src/components/AppLayout/Header/components/ProviderInfo/ProviderAccessible.tsx
- src/components/AppLayout/Header/index.tsx
- src/logic/wallets/store/selectors/index.ts
Resolves #3255
If present, adds a reverse ENS name to the connected wallet popup.
* Connect with an address that has a primary ENS name
* Connect with an address that doesn't
> Feature: display ENS name in connected wallet info

- src/routes/safe/components/Transactions/TxList/TxCollapsed.tsx
- src/routes/safe/components/Transactions/TxList/styled.tsx
Resolves #3443
The old on-chain rejection label styling was removed to keep it consistent across tthe app.
1. Create a transaction and corresponding on-chain rejection.
2. Observe that the on-chain rejection in the group has the usual transaction label style.
> style: remove inconsistent on-chain rejection label

- src/routes/safe/components/Balances/SendModal/screens/ModalHeader/index.tsx
- src/routes/safe/components/Transactions/TxList/TxOwners.tsx
Console errors related to Stepper and chain theming
Theme-related props are appended with `$`, preventing them from being passed to the DOM.
Interface with the Stepper and observe no errors in the console.
> fix: don't pass theming props to DOM

- src/routes/safe/components/Transactions/TxList/SpendingLimitDetails.tsx
Resolves #3456
Aligns the font size with the other SpendingLimitDetail title size
Open a DeleteAllowance transaction in the TxList and assert that the font size is as per designs https://www.figma.com/file/47wkjxMZkyEeCRbCrLJBJa/safe%232995-Tx-details?node-id=387%3A21816
> style: increase SpendingLimitDetails title font size

- src/components/AppLayout/Sidebar/SafeHeader/index.tsx
Resolves #3458
The Safe-specific sidebar is only shown when a Safe address exists in the URL. (The 'loaded' Safe remains in the store so it is necessary to use the URL as a flag as well).
1. Open a Safe.
2. Click the Safe logo.
3. Observe that the Safe-specific sidebar is no longer visible.
> fix: only show safe sidebar on open Safes

- src/components/forms/validator.ts
- src/logic/wallets/getWeb3.ts
- src/routes/CreateSafePage/CreateSafePage.test.tsx
- src/routes/CreateSafePage/CreateSafePage.tsx
- src/routes/CreateSafePage/steps/NameNewSafeStep.tsx
- src/routes/CreateSafePage/steps/OwnersAndConfirmationsNewSafeStep.tsx
Resolves #3459
The address being looked up is now checksummed before being compared to the verified (checksummed) address, allowing it to pass validation.
Note: the error message regarding repeated multiple of the same owner was adjusted.
1. Open Safe creation whilst connected to an EOA with an ENS domain
2. Progress to the owner step and observe that the ENS name has been resolved
> fix: lookup ENS domains when intialising form

- src/logic/hooks/useCanTxExecute.tsx
- src/routes/safe/components/Transactions/helpers/TxModalWrapper/index.tsx
Resolves #3457 
Changes `useCanTxExecute` to return `false` if current transaction nonce is out of order
1. Open a 2+/n safe
2. Queue a transaction
3. Queue a second transaction
4. Switch wallet
5. Try to Confirm the second transaction
6. Observe that it can not be executed
> fix: Disable tx execution for out of order nonce txs

- src/components/forms/AddressInput/index.tsx
- src/logic/wallets/onboard.ts
- src/logic/wallets/store/reducer/index.ts
- src/routes/CreateSafePage/CreateSafePage.tsx
- src/routes/CreateSafePage/steps/OwnersAndConfirmationsNewSafeStep.tsx
Resolves #3460
The 'Owners and Confirmations' step validation was being overwritten by field-level `onChange` validation. Field-specific validation is now added on a per-field basis, appending it to the `composeValidators`.
1. Open Safe creation.
2. Progress to 'Owners and Confirmations' step.
3. Attempt to add the same owner (with/without EIP-3770 prefix) and observe the duplicate owner error.
> fix: use field-level owner validation

- src/routes/index.tsx
- src/utils/googleTagManager.ts
Part of https://github.com/gnosis/safe-react/issues/3408 - anonymous tracking
As with GA was, the URL is now anonymised for GTM. It is possible to implement RegEx replacement on the GTM-side, but a history listener is used instead so that no safe addresses or transaction ids are even sent to GTM in the first place
- Safe addresses are replaced with `"SAFE_ADDRESS"`
- Transaction ids are replaced with `"TRANSACTION_ID"`
Open GTM preview and observe that, when navigating between pages, the safe address and any deeplinked transaction ids are replaced.
> fix: migrate anonymous page tracking to GTM

- src/routes/safe/components/Transactions/TxList/TxOwners.tsx
Incorrect confirmation details on immediately executed transactions
The user account details are not shown at the confirmer on transactions that are created and executed immediately.
We do not receive details of the confirmations/executor from backend when immediate execution occurs. This instance renders a 'mimicked' Stepper and the Safe name was being shown as the confirmer, not the current user.
- Create and immediately execute a transaction on a 1/? Safe
- Observe that the confirmations (1) is that of the current user w/ name, not the Safe
> fix: show user as confirmer for immediately executed transactions

- src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/utils/index.ts
- src/routes/safe/components/Transactions/TxList/MethodValue.tsx
Resolves #3468
Handles multidimensional method param values
Open app/avax:0x2ABC32Fcf8584Aba161b33133af55cD3f94Ba288/transactions/0xb249327fea1885798f2ffca88aa31bd4e9a4d35f66aa57e58bf3cf25af4c239c and you shall see all the values well represented without the application crashing
> fix: deal with nested arrays param values

- src/logic/wallets/__tests__/getWeb3.test.ts
- src/logic/wallets/getWeb3.ts
Resolves #3435
`isSmartContractWallet` now checks via the readonly `web3` object instead of that from the provider. Using the standard `getWeb3()` object, returned from the provider, was causing `web3` interaction in the case of `,eth.getCode()` to hang when using the `https://rpc.xdaichain.com/oe-only/` RPC.
This fix facilitates switching back to the OE RPC for Gnosis Chain instead. This fixes the gas estimation issue. The `isSmartContractWallet()` tweak fixes the WalletConnect issue which made us migrate RPC in the first place.
- Use the temporary Gnosis Chain on the staging CGW (it has a different RPC than on prod.)
- Test that estimations do not fail on < 1.3.0 Safes on Gnosis Chain
- Test that Safe-Safe WC works, setting the `smartContractWallet` flag correctly in the `providers` …
> fix: `getCode` via readonly web3 object

- src/routes/safe/components/Transactions/helpers/EditTxParametersForm/index.tsx
Resolves #3464 
Extends the form validation to compare `ethMaxPrioFee` against `ethGasPrice`.
1. Open the safe
2. Create a pre EIP-1559 transaction
3. Change `Max fee per gas` and observe that the form can be saved
4. Create a post EIP-1559 transaction
5. Change `Max priority fee per gas` to be higher than `Max fee per gas`
6. Observe that there is a validation error
> fix: Add form validation for max priority fee

- src/routes/safe/components/Transactions/TxList/styled.tsx
Resolves #3509
Removes style that was suppressing row-gap in the last MUI accordion for no apparent reason
Open a transaction deeplink view and the layout shall not be cramped anymore.
> style: remove row-gap overwritting style in MuiAccordion

- src/components/TransactionFailText/index.test.tsx
- src/components/TransactionFailText/index.tsx
Resolves #3519
Adds a condition to not render the error if neither an execution nor an unauthorized creation.
Follow the steps in the linked issue.
> Fix: error message on confirmation

- package.json
- src/components/Track/__tests__/index.test.tsx
- src/components/Track/index.tsx
Missing chain-specific details
As per @johannesmoormann's request, the `shortName` (more stable than `chainName`) and `chainId` are sent with every track to GTM. I added them in a separate tracking key `data-track-chain` so they can be separated from the track as/when we want, e.g.
```ts
{
id: 'Add owner',
chain: {
shortName: 'rin',
chainId: 4,
},
payload: {
total: 4,
threshold: 2
}
}
```
```ts
{
id: 'Add owner',
chain: {
shortName: 'eth',
chainId: 1,
},
payload: {
total: 4,
threshold: 2
}
}
```
With the above we can track the 'Add owner' event and decide whether to track the total events or also by chain, simply by not including the `data-track-chain` payload into the analytics
It is currently covered by unit tests. Testing to occur when the first set of tracking is implemented. …
> fix: add chain data to tracking

- .github/workflows/release-mainnet-desktop.yml
- package.json
- src/config/index.ts
- src/logic/safe/api/fetchSafeApps.ts
- src/logic/wallets/utils/walletList.ts
- src/routes/safe/components/Apps/components/AppCard/index.stories.tsx
- src/routes/safe/components/Apps/components/AppsList.test.tsx
- src/routes/safe/components/Apps/utils.ts
- yarn.lock
Resolves #3379 
Cherry-picks #2672 
It turned out that we don't need a migration script, but we had to change `productName` in package.json to match the old name, so it uses the same cache folder
1. Download app 3.8.4 from https://gnosis-safe.io
2. Load safes, add things to address book, etc
3. Build a new app from this PR:
```
yarn build-desktop && yarn electron-build
```
4. Install it from `dist` folder and check that all the content from an old app is there
Do I merge it to the `electron` branch or we should create a new one for the release?
> Feature: desktop localstorage migration

- src/logic/safe/hooks/useLocalSafes.tsx
- src/routes/safe/components/Settings/RemoveSafeModal/index.tsx
Resolves #3031 
Similar to how its handled on mobile, when deleting the current safe the user gets redirected to:
- The next available safe on the same network OR
- The next available safe on another network OR
- The welcome page
Could opening another safe automatically impact UX in a negative way? cc @liliiaorlenko 
2. Go to Settings > Safe Details
3. Click Remove Safe
4. Observe redirection for different cases in the order described above
> fix: Redirect user to next available safe after removing current safe

- src/logic/wallets/getWeb3.ts
- src/routes/CreateSafePage/steps/NameNewSafeStep.tsx
Resolves #3507
Just a quick fix that checks that the address isn't undefined.
I couldn't reproduce the error from Sentry. We actually don't allow empty addresses.
But this should fix it.
Try creating a Safe with several owners, some of which are ENS owners.
> Fix: undefined address in reverse ENS lookup

- src/components/AppLayout/Sidebar/index.tsx
- src/components/CookiesBanner/index.tsx
- src/logic/cookies/model/cookie.ts
- src/logic/cookies/store/actions/openCookieBanner.ts
- src/logic/cookies/store/reducer/cookies.ts
- src/logic/cookies/store/selectors/index.ts
- src/store/index.ts
Resolves #3473
Adds Beamer cookies under the analytics category.
Displays a warning on trying to open the Beamer drawer without the cookies consent.
Open the Cookies preferences in the Welcome Page footer and toggle the "Analytics"
- If "Analytics" cookies accepted, the sidebar "What's New" button will open the Beamer drawer
- If "Analytics" cookies is not accepted, the sidebar "What's New" button will prompt the Cookies Banner
> feat: Cookies and privacy policy

- src/routes/safe/components/Settings/index.tsx
Resolves #3532
Settings routes that do not exist in our Router redirect to the default settings path.
Open `/app/{{safeAddress}}/settings` and observe it redirect to the settings details.
> fix: add redirection for settings section

- src/components/ExecuteCheckbox/index.tsx
- src/routes/safe/components/Transactions/helpers/TxModalWrapper/index.tsx
Resolves #3539 
We now also pass the state itself to the checkbox component instead of just the setter so it stays in sync.
1. Open the Safe
2. Create a Transaction
3. Uncheck the Execute Tx Checkbox
4. Go to the Edit Parameters screen
5. Go back
6. Observe that Advanced Details is still hidden and the checkbox is still unchecked
> fix: Link execute tx checkbox state to parent component

- src/logic/safe/store/actions/__tests__/TxSender.test.ts
- src/logic/safe/store/actions/createTransaction.ts
- src/logic/safe/store/actions/utils.ts
Part of #3494 
Tests `TxSender` class for each transaction flow: `approve transaction`, `create transaction`, `create and execute transaction`, `execute transaction/approve and execute transaction`. This is an important prerequisite for the upcoming v2 refactor as discussed [here](https://github.com/gnosis/safe-react/pull/3492#issuecomment-1041269479).
`navigateToTx` got moved to a different file for mocking purposes.
> test: Create tests for TxSender class

- src/components/ExecuteCheckbox/index.test.tsx
- src/components/ExecuteCheckbox/index.tsx
Relates to #3539 
Removes the `defaultChecked` attribute as it conflicts with using the Checkbox as a controlled input.
Behaviour is still the same, only the console error is gone now.
> fix: Remove defaultChecked attribute from exec tx checkbox

- src/routes/routes.ts
`replaceAll` errors on Chrome Android.
`replaceAll` has been exchanged with the legacy global `replace`.
Open an example `chainName` 'root route' on Chrome Android, e.g. `/app/gnosis-chain` and observe that the Safe opens correctly.
> fix: use global `replace` instead of `replaceAll`

- src/logic/safe/store/actions/__tests__/TxSender.test.ts
- src/logic/safe/store/actions/createTransaction.ts
Dima noticed the following bug:
* connect the mobile app via WalletConnect
* initiate a transaction on web (Execute checkbox unchecked)
* reject on mobile
* before the fix: web app redirects to the tx with 0 signatures 🐞
Another bug this PR fixes:
* make a Safe an owner of another Safe
* connect the first Safe to the owned safe via WC and WC Safe App
* create a tx (Execute unchecked)
* before the fix: tx created with 0 signatures 🐞 
After this fix, a tx will be signed correctly in both cases.
When a created tx is rejected by the wallet, we throw an error and show an error snackbar. The tx is _not_ created and the user is _not_ redirected anywhere.
Also checks if the connected wallet is a smart contract and does an on-chain signature if yes.
> Fix: throw when WC rejects a created tx + on-chain signing with a Safe signer via WC

- src/routes/CreateSafePage/components/SafeCreationProcess.tsx
- src/routes/opening/index.tsx
Resolves #3498 (partially)
When calling `createNewSafe` we only proceed with the Tx proposal if the users wallet is connected.
2. Create a new Safe
3. Reject the Transaction via MetaMask
4. Reload the page
5. Observe that MetaMask opens again
6. Observe that there is no error and the Retry button is not visible
Before - After
> fix: Only run createNewSafe if user wallet is connected

- src/components/DecodeTxs/index.tsx
Resolves #3502
An array parameter value is always stringified when processing a transaction. 
When receiving decoded data from the back-end while creating a transaction, decoded data parameters are of type
`DecodedDataBasicParameter` which types the parameter value as a `string`.
1. Propose a transaction that contains a nested array as a parameter (e.g. claiming a merkle airdrop, such as vCOW)
2. Check that nested array is displayed
> fix: stringify parameter value arrays

- src/logic/wallets/pairing/module.ts
Resolves outdated pairing QR upon connection rejection.
`onDisconnect` was only being called when the provider was connected. If the user rejects a pairing request, the provider was `!connected` and would therefore not reset the wallet, invalidating the QR code. The `connected` flag has been removed.
- Scan the pairing QR in the mobile app but reject the pairing request.
- Observe the QR disappear, requesting regeneration.
> fix: always reset wallet on `disconnect` event

- src/routes/opening/index.tsx
Part of #3569
While testing the creation a Safe on Polygon, I've noticed that an error was thrown in the creation tx monitor.
Checks for null/undefined.
It's not happening consistently.
> Fix: safe creation monitor - receipt can be undefined

- src/logic/config/store/middleware/index.ts
- src/logic/config/utils/index.ts
Updating Onboard's `appNetworkId` on setting the `chainId`.
Updating the config on Onboard is now done in the middleware as it is a side-effect.
- Pair on a network
- Change to another network via the Web UI
- Execute a transaction successfully
> fix: move Onboard config setting to middleware

- src/components/ReviewInfoText/ReviewInfoText.test.tsx
- src/components/ReviewInfoText/index.tsx
- src/routes/safe/components/Transactions/helpers/TxModalWrapper/index.tsx
Resolves #3568
Passes a new prop for rejection txns.
Create a few txns with out-of-order nonces. Reject them.
> Fix: do not show a nonce warning for rejection txns

- src/logic/config/store/middleware/index.ts
- src/logic/wallets/onboard.ts
Provider with outdated `chainId`
The cross-chain persistence of Onboard has been reverted to how it was prior to desktop pairing.
Original change here: https://github.com/gnosis/safe-react/pull/3354/commits/2a179d450437550c8acef792e129965b2c194cf4
- Connect a wallet
- Switch network and observe that you will need to reconnect the wallet
> fix: revert cross-chain Onboard persistence

- src/components/AppLayout/Header/components/Layout.tsx
- src/logic/wallets/pairing/hooks/usePairing.ts
Early pairing initialisation
The wallet popper only renders when the `open` flag is `true` and the pairing module does not reset the wallet when unmounting.
Load Safe and observe that the 'Mobile Safe' wallet is not immediately saved as a provider.
> fix: init pairing w/ popper + don't reset on unmount

- src/logic/wallets/ethTransactions.ts
Resolves #3564 
Use `web3ReadyOnly` to fetch the current connected wallet nonce instead of using `web3`
1. Open the Safe app on release/3.20.0
2. Connect web and mobile
3. Try to execute Txs on different networks with the same connected key
4. Open estimation details before execution on each network 
5. Observe that the nonce shown is the same as the wallet nonce
> fix: Use web3readonly to get the nonce of currently connected wallet

- src/routes/opening/index.tsx
Following up on #3573, a few more guards to prevent uncaught exceptions in the tx monitor.
> Fix: prevent exceptions in tx monitor

- src/logic/wallets/pairing/module.ts
Remove pairing URI logging.
- Open wallet popper and display QR code for pairing.
- Observe correctly formed QR code but no console log of the URI.
> fix: don't log pairing uri

- src/logic/safe/store/actions/createTransaction.ts
- src/logic/wallets/getWeb3.ts
- src/logic/wallets/onboard.ts
- src/logic/wallets/store/actions/index.ts
- src/logic/wallets/store/actions/updateProviderSmartContract.ts
- src/logic/wallets/store/middleware/index.ts
- src/logic/wallets/store/reducer/index.ts
- src/logic/wallets/utils/network.ts
- src/routes/CreateSafePage/steps/SelectWalletAndNetworkStep.tsx
Resolves #3581 
Checking whether the connected wallet is a smart contract now occurs in the middleware as a side effect.
Originally, the flag was checked against Onboard's internal state (when the wallet subscription was fired). This was causing it to recurse with the 'old' `chainId` when switching network. It no longer references it's internal state.
- The wallet subscription is often fired first, with an empty address state, meaning that `smartContractWallet` would always be `false`.
- A race condition was occuring because the `isSmartContractWallet` is asynchronous. The payload containing the flag, checked from the address, would be dispatched **after** the reset wallet.
- Pair with the Safe and switch network, observing that no 'invalid topic' error is thrown.
- Connect a normal …
> fix: pairing invalid topic

- src/routes/safe/components/Transactions/TxList/styled.tsx
Resolves #3552
- Changes the Disclaimer background color on hover
- Removes the grey scale filter in transactions that will be replaced
1. Stack transactions with the same nonce.
2. Get one of the grouped transactions ready to be executed.
3. On hovering the "execute" icon/button, the other transaction will not
(_on hover_)
> style: improve conflicting transactions styles

- src/logic/notifications/notificationBuilder.tsx
- src/logic/safe/store/actions/createTransaction.ts
- src/logic/safe/transactions/offchainSigner/index.ts
- src/logic/wallets/errors.ts
Resolves #3563
We were actually never showing any error on rejection, but this PR fixes it.
A snackbar saying "Transaction was rejected" is shown now when rejecting execution/signing in the wallet.
Only works for MM, WC and Keystone (we parse their specific errors).
Create & reject.
> Fix: show a tx rejection error

- src/components/AppLayout/Header/components/ProviderDetails/PairingDetails.tsx
- src/logic/wallets/onboard.ts
- src/logic/wallets/pairing/hooks/useGetPairingUri.ts
- src/logic/wallets/pairing/utils.ts
Resolves #3589 
The QR Code uri is now saved and updated within the `PairingDetails` component state whenever the uri from the onboard instance changes. This triggers necessary rerenders in order to display the correct QR Code.
2. Connect to the safe by scanning the QR Code
3. Press Reject on your phone
4. Refresh the QR Code
5. Observe that the new QR code can be used again
> fix: Save and update QR Code uri in component state

- src/logic/wallets/onboard.ts
- src/logic/wallets/pairing/utils.ts
Resolves #3589 
Reverting back to use `onboard()` in order to get the onboard instance.
2. Press on Connect Wallet
3. Observe that it doesn't crash
> fix: Revert back to using onboard() in order to get the onboard instance

- src/components/AppLayout/Header/components/ProviderDetails/ConnectDetails.tsx
- src/components/AppLayout/Header/index.tsx
- src/logic/wallets/utils/walletList.ts
Relates to #3589 
- Before trying to load the last used provider we now also check that it is still enabled in our config
- Lazy import `PairingModule` because it imports static css to hide the first result in the onboard window which is MetaMask in case the pairing module is disabled
1. Open the Safe app with dev CGW
2. Connect to the safe via mobile app
3. Disconnect
4. Switch to prod CGW
5. Try to connect via MetaMask
6. Observe that App doesn't crash
7. Observe that the onboard popup doesn't automatically open
> fix: Check that last used provider is enabled before loading it

- src/logic/wallets/utils/walletList.ts
Broken wallet support
If a wallet is unsupported they are filtered out of the `getSupportedWallets`. They are further filtered depending on whether the build environment is the desktop/web app.
Open the Onboard modal and observe that the supported wallets match that of the CGW.
> fix: supported wallets

- src/logic/hooks/useEstimateSafeCreationGas.tsx
Resolves #3586 
- Version [1.7.0](https://github.com/ChainSafe/web3.js/releases/tag/v1.7.0) of web3.js changed the first parameter type for `getFeeHistory` from `number` to `hex`. Using `number` type with the Gnosischain RPC caused errors.
- We also check that the network supports EIP-1559 before fetching `getFeeHistory` in `useEstimateSafeCreationGas`. This is in line with our implementation in `useEstimateTransactionGas`
1. Open a Safe on Gnosischain
2. Create a transaction
3. Observe that the fee estimation works
~Only use `getFeeHistory` on networks that support it. There seems to be an error when creating a Safe on Arbitrum~
> chore: Bump web3 version to 1.7.0

- src/components/CookiesBanner/index.tsx
- src/logic/cookies/utils/index.ts
- src/utils/beamer.ts
- src/utils/googleAnalytics.ts
Resolves #3608 
When withdrawing consent for _Community Support & Updates_ cookies all `_BEAMER` cookies are deleted
2. Accept all cookies
3. Observe `_BEAMER` cookies being added
4. Open Cookie Preferences
5. Uncheck _Community Support & Updates_ and save
6. Reload the page
7. Observe `_BEAMER` cookies not existing anymore
> fix: Remove Beamer cookies on consent withdraw

- .github/workflows/mint.yml
Instead of triggering the action on each PR, we'll be manually launching it via the GitHub UI and pasting a target PR number.
> Chore: change the NFT action to a manual trigger

- src/config/chain.d.ts
- src/logic/wallets/onboard.ts
- src/logic/wallets/utils/walletList.ts
Resolves #3607
Onboard now has the option of using a detected wallet.
- Install the frame.sh browser extension
- Open the onboard modal and see the option of connecting to Frame wallet
> fix: enable detected wallet

- src/components/ReviewInfoText/ReviewInfoText.test.tsx
- src/components/ReviewInfoText/index.tsx
Resolves #3616
When submitting a transaction with a nonce lower than the queue but higher than that of the Safe, the warning does not signify failure of the transaction.
- Create and queue a transaction 2 nonces higher than that of the Safe nonce.
- Create a transaction but edit the nonce to be 1 higher than that of the Safe nonce.
- Observe the new warning message
> fix: clarify nonce warning

- src/config/chain.d.ts
- src/logic/wallets/utils/walletList.ts
This reverts commit d68693497a452bb8efc4f7917cbb8aff3cf2abf7.
Resolves #3607
Onboard no longer detects injected wallets.
This was added in favour of 'fixing' Frame support but it didn't work. There does not seem to be any historical implementation of it either and in an effort to avoid future bugs, it will be reverted.
Open the Onboard modal and observe that "Detected Wallet" is no longer shown.
> Revert "fix: enable detected wallet (#3612)"

- src/components/AppLayout/Header/components/ProviderDetails/ConnectDetails.tsx
- src/components/AppLayout/Header/components/ProviderDetails/PairingDetails.tsx
- src/components/AppLayout/Header/components/ProviderDetails/hidePairingModule.css
- src/components/AppLayout/Header/index.tsx
Resolves #3624 
Instead of normally importing the css within `PairingDetails` and leaving it there we now import it on mount and remove it once the component unmounts.
`wrapInSuspense` was moved closer to the component that required it (`PairingDetails`)
2. Connect to a network that has mobile pairing enabled
3. Click "Connect Wallet
4. Switch to a network that has mobile pairing disabled e.g. Gnosis Chain
5. Click on "Connect Wallet" > "Connect"
6. Observe that MetaMask (first wallet) is visible
> fix: Only hide first wallet if mobile pairing is enabled

- src/logic/safe/store/selectors/index.ts
Resolves #3565 
When switching networks, the `currentSafe` selector didn't get an up-to-date safe address sometimes but instead used a cached value. Moving the `extractSafeAddress` call to the selector arguments solves this issue.
1. Open the safe app
2. Switch to safes in different networks so that they are saved in localStorage
3. Connect with mobile pairing
4. Switch to other networks
5. Observe that the last used safe of those networks is correctly loaded and visible in the sidebar
6. Observe that there is no Safe loading error visible
> fix: Extract safe address when using currentSafe selector

- src/components/AppLayout/index.tsx
Relates to https://github.com/gnosis/safe-react/pull/3620#issuecomment-1062134989
Changes the sidebar so it doesn't shrink and keeps its fixed width of 200px at all times
1. Open the safe app
2. Change the viewport to a lower width
3. Observe that the sidebar width doesn't change
> fix: Don't shrink sidebar on smaller screens

- src/components/CookiesBanner/index.tsx
Resolves #3638
The openBanner callback receives a key to set an alert message.
Open a Incognito window. The Cookie banner shall display initially without any warning
> fix: pass alert key to the openBanner callback

- src/components/AppLayout/Header/components/ProviderDetails/PairingDetails.tsx
- src/components/AppLayout/Header/components/ProviderDetails/hidePairingModule.css
> chore: Always hide first wallet if mobile pairing is enabled

- src/logic/safe/store/middleware/pendingTransactionsMiddleware.ts
- src/logic/safe/transactions/__tests__/pendingTxMonitor.test.ts
Deploy issue on `dev` branch
The `PROVIDER_ACTIONS` enum value was updated and the type fixed in a test.
> fix: provider actions

- src/routes/safe/components/Settings/Appearance/index.tsx
Resolves #
A typo in the Settings page accross -> across
> Fix typo in Settings Component

- package.json
- src/logic/collectibles/sources/Gnosis.ts
- src/routes/safe/components/Transactions/TxList/TokenTransferAmount.tsx
- src/routes/safe/components/Transactions/TxList/TxInfoDetails.tsx
- src/routes/safe/components/Transactions/TxList/hooks/useAssetInfo.ts
- src/routes/safe/components/Transactions/TxList/modals/ApproveTxModal.tsx
- src/routes/safe/components/Transactions/TxList/utils.ts
- src/setupTests.js
- src/test/utils/safeHelper.ts
- yarn.lock
Build issues with latest SDK types
Wherever `TokenType` was being used, relative to transactions, `TransactionTokenType` is not being used in accordance with the following: https://github.com/gnosis/safe-react-gateway-sdk/pull/62
> The client gateway returns NATIVE_TOKEN for TokenType enum and Transaction type uses NATIVE_COIN to define native chain token.
> fix: migrate to `TransactionTokenType` type

- src/components/CookiesBanner/index.tsx
- src/utils/beamer.ts
- src/utils/googleAnalytics.ts
Resolves #3652 
We split the logic for loading and unloading Beamer. While we load Beamer both on user interaction with the cookie banner and page reload, unloading it (deleting cookies) only happens on user interaction now.
Since the logic was the same for Google Analytics, I included it in this fix.
2. Accept all cookies
3. Observe that "Whats new" has a green dot next to it
4. Click on "Whats new"
5. Reload the page
6. Observe that Beamer cookies / localStorage are not deleted/reset
7. Observe that "Whats new" doesn't have a green dot anymore
> fix: Delete Beamer cookies only if it was previously loaded

- src/components/AppLayout/Header/components/ProviderDetails/ConnectDetails.tsx
- src/components/AppLayout/Header/components/ProviderDetails/HidePairingModule.tsx
- src/components/AppLayout/Header/components/ProviderDetails/PairingDetails.tsx
- src/components/AppLayout/Header/components/ProviderDetails/hidePairingModule.css
- src/components/AppLayout/Header/index.tsx
Resolves #3624 
Instead of including the css for hiding the first wallet within `PairingDetails` it is now included within the `Header` component that always exists.
2. Navigate to Create Safe
3. Click on Connect
4. Observe that "Safe Mobile" Link is not visible
5. Click on Connect Wallet > Connect in the Header
6. Observe that "Safe Mobile" Link is not visible
> fix: Hide first wallet in onboard modal if mobile pairing is enabled

- src/logic/collectibles/sources/Gnosis.ts
- src/routes/safe/components/Transactions/TxList/TokenTransferAmount.tsx
- src/setupTests.js
Comments made by @dasanra (https://github.com/gnosis/safe-react/pull/3640)
Assets now use `TokenType` instead of the transaction-specific type.
> fix: asset types

- package.json
- src/routes/safe/components/Apps/components/AppFrame.tsx
- yarn.lock
Resolves https://github.com/gnosis/safe-apps-sdk/issues/301, resolves https://github.com/gnosis/safe-react-apps/issues/374
We are doing 2 different things here:
1) Adding a new method `getCommunicationInfo()` used by returning some info about the communicator. By now we are returning the origin as we need it in the walletConnect app and is difficult to get it inside an iframe (Current approach `ancestorOrigins` is not supported on Firefox
2) We are including a new property `isReadOnly` on the SafeInfo object allowing as to know safe apps if the safe-web is on READ-ONLY mode
> feat: Add getCommunicationInfo method and new prop to SafeInfo

- src/theme/mui.ts
Resolves #3664
The `letterSpacing` has been removed.
Observe non-truncated addresses in address input fields.
> fix: remove `letterSpacing`

- src/components/forms/TextField/index.tsx
- src/routes/CreateSafePage/steps/OwnersAndConfirmationsNewSafeStep.tsx
- src/routes/LoadSafePage/steps/LoadSafeOwnersStep.tsx
Resolves #3662
Whenever a placeholder exists, the label is shrunk.
Observe shrunken labels in fields that have placeholders.
> fix: shrink input label when placeholder exists

- src/routes/safe/components/Apps/hooks/useIframeMessageHandler.ts
- src/routes/safe/components/Apps/hooks/useThirdPartyCookies.ts
Resolves https://github.com/gnosis/safe-react-apps/issues/383
By adding a condition  to not show the message when the origin is the iframe validating the third party cookies activation
1) Third party cookies warning should continue to work as before
2) ThirdPartyApp message should not be present in the console
> fix: Avoid showing ThirdPartyApp message for the cookies warning flow

- package.json
- yarn.lock
Update the `safe-react-components` dependency to make use of new theme background color.
Figma: https://www.figma.com/file/3EUA9pvjt0P5xNLKOzbbEJ/Visual-segregation-for-Tx?node-id=1%3A119
> chore: bump safe-react-components version

- src/logic/wallets/walletConnect/utils.ts
Resolves #3581
WC only disconnects if a `peerId` is present (a successful connection occurred).
1. Open the WC modal on a network and then close it without scanning the QR code.
2. Switch network and open the modal again.
3. Observe no "Missing or invalid topic" error message in the console.
> fix: only disconnect WC when a `peerId` exists

- src/routes/safe/components/Apps/__tests__/utils.test.ts
- src/routes/safe/components/Apps/components/AppFrame.tsx
- src/routes/safe/components/Apps/utils.ts
resolves https://github.com/gnosis/safe-react-apps/issues/313
We are making `description` and `iconPath`  properties optional.
Besides that we are adding support for the `icons` web manifest standard prop as some apps are going this way and is the real standard (For example Sushi as the related bug stands out)
1) Access Sushi app
1.1) Create a transaction by making a swap
1.2) Icon and name should be visible
1.3) If the manifest has some missing prop (As Sushi) then a console.error message should be showed
2) Add a new Custom apps with the [new manifest structure](https://github.com/gnosis/safe-react-apps/pull/388) using icons property. The apps should be added with no issue
3) Add a new Custom apps with the current manifest structure. The apps should be added with no issue
4) Add custom …
> feat: Change manifest.json requirements for Safe Apps

- src/logic/safe/store/actions/createTransaction.ts
- src/logic/safe/store/actions/transactions/utils/transactionHelpers.ts
- src/logic/safe/transactions/__tests__/pendingTxMonitor.test.ts
- src/logic/safe/transactions/pendingTxMonitor.ts
Pending statuses pesisting upon transaction failure
When a transaction reverts ([`receipt.status === false`](https://web3js.readthedocs.io/en/v1.2.11/web3-eth.html#eth-gettransactionreceipt-return)), it's pending status is cleared.
In the `TxSender` the `txId` is saved after proposal as it is used as refrence to clear the pending status. A reverted transaction throws instead of the `promiEvent` returning the receipt.
1. Create an execute a transaction that would revert and observe the pending status clear upon reversion
2. Create an execute a transaction with a low gas limit then refresh (to initiate the pending watch). Observe the pending status also clear.
> fix: clear pending status when transaction reverts

- src/logic/safe/transactions/__tests__/pendingTxMonitor.test.ts
Remove `only` flag from test.
The pending watcher alterations were merged with an `only`-flagged test file. This has been removed.
The unit tests should still pass.
> fix: remove `only` from test

- src/components/ExecuteCheckbox/index.tsx
- src/components/SafeListSidebar/SafeList/index.tsx
- src/components/Track/index.tsx
- src/logic/safe/hooks/useLocalSafes.tsx
- src/routes/safe/components/Balances/Collectibles/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/ReviewSendFundsTx/index.tsx
- src/routes/safe/components/Transactions/TxList/QueueTransactions.tsx
- src/utils/events/modals.ts
- src/utils/googleTagManager.ts
@francovenica noticed some inconsistencies in a few events. These have been fixed/tweaked and the GTM-GA link removed on dev. environments.
It is possible to have production only triggers in GA but they cost with every event. Instead, the triggers have been adjusted to fire when the built-in debug mode variable (`true` by default in the development environment) is `false`.
The following events were tweaked:
Preview the local branch/PR in GTM and observe no GA tags firing in GTM.
1. Repeatedly click on a transaction tab and observe only one `'pageview'` event.
2. (Un-)check the "Execute transaction" checkbox and observe a new `'cusomClick'` event.
3. Pay for a transaction from a spending limit and observe a new `'metadata'` event.
4. Open the sidebar and observe a `'metadata'` event for …
> fix: tweak events + don't trigger GA on dev

- src/logic/safe/store/actions/__tests__/TxSender.test.ts
- src/logic/safe/store/actions/createTransaction.ts
- src/logic/safe/store/actions/pendingTransactions.ts
- src/logic/safe/store/reducer/pendingTransactions.ts
- src/logic/safe/transactions/__tests__/pendingTxMonitor.test.ts
- src/logic/safe/transactions/pendingTxMonitor.ts
Slow clearance of pending transactions
Instead of the pending watcher waiting for the current block + 50 to clear an (unsuccessful) pending transaction upon wallet connection, the block number upon executing a transaction is cached. The watcher now waits for cached block number (if it exists) + 50 instead. It falls back to the current block number if the original block number retrieval failed.
1. Create a queued transaction.
2. Execute the transaction with a very low gas limit.
3. Cancel the transaction with a high gas limit and immediately refresh.
4. The transaction should clear exactly 50 blocks post `block` stored under the transaction `id` in the store.
> fix: cache block of pending transaction

- src/components/AppLayout/index.tsx
- src/components/AppstoreButton/index.tsx
Resolves #3712
The footer is only visible on the welcome and settings routes.
Open the welcome/settings routes and observe the footer. On others it should not be visible.
No analytics implementation is necessary. There is an App Store campaign in place that tracks the user interaction for us.
> fix: only show footer in welcome and settings

- src/logic/wallets/onboard.ts
- src/logic/wallets/store/middleware/index.ts
Resolves #3722
`setWeb3` and the instantiation of contracts has been moved to the provider middleware (as well as `resetWeb3`).
As we enable the pairing module on load, onboard's wallet subscription fires by default, meaning that the `updateProviderWallet` action is fired. Within that subscription we were saving the provider: a WalletConnect session that isn't connected (the QR code not scanned). This was causing issues retrieving the spending limit contract and preventing the Safe from loading.
Open a Safe with the spending limit module enabled (e.g. `/app/eth:0xfF501B324DC6d78dC9F983f140B9211c3EdB4dc7/balances`) and the wallet disconnected. The Safe should load without issues: balances, transactions, etc.
This fix affects the instantiation of the web3 object/contract loading and thus …
> fix: initialise web3 and load contracts in middleware

- src/logic/safe/store/reducer/pendingTransactions.ts
Removal of pending transactions from store.
The `chainId`s presence in the pending transaction store is checked before verifying it's length.
Add a pending transaction and wait for it to succeed. Observe no presence of `pendingTransactions[chainId]` in the store.
> fix: only remove empty `chainId`s

- src/logic/wallets/pairing/hooks/useGetPairingUri.ts
Resolves #3669
There seems to be a delay between when a previous provider is disconnected and a new WC URI is generated.
A very scientific fix, I know.
> Fix: refresh pairing QR code with a timeout

- src/logic/safe/store/actions/createTransaction.ts
- src/utils/events/wallet.ts
Transaction tracking
On-/off-chain interactions now emit a tracking event if they are successful.
- Sign off-chain and observe a tracking event.
- Sign/execute on-chain and observe a tracking event.
> feat: add on-/off-chain tx event tracking

- src/components/VirtualizedList/index.tsx
- src/logic/hooks/useIgnoreResizeObserverError.ts
- src/routes/safe/components/Balances/Collectibles/index.tsx
Resolves `ResizeObserver` errors.
The virtualization of the collectibles list resulted in some [`ResizeObserver` errors](https://sentry.io/organizations/gnosis/issues/3121178886/?project=5436884&query=is%3Aunresolved&sort=freq&statsPeriod=14d). These can, however, be [safely ignored](https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded#comment86691361_49384120). Fix found via the React Virtuoso issue board [here](https://github.com/petyosi/react-virtuoso/issues/369).
1. Open a Safe with a large number of collectibles, e.g. `eth:0xc6400A5584db71e41B0E5dFbdC769b54B91256CD` in Chrome.
2. Excessively scroll through the collectibles list.
3. Observe no `ResizeObserver` errors (`'ResizeObserver loop completed with undelivered notifications.'`,
`'ResizeObserver loop …
> fix: ignore `ResizeObserver` errors

- cypress/integration/landing.spec.js
- cypress/support/index.js
- package.json
- yarn.lock
Adding `@testing-library/cypress`
We can now use the well-known `findBy*` methods in our Cypress tests.
The `landing.spec.js` test should continue to pass.
> chore: use `@testing-library/cypress`

- src/routes/safe/components/Transactions/helpers/EditTxParametersForm/index.tsx
- src/routes/safe/components/Transactions/helpers/TxParametersDetail/index.tsx
- src/routes/safe/container/hooks/useTransactionParameters.ts
Resolves #3735 
The `safeNonce` input field is initially populated with the `recommendedNonce` that is fetched. If the network is slow and the user changes the `safeNonce` in the meantime, it will be overridden once the fetch resolves. 
The `safeNonce` input field shows a loading indicator until the fetch request for `recommendedNonce` has been resolved or the user starts typing. If any user interaction is detected, the value won't be overwritten by the fetch anymore.
- The read view displays a Skeleton element for the safe nonce as long as it is still loading
- The safe nonce input displays a loading indicator
2. Block or throttle the `/estimations` request url
3. Create a new transaction
4. Edit the Advanced Parameters
5. Observe that the safeNonce field has a …
> fix: Disable safeNonce input field until recommendedNonce is fetched

- src/components/SafeListSidebar/SafeList/SafeListItem.tsx
- src/routes/CreateSafePage/components/SafeCreationProcess.tsx
- src/routes/LoadSafePage/LoadSafePage.test.tsx
- src/routes/LoadSafePage/LoadSafePage.tsx
- src/routes/index.tsx
- src/routes/routes.ts
- src/routes/safe/components/Settings/RemoveSafeModal/index.tsx
- src/routes/safe/container/index.tsx
Part of #3693 
Changes the Safe dashboard route from `/app/home` to `/app/<safe address>/home` and loads the Dashboard component inside `SafeContainer` so that it has access to transaction data.
Navigates the user to the Dashboard if:
1. A safe is selected from the Sidebar
2. A safe is created
3. A safe is loaded
4. A safe is removed and there is an available safe
5. `ROOT` is opened if last viewed Safe exists
6. Select a Safe from the Sidebar
7. Observe that the Dashboard is visible
8. Create a new Safe
9. Observe being navigated to the Dashboard
10. Load an existing Safe
8. Observe being navigated to the Dashboard
9. Remove a safe while having another safe on the same network
8. Observe being navigated to the Dashboard
9. Open `/` while having a last viewed Safe
10. …
> feat: Add Safe route for dashboard

- package.json
- src/logic/safe/store/actions/utils.ts
- src/logic/safe/store/reducer/__tests__/gatewayTransactions.test.ts
- src/logic/safe/store/reducer/gatewayTransactions.ts
- src/logic/safe/transactions/api/fetchSafeTransaction.ts
- src/routes/routes.ts
- src/routes/safe/components/Transactions/TxList/TxDetails.tsx
- src/routes/safe/components/Transactions/TxList/TxShareButton.tsx
- src/routes/safe/components/Transactions/TxList/TxSingularDetails.tsx
- src/routes/safe/components/Transactions/TxList/TxSummary.tsx
- src/routes/safe/components/Transactions/TxList/hooks/useTransactionDetails.ts
- src/utils/__tests__/googleTagManager.test.tsx
- yarn.lock
The queue store is super complicated.
This is step 1: always completely overwrite the queue from what CGW returns.
Step 2 will be to get rid of "next" and "queue", along with grouping by nonce, and just store a flat list.
The queue component can then group by nonce when rendering.
> Refactor: overwrite the queue instead of merging + use txId for deep links

- src/components/AppLayout/Sidebar/useSidebarItems.tsx
- src/routes/routes.ts
- src/routes/safe/components/Balances/Collectibles/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/ChooseTxType/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/ReviewCollectible/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/SendCollectible/index.tsx
- src/routes/safe/components/Balances/index.tsx
- src/routes/safe/container/index.tsx
Partially tackles #3329
Adjusted the copy in the UI from "Collectibles" to "NFTs".
Test that the old URL redirects to the new /nft URL.
> Fix: rename Collectibles to NFTs

- package.json
- scripts/cypress.js
Deployment-specific Cypress commands
A script with optional environment argument (`dev`, `staging` or `prod`) allows for a dynamic Cypress `baseUrl`.
Try running:
`yarn cypress:open`
`yarn cypress:open dev`
`yarn cypress:open staging`
`yarn cypress:open prod`
`yarn cypress:run`
`yarn cypress:run dev`
`yarn cypress:run staging`
`yarn cypress:run prod`
and observe Cypress open with varying `baseUrl`s.
> chore: add cypress env commands

- src/routes/safe/components/Apps/communicator.ts
- src/routes/safe/components/Apps/components/AppFrame.tsx
- src/routes/safe/components/Apps/hooks/useIframeMessageHandler.ts
- src/utils/events/safeApps.ts
- src/utils/googleTagManager.ts
Resolves https://github.com/gnosis/safe-apps-sdk/issues/309
We are adding to the current GTM container:
- 4 new variables
- 1 trigger
- 1 Safe App Tag bounded to a GA4 event
- 1 Safe App tag specifying the Measurement ID for the Safe App property
> Add GTM safe apps event tracking

- src/components/AppLayout/Header/components/WalletIcon/index.tsx
- src/components/AppLayout/index.tsx
- src/components/Modal/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/ChooseTxType/style.ts
Resolves https://github.com/gnosis/safe-pm/issues/64
The sidebar on a small screen is shifted off screen. Only 5% of it is still visible, and if you tap on it, it will slide into view.
Tapping anywhere will again hide the sidebar.
Also adjusted modal windows to be full width.
Open the app on a mobile phone
> Feat: toggle sidebar on mobile

- src/components/AppLayout/Sidebar/SafeHeader/index.tsx
- src/components/AppLayout/Sidebar/Threshold/index.tsx
- src/components/AppLayout/Sidebar/index.tsx
- src/components/AppLayout/Sidebar/useSidebarItems.tsx
- src/components/AppLayout/index.tsx
- src/components/List/ListIcon.tsx
- src/components/List/index.tsx
- src/theme/variables.js
- src/theme/variables.scss
Resolves #3504 
- Adjusts the design according to [Figma](https://www.figma.com/file/Y9HUUDQzrbOtMpC3Nye3lt/Safe-Dashboard?node-id=997%3A3128).
- Adds Queue, History links to the navigation
3. Observe that there are links to the Transaction Queue and History
4. Observe that the Sidebar looks according to the design
> feat: Sidebar redesign

- src/components/AppLayout/Sidebar/useSidebarItems.tsx
Part of #3693 
Adds a Home button to the sidebar navigation
2. Select a Safe
3. Observe the Home button in the navigation
4. Click the Home button
5. Observe being navigated to the Dashboard
> fix: Add Home button to sidebar navigation

- package.json
- src/components/Dashboard/FeaturedApps/FeaturedApps.tsx
- src/routes/Home/index.tsx
- src/routes/routes.ts
- src/routes/safe/components/Apps/components/AppsList.test.tsx
- src/routes/safe/components/Apps/utils.ts
- yarn.lock
Part of #3693 
Adds a widget to display featured apps in the dashboard. Layout will be done in a separate PR.
2. Select a Safe
3. Observe a widget that displays Transaction Builder and WalletConnect apps in the dashboard
> feat: Featured Apps Widget

- package.json
- src/logic/hooks/useEstimateSafeCreationGas.tsx
- src/logic/hooks/useEstimateTransactionGas.tsx
Resolves #3483
The default `gasCostFormatted` has now been set to `> 0.001`.
I've verified that all instances of estimation are indeed passed through [`formatAmount`](https://github.com/gnosis/safe-react/blob/dev/src/logic/tokens/utils/formatAmount.ts) and are therefore correct when estimation occurs.
Go through the Safe creation funnel and before the final step, throttle the internet. Go to the next step and observe the default estimation be '> 0.001' before estimation succeeds.
> fix: default gas estimation

- src/logic/addressBook/hooks/useAddressBookSync.ts
- src/logic/addressBook/store/__tests__/addressBookReducer.test.ts
- src/logic/addressBook/store/actions/index.ts
- src/logic/addressBook/store/reducer/index.ts
- src/routes/safe/components/AddressBook/index.tsx
Resolves #3526
If an empty name makes it's way to the address book reducer (be it by adding or importing), it is set to a shortened version of the given address.
A temporary dispatch sets any existing empty-named address book entries to be the same as the above.
Remove the name name of a contact in the locally stored address book. Refresh/navigate to the address book and observe the shortened address be in place of the name.
> fix: set empty names as shortened address

- src/utils/__tests__/googleTagManager.test.tsx
- src/utils/googleTagManager.ts
GTM by default allows custom JavaScript tags which is a security concern.
This PR blocks any tags other than GA4 tags.
https://developers.google.com/tag-platform/tag-manager/web/restrict
All of our events should continue working fine.
> Fix: block custom JS in GTM

- src/logic/wallets/__tests__/network.test.ts
- src/logic/wallets/utils/network.ts
Resolves #3762
As hardware wallets cannot themselves change network, `shouldSwitchNetwork` now returns `false` when they are detected.
Open the wallet connection modal and choose Ledger/Trezor. Observe no error in the console.
> fix: hardware wallet console errors

- .eslintrc.js
- package.json
Lax linting/prettier
The whole project is now checked for lint and automatically prettified. The linting rules were made stricter.
We should ideally remove `'@typescript-eslint/no-explicit-any'` as well as enable the default React linter but this resurrected >100 warnings of non/false-typed code and typing this manually started to get out of hand. I have a local stash of this locally but it became quickly apparent that this would like cause bugs/require a full regression.
For now, the added rules and project-wide scanning should improve our committed code.
- Commit unformatted code and see it get automatically 'prettified'
- Attempt to commit code that goes against our rules and observe a warning that prevents pushing
> fix: stricter linting across repo

- src/components/App/index.tsx
- src/logic/tokens/utils/__tests__/formatAmount.test.ts
- src/logic/tokens/utils/formatAmount.ts
- src/routes/safe/components/Balances/dataFetcher.ts
Resolves #3792
Some values were being formatted to US style by default. This function has been adjusted to simply format numberd and append the currency to the end.
Switch the browser locale between UK and EU (UK using comma thousand separators and full stop decimal separators and EU using the inverse) and observe the following:
- Balance is correctly formatted
- Transaction amount received and that listed in the transaction list also
Taken from the reported transactions `/app/bnb:0x01859368761983ce07c9610BA1C3B2FBa60cae31/transactions/ethereum_0x01859368761983ce07c9610BA1C3B2FBa60cae31_0xa4cdc401a1e67447867559c04dc784c56bbb44c70c2916b281c5d77028528852_0x9e2afd8eb251cf4b`:
> fix: generalise currency formatting

- src/components/App/index.tsx
- src/logic/currentSession/hooks/useCurrentSafeAddressSync.ts
- src/logic/currentSession/store/actions/addCurrentSafeAddress.ts
- src/logic/currentSession/store/reducer/currentSession.ts
- src/logic/currentSession/store/selectors/index.ts
- src/logic/safe/store/reducer/gatewayTransactions.ts
- src/logic/safe/store/selectors/index.ts
- src/routes/safe/components/CurrencyDropdown/CurrencyDropdown.test.tsx
- src/routes/safe/components/Settings/Advanced/Advanced.test.tsx
Resolves #3760 
Instead of relying on the `currentSafe` selector, we handle the logic inside the component by getting all safes from the store, extracting the current safe address from the url and finally selecting the current safe.
1. Open a Safe
2. Switch to a different Safe
3. Observe that Safe name, address, balance, icon updates in the sidebar
> fix: Sync current safe address into store

- src/logic/addressBook/store/__tests__/addressBookReducer.test.ts
- src/logic/addressBook/store/reducer/index.ts
Resolves #3690
`bathLoadEntries` used when loading a Safe or importing and address book now filters invalid addresses from address books. The error was being thrown from the blockie generator plugin.
Import the corrupt csv from the issue and observe that only one entry exists in the Safe address book.
> fix: filter invalid addresses in imports

- src/components/App/index.tsx
- src/components/Providers/SnackbarProvider.tsx
- src/components/Providers/index.tsx
- src/logic/notifications/notificationTypes.ts
- src/routes/routes.test.tsx
- src/routes/routes.ts
- src/routes/safe/components/Apps/components/AppCard/index.tsx
- src/routes/safe/components/Apps/components/AppsList.test.tsx
Resolves gnosis/safe-react-apps/issues/412
In this ticket we should continue with sharing Safe Apps problem statement. This will be focused on creating a share button directly in the Safe Apps list card, creating a valid link to get to the Safe App landing page.
[Figma Designs](https://www.figma.com/file/v56CKWh6Yp60cSsZ71URB0/dApp-sharing-functionality?node-id=1%3A967)
Added a new button to copy the Share Safe App url to the clipboard:
```
https://{{BASE_URL}}/app/share/safe-app?appUrl={{SAFE_APP_URL}}&chainId={{CHAIN_ID}}
```
To be able to test that the Snackbar is showed, I moved our `<SnackbarProvider />` component from `src/components/App/index.tsx` to `/src/components/Providers/index.tsx` (where all our providers are defined)
Now we can check if a Snackbar is showed in our unit …
> feat: Share Safe App button

- src/components/VirtualizedList/index.tsx
- src/index.tsx
Unnecessary errors in Sentry logs.
Three new errors have been added to the ignore list for Sentry:
- ResizeObserver loop completed with undelivered notifications.
- ResizeObserver loop limit exceeded
- Transaction was not mined within 50 blocks, please make sure your transaction was properly sent. Be aware that it might still be mined!
The first two are safe to ignore, [as clarified by the author of the `ResizeObserver`](https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded#comment86691361_49384120) (we do not show it in the console either). The latter we already have a `CodedException` for (`Errors._800`) but this is emitted from `Web3`.
1/2. Scroll excessibly up/down a large NFT list and observe no POST request to Sentry with either error message.
3. …
> fix: add ignored errors to Sentry config

- src/components/Dashboard/FeaturedApps/FeaturedApps.tsx
- src/components/Dashboard/SafeApps/Grid.tsx
- src/routes/safe/components/Apps/hooks/appList/useRemoteSafeApps.ts
As per @sche's feedback, pinned Safe Apps are now displayed in the Safe Apps widget with a priority over random apps.
Current logic:
1) Apps ranked by usage go first
2) Pinned Safe Apps go as a fallback
3) Fill up the remaining slots with random apps
Also fixed the issue that we were issuing two simultaneous requests to the remote Safe App list.
> Feat: prioritize pinned apps in the Dashboard

- src/components/AppLayout/Sidebar/useSidebarItems.tsx
Redirect the user to transaction history instead of transaction queue when clicking the transaction link in the sidebar navigation.
> fix: Transaction nav link to history instead of queue

- src/logic/hooks/__tests__/useEstimateSafeTxGas.test.ts
- src/logic/hooks/useEstimateSafeTxGas.tsx
- src/routes/safe/components/Transactions/helpers/TxModalWrapper/index.tsx
Resolves #3708
`safeTxGas` estimations are always done, regardless of if it is a transaction creation or not.
Errors thrown by `useEstimateSafeTxGas` are now taken into account when (not) showing an estimation failure on older Safes. 
- Open a Safe that requires `safeTxGas`, i.e. 1.1.1
- Attempt to create an invalid `changeThreshold` transaction
- Observe the estimation warning
- Attempt to execute a fully confirmed transaction (i.e. [here](https://pr3812--safereact.review-safe.gnosisdev.com/app/rin:0xcFE0395CBb142b7893E5E039a21408ecE7D1B499/transactions/queue)) and observe the error
> fix: show estimation warnings on Safes that require `safeTxGas`

- src/routes/CreateSafePage/components/SafeCreationProcess.tsx
- src/routes/SafeAppLandingPage/SafeAppLandingPage.tsx
- src/routes/SafeAppLandingPage/components/TryDemoSafe.tsx
- src/utils/events/safeApps.ts
resolves gnosis/safe-react-apps#426
Adding new 4 track events:
1) When opening the Share App landing page we send 2 events, the concrete app and the chain where the app was shared
2) When opening the demo safe we send another event
3) After starting the safe creation from the landing page, if the user completes it and access the safe app we send another event
> feat: Add analytics for the Share App feature

- src/routes/safe/components/Transactions/TxList/Filter/index.tsx
Transaction service filter keys
The field names have been adjusted to match that of the transaction service and filter object generators created.
Add filter values and upon clicking apply, observe the logged object matching that of the transaction service parameters found [here](https://safe-transaction.gnosis.io/).
> fix: adjust fields to tx service params

- src/components/Dashboard/PendingTxs/PendingTxsList.tsx
Part of #3693
The space between pending transactions in the dashboard widget was stretched if there were less than 4 transactions.
Instead of stretching the space, there is a fixed gap between each transaction. The gap is also slightly increased so that the space is filled when there are 4 transactions displayed.
1. Open the safe app
2. Navigate to the dashboard
3. With less than 4 transactions, observe whitespace at the bottom of the widget
4. With 4 transactions, observe the pending tx widget has the same height as the featured apps widget
> style: Adjust gap between pendings txs on dashboard widget

- src/components/Dashboard/Overview/Overview.tsx
Resolves https://github.com/safe-global/safe-react/issues/3840
Do not include in Safe token count tokens with 0 balance
1. Open the Dashboard for a Safe containing some Ether and other tokens and observe that Ether counts as a token in Dashboard Overview widget
2. Open the Dashboard for a Safe containing 0 Ether but other tokens and observe that the Dashboard Overview widget does not count Ether
_Balances_
_Dashboard_
> Fix: do not increase Dashboard token count when Ether balance is 0

- src/components/AppLayout/Sidebar/SafeHeader/index.tsx
- src/components/AppLayout/Sidebar/Threshold/index.tsx
- src/components/Dashboard/Overview/Overview.tsx
- src/components/SafeListSidebar/SafeList/SafeListItem.tsx
Part of #3780 
We display the threshold and number of owners for added safes in the sidebar
1. Open the safe app
2. Open the sidebar drawer
3. Observe thresholds and number of owners for added safes
> fix: Show safe thresholds for added safes in sidebar

- src/components/SafeListSidebar/SafeList/SafeListItem.tsx
Fix for #3891
The Threshold bubble is positioned relative to the Identicon size instead of the row
2. Add a safe with a safe name
3. Add a safe without a safe name
4. Open the sidebar
5. Observe the threshold bubble position is the same for both list items
> style: Adjust sidebar threshold bubble position

- src/components/Dashboard/SafeApps/Grid.tsx
- src/routes/safe/components/Apps/__tests__/trackAppUsageCount.test.ts
- src/routes/safe/components/Apps/trackAppUsageCount.ts
Part of #3693 
Pinned safe apps are included with a given weight when ranking tracked safe apps for the dashboard widget.
2. Navigate to the dashboard
3. Observe that pinned apps are displayed within the safe apps widget
> feat: Include pinned safe apps in dashboard widget

- src/components/AppLayout/Header/components/Layout.tsx
As per Lukas's comment, the logo should link to the root route, not to the Welcome page.
From the root, it redirects either to the Dashboard or to Welcome if no Safe has been viewed.
> Fix: logo links to /

- src/routes/safe/components/Transactions/TxList/TxDetails.tsx
- src/routes/safe/components/Transactions/TxList/TxShareButton.tsx
- src/routes/safe/components/Transactions/TxList/TxSummary.tsx
- src/routes/safe/components/Transactions/TxList/styled.tsx
Resolves #3508 
Moves the share button to top.
Expand the accordion of any tx in the queue or history.
The share button should always be in the top right of the left section (see screenshot)
none, the share button should still be tracked.
> style: move share tx button to top

- src/components/CookiesBanner/index.tsx
- src/logic/hooks/useSafeAppUrl.tsx
Resolves #3876 
Fixes a wrong comparison which caused the intercom to never load.
Open the safe web interface and accept the cookies.
None
No real changes. The intercom still looks the same.
> fix: enables intercom

- .gitignore
- cypress/integration/intercom.spec.js
Intercom was broken for 2 weeks (see #3876), so I added a test for it.
* Enables the Intercom cookies
* Opens Intercom
* Goes to a Safe App to check that Intercom is disabled
* Goes to settings and disables Intercom cookies
> Chore: add e2e tests for Intercom

- src/logic/hooks/__tests__/useAsync.test.ts
- src/logic/hooks/useAsync.ts
- src/logic/hooks/useEstimateSafeTxGas.tsx
- src/logic/hooks/useRecommendedNonce.tsx
- src/routes/SafeAppLandingPage/SafeAppLandingPage.tsx
- src/routes/safe/components/Transactions/TxList/TxSingularDetails.tsx
* Use an array signature for easier naming of returned variables
* Pass a callback and the list of dependencies instead of useCallback
> Refactor: useAsync signature

- src/logic/safe/store/reducer/safe.ts
Resolves retrieval of contract ABIs
The `currentVersion` -`+L2` suffix is removed before saving to the store.
Open a Safe on an L2 network and create/execute a transaction. There should be no `Code 815: Error preparing transaction sender` warning in the console preventing you from executing the transaction.
This needs to be revisited with a cleaner fix.
> fix: remove `+L2` suffix from `currentVersion`

- .github/workflows/deploy.yml
- src/routes/safe/components/Apps/communicator.ts
Cypress is being executed inside an iframe so the current comparison for checking valid messages is not working inside the Cypress context
We are comparing the message source window against `window` instead `window.parent` as should be the same in the web context
> feat: Update isValidMessage() check for Safe Apps

- .github/workflows/deploy.yml
Execute smoke tests only in PRs
> fix: Execute e2e only in PRs

- src/components/Modal/index.tsx
- src/routes/safe/components/Settings/SpendingLimit/FormFields/Beneficiary.tsx
- src/routes/safe/components/Settings/SpendingLimit/NewLimitModal/Review.tsx
Resolves #3894
* Increases the modal width to 525 px (affects all tx modals)
* Makes the beneficiary field wrap to the next line on very small screens
* Start creating a new Spending Limit
* Reduce the window size gradually down to 600 px
> Fix: spending limit beneficiary address can be too long

- package.json
- src/utils/__tests__/googleTagManager.test.tsx
- src/utils/googleTagManager.ts
As Usame discovered in #3913, after #3807, custom events seem to have been broken.
Removes the GTM allowlist and keeps only the blocklist.
Needs to be tested with a production build, so that we can verify that the events are actually sent to GA.
> Hotfix: remove GTM allowlist 🔥 

- src/components/InfoAlert/index.tsx
- src/routes/safe/components/Balances/Collectibles/index.tsx
- src/theme/mui.ts
- src/theme/variables.js
Resolves https://github.com/safe-global/safe-pm/issues/57
* Adds an info bar
* Shows the Safe Apps tagged with `nft` on the NFTs page
- Open the collectibles page
- Close the info bar
- Refresh the page – the info bar should not be displayed again
We should probably track clicks on the apps?
> Feat: show NFT apps on the NFT page

- src/routes/SafeAppLandingPage/SafeAppLandingPage.test.tsx
- src/routes/SafeAppLandingPage/SafeAppLandingPage.tsx
- src/routes/SafeAppLandingPage/components/UserSafeSection.tsx
Resolves https://github.com/safe-global/safe-react-apps/issues/446
Now we only show  the "connect wallet" button if the wallet has not been connected and there are no compatible Safes present in the localstorage:
```
const isWalletConnected = !!userAddress
const hasComplatibleSafes = compatibleSafes.length > 0
const showConnectWalletSection = !isWalletConnected && !hasComplatibleSafes
```
go to 
```
https://pr3924--safereact.review-safe.gnosisdev.com/app/share/safe-app?appUrl=https://safe-apps.dev.gnosisdev.com/tx-builder&chainId=4
```
- If the wallet has not been connected and there are no compatible Safes present in the localstorage, we show the "connect wallet" button.
- If the wallet has not been connected and there ara compatible Safes present in the localstorage, we show the safe …
> feat: Show compatible Safes from localstorage when a wallet has not been connected

- src/routes/safe/components/Apps/components/SafeAppsErrorBoundary.tsx
- src/routes/safe/components/Apps/components/SafeAppsLoadError.tsx
- src/routes/safe/components/Apps/index.tsx
Resolves https://github.com/safe-global/safe-react/issues/3897
Adding a specific ErrorBoundary for Safe Apps covering the iframe space. From there the user can navigate to the Safe Apps list
> feat: Add specific error boundary for safe apps

- src/logic/safe/utils/mocks/getChainsConfigMock.ts
- src/logic/tokens/utils/__tests__/formatAmount.test.ts
- src/logic/tokens/utils/formatAmount.ts
- src/routes/safe/components/Balances/dataFetcher.ts
Overtly long fiat numbers
The maximum number of fiat decimal places is set to 2.
Open the Safe asset list and observe fiat values only having 2 decimal places.
> fix: only use 2 decimals for fiat

- src/logic/hooks/__tests__/useExecutionStatus.test.ts
- src/logic/hooks/useEstimateTransactionGas.tsx
- src/logic/hooks/useExecutionStatus.ts
- src/routes/safe/components/Transactions/helpers/SpendingLimitModalWrapper/index.tsx
- src/routes/safe/components/Transactions/helpers/TxModalWrapper/index.tsx
Resolves #3933 
Returns `EstimationStatus.LOADING` while estimation for `gasPrice` and `gasMaxPrioFee` is still pending
2. Create a transaction
3. Observe the Submit button being disabled while waiting for the gas estimation
> fix: Disable submit button while gas estimation is pending

- src/components/AppLayout/Header/index.tsx
- src/logic/wallets/store/middleware/index.ts
Resolves #3938
Removal of the last provider cache occurs with clicking disconnect.
It was previously removed when onboard was totally disconnected and the provider store was empty, which occurs when switching chain. We didn't experience this bug before as the removal of the wrong key was attempted.
Connect a wallet and:
1. switch to a supported chain and observe successful reconnection.
2. switch to an unsupported chain and observe no reconnection. Switching back to a supported chain should successfully reconnect,
> fix: remove provider on disconnect

- package.json
- src/logic/safe/store/reducer/safe.ts
- yarn.lock
Reverts https://github.com/safe-global/safe-react/pull/3891 changes
Version metadata is now handled by `safe-deployments` and we can therefore remove this hotfix.
Any process involved the mastercopy of L2/Circles Safes should be tested; executing a transaction, upgrading the Safe, etc.
> fix: remove `+L2` hotfix

- src/routes/safe/components/Transactions/TxList/TxShareButton.tsx
The hover color of the share TX  Button was not matching the figma one.
Resolves https://github.com/safe-global/safe-react/pull/3943#issuecomment-1150910974
Changes the hover color
hover the share tx button
> fix: hover color of TxShareButton

- src/logic/hooks/__tests__/useExecutionStatus.test.ts
- src/logic/hooks/useExecutionStatus.ts
Resolves #3958
Errors during gas estimation (GS13) will cause a fallback of gas limit 0.
The hook `useExecutionStatus` now accepts a gas limit of 0 as not a loading state.
See #3958
> fix: prevent endless estimation on erronous gas limit estimation

- src/logic/hooks/__tests__/useEstimateTransactionGas.test.ts
- src/logic/hooks/__tests__/useEstimationStatus.test.ts
- src/logic/hooks/__tests__/useExecutionStatus.test.ts
- src/logic/hooks/useEstimateTransactionGas.tsx
- src/logic/hooks/useEstimationStatus.tsx
- src/logic/hooks/useExecutionStatus.ts
- src/routes/safe/components/Transactions/helpers/SpendingLimitModalWrapper/index.tsx
- src/routes/safe/components/Transactions/helpers/TxModalWrapper/index.tsx
Resolves #3962
Changes default `gasPrice` and `gasMaxPrioFee` estimation to undefined instead of 0.
1. Open the Safe app on BSC or Arbitrum
2. Create a transaction
3. Observe the Submit Button being clickable
> fix: Change default gas estimation state from 0 to undefined

- src/logic/hooks/useNotifier.tsx
- src/logic/notifications/notificationTypes.ts
- src/logic/notifications/store/notifications.ts
Adds extra 'state' flags for notifications
`timestamp` (for showing the date in the notification centre), `read` (whether the notification is (un-)read) and `action` (likely a `ReactElement` link) have been added to the notification system.
Dispatch a notification and observe the `timestamp`/`read` flags in the store by default. `read` will be set to `true` unless the notification is not manually dismissed.
`action` is not used yet and will not be present in the store.
> feat: add `timestamp`, `read` and `action` to notifications

- src/components/AppLayout/Header/components/Layout.tsx
- src/components/AppLayout/Header/components/Notifications.tsx
Adds bell to header with unread badge.
A new bell icon button has been added to the header, displaying a dot badge when there are unread notifications in the store.
Observe the new bell in the header. When attempting to sign a transaction, a notification is dispatched and there will be a green badge on the bell.
> feat: notification header bell

- src/routes/CreateSafePage/components/SafeCreationProcess.tsx
- src/routes/opening/index.tsx
- src/utils/events/createLoadSafe.ts
Part of #3948 
Adds additional tracking for Safe Creation:
- Tx was submitted by user
- Tx was rejected by user
- Safe Creation was canceled
- Safe Created was retried
Removes the "Back" Button that is displayed after the tx is submitted.
2. Create a new Safe
3. Observe GTM Events being sent when rejecting/submitting the Tx in the wallet provider
4. Observe GTM Events being sent when clicking Retry or Cancel
5. Observe no Back Button in the Footer after Tx Submission
> fix: Track more safe creation steps

- cypress/integration/smoke/balances.spec.js
Fixes the balances e2e test.
The balances are sorted based on value, and USDC apparently depreciated relative to the other tokens in the test Safe.
Ideally we should find the correct row by the token symbol, not just by index. But for now I just fixed it by hardcoding the correct USDC row.
> Chore: fix the balances test

- src/routes/safe/components/Transactions/helpers/TxModalWrapper/index.tsx
Resolves #3983 
Gas estimation in 1.1.1 Safes was broken in many ways since #3868 or possibly even before.
The variable `safeTxGas` was redefined after its first usage. I moved it up.
* Open a 1/X Safe v.1.1.1
* Make a simple tx
* Check that the gas limit and total gas depend on the safeTxGas
NB: editing the safeTxGas in the Advanced form **will not** automatically update the gas limit. This hasn't changed from prod.
Before (gas limit 60k):
After (gas limit 100k):
> Fix: gas estimation in 1.1.1 Safes

- src/logic/safe/store/actions/transactions/__tests__/loadGatewayTransactions.test.ts
- src/logic/safe/store/actions/transactions/fetchTransactions/loadGatewayTransactions.ts
- src/routes/safe/components/Transactions/TxList/Filter/index.tsx
- src/utils/constants.ts
History pointers polling `next`
`loadHistoryTransactions` has been split back to `loadHistoryTransactions` and `loadPagedHistoryTransactions`, the latter used for loading `next`+ `pageUrl`s.
1. Open a Safe with a large history, scroll to the second page. Enable a filter that also has a large amount. Observe the correct endpoints was queried and that is is correctly paginated. Clearing the filter should return to the history results, which should also be paginated correctly.
2. Open a Safe with a large history, create and execute a transaction. Observe the transaction no longer remains pending but moves to the history when successfully indexed.
> fix: history polling `next`/transactions remaining pending

- src/components/AppLayout/InvalidMasterCopyError/index.tsx
The xl size of the link looks weird:
I've changed it to `lg` to match the text font:
> Fix: mastercopy link size

- src/logic/notifications/notificationTypes.ts
- src/logic/safe/store/middleware/notificationsMiddleware.ts
- src/logic/safe/transactions/__tests__/pendingTxMonitor.test.ts
- src/logic/safe/transactions/pendingTxMonitor.ts
- src/logic/safe/utils/aboutToExecuteTx.ts
- src/routes/safe/components/Settings/ManageOwners/EditOwnerModal/index.tsx
- src/routes/safe/components/Settings/SafeDetails/index.tsx
- src/routes/safe/components/Transactions/TxList/hooks/useActionButtonsHandlers.ts
Adding links to current notifications
All current notifications that could have links added to them, i.e. when a Safe requires an update, now receive and render links.
- Open a Safe that requires an update and observe the notification now including a link.
> feat: add links to current notifications

- package.json
- src/routes/safe/components/Transactions/TxList/Filter/RHFTextField.tsx
- src/routes/safe/components/Transactions/TxList/Filter/__tests__/utils.test.ts
- src/routes/safe/components/Transactions/TxList/Filter/index.tsx
- src/routes/safe/components/Transactions/TxList/Filter/utils.ts
Date filters, part of https://github.com/safe-global/safe-pm/issues/52 epic
The previously broken date filters have been fixed and are now enabled.
Open the historical transaction list and search by date range. Observe the filtered transactions matching those of the filtered dates.
To/from date periods are tracked.
> fix: enable date filters

- src/routes/safe/components/Transactions/helpers/Simulation/SimulationResult.tsx
Fixes this: https://github.com/safe-global/safe-react/pull/3925#issuecomment-1170028186
The simulation result should say "transaction", not "batch".
I also took the opportunity to refactor the result component slightly. Best reviewed with whitespace changes disabled: https://github.com/safe-global/safe-react/pull/4004/files?diff=split&w=1
> Fix simulation text: batch -> transaction

- src/logic/wallets/e2e-wallet/module.ts
Resolves E2E tests failing due to a timeout in the gas estimation.
Uses the `rpcUri` returned in the config instead of the public `publicRpcUri` for a reliable estimation
Run  `add_owner.spec` and `tx_modal.spec` locally against this branch and both tests should past the gas estimation assertion
```
// Estimated gas price is loaded
cy.contains('Estimated fee price').next().should('not.have.text', '> 0.001 ETH')
> tests: use the RPC uri returned by the services in E2E

- src/logic/safe/store/models/types/__tests__/gateway.d.test.ts
- src/logic/safe/store/models/types/gateway.d.ts
- src/logic/safe/transactions/__tests__/multisend.test.ts
- src/logic/safe/transactions/multisend.ts
- src/routes/safe/components/Transactions/TxList/TxCollapsed.tsx
- src/routes/safe/components/Transactions/TxList/TxData.tsx
- src/routes/safe/components/Transactions/TxList/TxDetails.tsx
- src/routes/safe/components/Transactions/TxList/TxSummary.tsx
Related to #4021 as a Custom contract interaction calling a `multiSend` method could break the UI
The type guard to verify if a transaction is a supported `multisend` call verifies the called contract address
Having a transaction interacting with a `multiSend` method in a different contract than the supported Multisend should not display a custom TxDetails UI
1. Transaction with an [unsupported "multiSend" contract](https://gnosis-safe.io/app/rin:0x7a9af6Ef9197041A5841e84cB27873bEBd3486E2/transactions/multisig_0x7a9af6Ef9197041A5841e84cB27873bEBd3486E2_0xe0804fca410add0a1ac138d2ecbf64f58fa0b9a9630287e8c0ab425c26761a34)
> fix: verify multisend contract address

- src/routes/safe/components/Transactions/TxList/SpendingLimitDetails.tsx
- src/routes/safe/components/Transactions/TxList/TxData.tsx
The app is crashing in https://gnosis-safe.io/app/eth:0x63Ef071b8A69C52a88dCA4A844286Aeff195129F/transactions/history when expanding a "Contract interaction - setAllowance".
Resolves #4021
What is happening, in reality, is that the web app is rendering a SpendingLimit transaction details whenever there is a Contract interaction calling any `setAllowance` or `deleteAllowance`.
In the reported Safe, the crashing transactions are made to a different contract than our AllowanceModule and we are wrongly trying to display the SpendingLimit custom TxDetails for a method that can be called with totally different parameters.
The fix verifies taht the `setAllowance` and `deleteAllowance` calls are made to our AllowanceModule known addresses -> …
> fix: Verify spending limit contract address for displaying custom UI

- src/routes/safe/components/Transactions/TxList/styled.tsx
Reported via [Slack](https://5afe.slack.com/archives/C03DAGWJCR5/p1658406862903569)
- Adjusts css for the vertical `tree-lines` in grouped txs to fix an issue in Safari
- Open a Safe with grouped transactions in the queue in Safari Browser
- Observe all transactions are visible
> style: Fix tree lines for grouped txs

- src/components/TransactionQueueBar/TransactionQueueBar.test.tsx
- src/logic/contracts/safeContracts.ts
- src/logic/safe/store/actions/TxMultiSender.ts
- src/logic/safe/transactions/__tests__/multisend.test.ts
- src/logic/safe/transactions/multisend.ts
- src/logic/safe/utils/__tests__/upgradeSafe.test.ts
- src/logic/safe/utils/spendingLimits.ts
- src/routes/safe/components/Apps/components/ConfirmTxModal/ConfirmTxModal.test.tsx
- src/routes/safe/components/Apps/components/ConfirmTxModal/ReviewConfirm.tsx
- src/routes/safe/components/Settings/Advanced/Advanced.test.tsx
- src/routes/safe/components/Settings/UpdateSafeModal/index.tsx
- src/routes/safe/components/Transactions/TxList/BatchExecute.tsx
Related to #4021 
- Extends `isSupportedMultiSendAddress` to check both multiSend contracts
- Open `eth:0xEb3107117FEAd7de89Cd14D463D340A2E6917769/transactions/multisig_0xEb3107117FEAd7de89Cd14D463D340A2E6917769_0xea45c2dcec5f31f74eaf43f3c144e1eab772cbfeac077d816f89a70257212756`
- Observe the transaction being recognised as a multi send tx instead and displaying decoded data
Before:
After:
> fix: Extend isSupportedMultiSendAddress

- src/routes/safe/components/Apps/components/ConfirmTxModal/ReviewConfirm.tsx
Resolves #4036
Pass safeTxGas parameter to TxModalWrapper and parse from number to string if exists
[This Safe App](https://circles-groups-safe-jguyhds57-bootnode.vercel.app/) only available for Gnosis Chain, tries to set safeTxGas to 0. Parameter is currently ignored in prod.
After the change we set the suggested safeTxGas and we still calculate for those Safe Apps that don't suggest any value
More context directly in #4036 ticket
> Add safeTxGas parameter on TxModal for Safe App tx

- Dockerfile
- prod.Dockerfile
After commit 98476d07, there are no files to copy from `src/logic/contracts/artifacts` to the docker container, causing the build process to throw an error.
Remove COPY step, as it's no longer needed.
Via `docker-compose build`
> fix: don't COPY artifacts to container

- package.json
- src/routes/safe/components/Apps/components/AppFrame.tsx
- src/routes/safe/components/Apps/components/SignMessageModal/SignMessageModal.test.tsx
- src/routes/safe/components/Apps/components/SignMessageModal/index.tsx
- src/routes/safe/components/Apps/hooks/useSignMessageModal.ts
- yarn.lock
This PR fixes bugs found in the EIP712 signing found by the 1inch team. They're the following:
- Unnecessary wrapping of the EIP712 typed data with Safe's EIP712 message structure
- Unnecessary JSON wraps/unwraps of the EIP712 data 
1. Run https://github.com/gnosis/safe-test-app/pull/2
2. Use a test message, it should be a valid JSON. Example:
```
{"domain":{"verifyingContract":"0x0000000000000000000000000000000000000777","chainId":1},"message":{"message":"0x"},"types":{"SafeMessage":[{"type":"bytes","name":"message"}]}}
```
3. Paste it into the textarea
4. Click a button to sign it
5. Confirm that the message matches your test message
6. Sign and execute the signing
7. Check if the message is signed by clicking the button in the test app
Related SDK PR …
> Fix: EIP712 signing

- src/components/AppLayout/Header/components/SafeTokenWidget/index.tsx
- src/utils/constants.ts
Uses the app ID from staging `61` and production `95` to fetch the app URL for the claiming app.
Click the token widget.
Hint: For prod the id exists but its disabled and not yet returned by the config service. But as soon as it gets enabled it should work.
None
> fix: use app id to fetch claiming app url

- src/components/AppLayout/Header/components/SafeTokenWidget/index.tsx
- src/components/Dashboard/SafeApps/index.tsx
Displays the safe-claiming-app at the first spot on the dashboard.
1. Open the Safe on Rinkeby
2. Navigate to the dashboard
3. Observe the safe-claiming-app at the top of the list
> fix: Display claiming app at the first position in dashboard

- src/routes/safe/components/Apps/components/SignMessageModal/SignMessageModal.test.tsx
- src/routes/safe/components/Apps/components/SignMessageModal/index.tsx
This is basically https://github.com/safe-global/web-core/pull/622 but for `safe-react`, for more context please check https://github.com/safe-global/web-core/pull/622
> Fix: Filter out the EIP712Domain type from eth_signTypedData RPC payload before passing to the hashing function

- src/routes/safe/components/Balances/SendModal/screens/SendFunds/index.tsx
- src/routes/safe/components/Balances/SendModal/screens/SendFunds/style.ts
The SAFE Token is currently paused so we display a non-transfer warning and disable the Submit button
1. Open a safe that has Safe Tokens
2. Create a new transaction
3. Select the Safe Token
4. Observe an error message below the token field
5. Observe the Review Button is disabled
> fix: Display non-transfer warning when selecting safe token

- package.json
- src/components/AppLayout/Header/components/SafeTokenWidget/index.tsx
- src/components/AppLayout/Header/components/SafeTokenWidget/useSafeTokenAllocation.ts
Total allocation (user + ecosystem) instead of current balance is displayed inside the safe token widget.
1. Open a safe that is not elligible for the airdrop
2. Observe the widget displaying 0
3. Open a safe that is elligible for the user airdrop
4. Observe the widget displaying the total user allocation
5. Open a safe that is elligible for the ecosystem airdrop
4. Observe the widget displaying the total ecosystem allocation
5. Open a safe that is elligible for both airdrops
6. Observe the widget displaying the sum of both allocations
> fix: Display total allocation instead of balance in safe token widget

- .github/workflows/deploy.yml
- src/utils/constants.ts
This PR:
- Pass the WalletConnect secret URL to the GitHub action build step 
- Adjust the fallback value for the walletconnect bridge URL
> Fix: Pass the wc url secret to the github action and adjust the fallback value

- src/components/PsaBanner/index.tsx
- src/components/SafeListSidebar/style.ts
Pushes the sidebar a bit down the banner height to be able to click "Load Safe" when banner is shown
Add the banner height to the top property in the sidebar
> style: push Sidebar down the banner height

- src/components/PsaBanner/index.tsx
- src/components/Root/index.module.scss
- src/components/SafeListSidebar/index.tsx
- src/components/SafeListSidebar/style.ts
- src/utils/storage/useCachedState.ts
The sidebar needs to shift down when the banner is open.
Also store the closed state in the session storage, not in the local storage.
> Fix: close banner only for the session; shift sidebar drawer

- src/components/AppLayout/Header/components/SafeTokenWidget/index.tsx
Link from allocation widget in header to open the Safe App is malformed, missing `/app` and reloads the whole web. Somehow in web is working but the desktop app is not able to resolve the link.
Use react-router to navigate to the correct route
Check that in prod the `/app` is missing when hovering the allocation widget in the header
Styles should be exactly the same. Link should correctly redirect to the Safe App
In the desktop app without this fix, app is not correctly redirected. If we use a normal link the current Wallet is disconnected
> Fix correct linking for token allocation

- src/components/PsaBanner/index.tsx
Preventing redirection to new deployment.
When the `no-redirect` search parameter is present, redirection to the new deployment doesn't occur.
Add `?no-redirect=true` to the end of the URL and observe that the redirection is not present in the banner.
Note: the banner close flag will need to be removed from the `localStorage`.
> fix: prevent redirection flag

- package.json
- src/components/PsaBanner/index.tsx
Updated banner text.
The banner text now reads:
```
Safe's new official URL is app.safe.global, with a fully rebranded and refurbished application. The old app will run in parallel and we will announce its deprecation in time.
```
Open the app and observe the new banner text.
> fix: adjust banner text

- src/routes/export/Export.tsx
- src/routes/index.tsx
- src/routes/routes.ts
- src/routes/safe/components/Settings/DataExport/index.tsx
- src/routes/safe/components/Settings/SafeDetails/index.tsx
Part of https://github.com/safe-global/web-core/issues/1097
- Adds an export button to the settings page
- Adds a new global route `/export` that contains the same button
- Downloads a .json file containing added safes and address book entries
- The `.json` file is versioned with version `1.0` and contains a `data` key with the `localStorage` data
2. Navigate to Settings
3. Observe a section with a Download button
4. Click the button
5. Observe a `.json` file being downloaded that contains the localStorage
> fix: Add export data button to settings page

- README.md
Remove mention/links of Gnosis from the readme.
- All mention of Gnosis and related links have been removed.
- GitHub links have been altered to `safe-global` instead.
- Redundant deployment links environments as well.
Observe that the readme has no mention or links of Gnosis.
> fix: remove Gnosis from readme

- src/components/AppLayout/Header/components/Layout.tsx
- src/components/AppLayout/Sidebar/index.tsx
- src/components/layout/Page/index.tsx
- src/routes/export/Export.tsx
The Export page is the only page that will be accessible in the old app for some time.
We need to prevent navigation to any other react route from it.
I'm hiding all header elements except for the logo (which now links to the new app), and the contents of the sidebar.
> Fix: hide header and sidebar on the Export page

- package.json
- src/components/AppLayout/Header/components/Layout.tsx
- src/components/AppLayout/Sidebar/index.tsx
- src/components/layout/Page/index.tsx
- src/routes/export/Export.tsx
A small fix to hide internal links on the Export page.
Can be tested on https://safe-web.dev.5afe.dev/app/export
All other URLs, e.g. https://safe-web.dev.5afe.dev/app/welcome, should redirect to the new app.
> Release 3.33.6
