.babelrc
.travis.yml
config/deploy/deploy.sh
config/webpack.config.prod.js
package-lock.json
package.json
scripts/build.js
src/index.js

This PR deploys automatically PRs, branches and tags. Also, it includes an automatic script for including as a comment the URL for testing PRs

[WIP] - Adding travis and CI

---

src/components/layout/Paragraph/index.scss
src/routes/safe/component/Layout.jsx
src/routes/safe/component/Layout.stories.js
src/routes/safe/component/Safe.jsx
src/routes/safe/container/actions.js
src/routes/safe/container/index.jsx
src/routes/safe/container/selector.js
src/routes/safe/store/test/balance.reducer.js
src/routes/safe/store/test/balance.selector.js

This PR includes the UI changes for displaying the balance on saved. In this version for updating the balance, you have to reload the website (after doing a transaction).
See the [video](https://drive.google.com/open?id=1yuKXaDqT-m1HBtf--OymqIJHWHBTgOFp)
**## Dev Notes**
@germartinez comments received on related PRs have been addressed here (basically doing tests using ETH with decimals

WA-230 - Show balance in UI

---

src/routes/safe/container/index.jsx

This PR is the last part of the "display safe funds feature", it includes an interval for checking every 1.5 seconds if the safe 's balance has changed. 
See [video](https://drive.google.com/open?id=11u9jM57m6tuSp4ZjEthPmOzFCqhU6iHt)
**## Dev Notes**
Need to check if reselect and immutable works fine and only re-render the component when the balance has changed and not every time the interval is run

WA-230 Introducing interval for checking balance

---

src/components/forms/validator.js
src/routes/open/components/Layout.test.js
src/routes/open/components/ReviewInformation/index.jsx
src/routes/open/components/SafeForm/Confirmations/index.test.js
src/routes/open/components/SafeForm/DailyLimit/index.jsx
src/routes/open/components/SafeForm/index.jsx
src/routes/open/components/fields.js
src/routes/open/container/Open.jsx
src/routes/open/utils/safeDataExtractor.js
src/routes/safe/component/Safe/DailyLimit.jsx
src/routes/safe/component/Safe/Owners.jsx
src/routes/safe/component/Safe/index.jsx
src/routes/safe/store/actions/addSafe.js
src/routes/safe/store/model/safe.js
src/routes/safe/store/test/builder/deployedSafe.builder.js
src/routes/safe/store/test/builder/safe.builder.js
src/routes/safe/store/test/safe.reducer.js
src/routes/safeList/components/SafeTable.jsx

This PR introduces the Daily Limit component and information in all routes where it applies:
* safelist route
* open safe route
* display safe route
Also, it updates the immutable Safe record and all actions related to it, tests have been updated as well.
**##Pictures**
**Dev Notes**
For reviewing this PR I just recommend do a "lexical" review and also visit the storybook link for checking all routes.

WA-238 - Include daily limit component in UI

---

src/routes/safe/component/Transactions/test/transactions.test.js
src/routes/safe/component/Transactions/test/transactionsHelper.js
src/routes/safe/component/Transactions/transactions.js
src/routes/safe/store/model/confirmation.js
src/routes/safe/store/model/transaction.js
src/routes/safe/store/reducer/safe.js
src/routes/safe/store/test/builder/safe.builder.js
src/utils/localStorage.js

**Due Diligence**
This PR introduces code for mocking service of creating, storing and retrieving transactions and confirmations of multisig operations. Frontend is not involved.
This PR has been developed by BDD, where all scenarios were represented in different tests. See:

WA-238 - Multisig TXs logic

---

src/routes/load/components/DetailsForm/index.jsx
src/routes/open/components/SafeOwnersForm/index.jsx

So in my previous PR I removed a spacing from Input which was caused by a bug.
The error message was positioned relatively when it meant to be absolute inside the flexbox container. This way it didn't drop out from document flow and CSS added spacing to the Input which was equal to the height of the message.
Hope you understand me haha :)
Link to SO with the same issue:
https://stackoverflow.com/questions/47444114/flex-box-item-with-relative-element
And this change removed spacings from the pages where the component was used. There I add them back the right way
**BEFORE:**
**AFTER:**

BUG: input spacings

---

src/config/development.js
src/config/production.js

Update tx history service api url

---

src/config/development.js
src/config/production.js

See https://github.com/gnosis/safe-react/issues/165

Update transaction history endpoints

---

src/logic/tokens/utils/tokensStorage.js
src/routes/safe/store/middleware/safeStorage.js

This PR:
- Fixes the conditions for recalculating active tokens, there are only 2 situations where we do this: Safe's tokens updated (UPDATE_SAFE action) / Custom token added for all safes (ACTIVATE_TOKEN_FOR_ALL_SAFES action)
- Small eslint fixes

BUG: Active tokens not saved

---

src/test/safe.dom.balances.test.js
src/test/utils/transactions/transactionList.helper.js

Add test for a bug we recently experienced (ether balance not updating automatically)

Test: Token balance updates

---

src/logic/tokens/utils/tokenHelpers.js
src/routes/safe/store/actions/fetchTransactions.js

See https://github.com/gnosis/safe-react/issues/177

Refactor isTokenTransfer

---

package.json
src/routes/safe/components/Settings/style.js
yarn.lock

- Add margin at bottom of settings block to allow scrolling on smaller screens
- Bump dependencies

Bugfix: Settings bottom spacing on smaller screen

---

src/components/Modal/index.jsx
src/routes/safe/components/Balances/Receive/index.jsx
src/routes/safe/components/Balances/index.jsx
src/routes/safe/components/Balances/style.js
src/routes/safe/components/Layout.jsx
src/routes/safe/components/style.js
yarn.lock

Feature #132: Receive view improvements

---

src/utils/storage/index.js

So mainnet/rinkeby safes aren't mixed together

Update storage prefix key

---

package.json

Safe for Teams v1.0.0 (Early Access)

---

src/logic/contracts/safeContracts.js
src/routes/load/components/DetailsForm/index.jsx

- Version of the Safe has to be at least v1.0.0
- Closes #213

Support Safes with old proxy (payingProxy)

---

.gitignore
src/logic/tokens/utils/alternativeAbi.js
src/routes/safe/components/Transactions/TxsTable/columns.js
src/routes/safe/store/actions/fetchTransactions.js

- Use alternative abi for getting symbol for DAI token
- Also fix token transfer tx showing as custom transactions
https://github.com/ethers-io/ethers.js/issues/527
https://ethereum.stackexchange.com/questions/53038/contract-returns-a-hex-value-when-a-string-is-expected

Hotfix: Transactions don't show up if there's DAI token tx

---

src/routes/safe/store/actions/fetchTransactions.js

Update `safe-react` for the refactor of the Safe Transaction Service. It should be a minor refactor, but I'm already opening this PR:
- Remove executed txHash from confirmations

Update safe-react for the refactor of the Safe Transaction Service

---

package.json
src/components/forms/validator.js
yarn.lock

This PR:
- Solves #214 by checking in the validator that address starts with `0x`
- dep bump

Bug 214: Addresses without 0x are valid to input

---

src/index.js

Adjusting https://github.com/gnosis/safe-react/pull/295

Increase TO_EXP for bignumber.js

---

.travis.yml

My previous PR (#275) removed the build step of storybook but I forgot to remove the deployment step, this lead to deployment failures

Fix CI: Remove deployment of storybook

---

src/routes/safe/components/Balances/dataFetcher.js
src/routes/safe/components/Balances/index.jsx
src/routes/safe/components/Balances/style.js

Feature #291: Remove 'Hide zero balances'

---

src/utils/googleAnalytics.js

This is recommended for GDPR:
https://brianclifton.com/blog/2018/06/19/impact-of-anonymizeip/

Anonymize IP Address in google analytics

---

src/routes/safe/components/Balances/Tokens/screens/AddCustomToken/index.jsx

Bug #210: Makes minMaxLength 2 to AddCustomToken

---

src/routes/safe/components/Balances/dataFetcher.js

Bug #357: Fixs ETH display on balances list

---

src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/index.jsx

See https://github.com/gnosis/safe-react/issues/376

Fix transaction description value

---

src/routes/safe/store/actions/fetchSafe.js
yarn.lock

This PR:
- Fixes the bug by updating the logic used to compare owners in `checkAndUpdateSafe` function

Bug: Owner gets removed after safe creation and added with UNKNOWN name

---

src/routes/safe/components/Transactions/TxsTable/Status/index.jsx

- Change label for cancelled tx to "Cancelled"

Bug: cancelled tx shown as failed

---

package.json
src/components/ConnectButton/index.jsx
src/logic/notifications/notificationTypes.js
src/logic/safe/safeTxSigner.js
src/logic/safe/transactions/gasNew.js
src/logic/wallets/store/actions/removeProvider.js
src/routes/safe/components/Transactions/TxsTable/Status/index.jsx
src/routes/safe/container/selector.js
src/routes/safe/store/actions/createTransaction.js
src/routes/safe/store/actions/processTransaction.js
src/test/signatures.blockchain.test.js
yarn.lock

- https://github.com/gnosis/safe-react/pull/393
- https://github.com/gnosis/safe-react/pull/324
- https://github.com/gnosis/safe-react/pull/429

V1.6.1 - Bugfixes

---

src/logic/currencyValues/api/fetchTokenCurrenciesBalances.js
src/routes/load/container/Load.jsx
src/test/builder/safe.dom.utils.js

That way 301 is not triggered on server

Add slash to the end of urls

---

package.json
src/components/ConnectButton/index.jsx
src/logic/wallets/store/actions/fetchProvider.js

Add an event when user connects a wallet

add ga event when connectin wallet & disable squarelink

---

src/components/layout/PageFrame/assets/alert.svg
src/components/layout/PageFrame/assets/check.svg
src/components/layout/PageFrame/assets/error.svg
src/components/layout/PageFrame/index.jsx
src/theme/mui.js

Closes #332 
It should look better now.

(fix) Notifications' visual inconsistencies

---

package.json

Revert "Update web3connect version. Closes #452"

---

package.json
src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/screens/ThresholdForm/index.jsx
src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/screens/ThresholdForm/index.jsx
yarn.lock

This is fixed by fixing the `material-ui/lab` dependency to version `4.0.0-alpha.39`
The problem:

(Fix) Send form fails to load

---

src/routes/safe/store/actions/createTransaction.js

This fixes an overwritten parameter after merging #564

(Hotfix) Safe Upgrade is not working

---

package.json

This PR intention is to have a final version of package.json file that does not diverge from changes made in `master`

Update `package.json` to match `master` branch

---

src/logic/safe/utils/safeVersion.js

This PR solves a linting error in `development`

Fix linting error

---

.travis.yml
config/webpack.config.prod.js

To make the app work with new server configuration

Add public url to prod webpack config

---

.travis.yml

The sole intention of this PR is to force linting and prettier checks into the CI.

(Feature) Add checks into CI

---

.travis.yml
config/travis/build.sh
config/travis/deploy_pull_request.sh
config/travis/deploy_release.sh
config/webpack.config.prod.js
src/components/forms/TextField/index.jsx
src/routes/safe/components/Layout.jsx
src/routes/safe/components/Settings/index.jsx
src/store/index.js
yarn.lock

- Add to `deploy_pull_requests.sh` to the new path.
- Replace upload-dir to deploy staging to the new path.

Repare new dev and staging enviroments to deploy

---

src/routes/safe/components/Apps/appsList.js
src/routes/safe/components/Apps/index.jsx

Update Apps list urls for Compound, ENS and Uniswap

update Apps list info

---

package.json
src/store/index.js
yarn.lock

- Use hash-based routing setup

V1.7.5 release

---

config/travis/deploy_release.sh
package.json

This PR:
- Removes caching for app's index.html
- Bumps version to 1.7.6

BUG: App index.html cached on production

---

src/logic/safe/safeTxSigner.js
src/logic/safe/transactions/gas.js
src/logic/safe/transactions/gasNew.js
src/routes/safe/store/actions/createTransaction.js
src/routes/safe/store/actions/processTransaction.js

Update documentation links to https://docs.gnosis.io/safe

Update links to docs

---

package.json

Set version to 1.8.1 (#672)

---

src/routes/safe/components/AddressBook/index.jsx
src/routes/safe/components/Balances/Collectibles/index.jsx
src/routes/safe/components/Balances/SendModal/index.jsx
src/routes/safe/components/Balances/SendModal/screens/ReviewCollectible/index.jsx
src/routes/safe/components/Balances/SendModal/screens/ReviewCustomTx/index.jsx
src/routes/safe/components/Balances/SendModal/screens/ReviewTx/index.jsx
src/routes/safe/components/Balances/SendModal/screens/SendCustomTx/index.jsx
src/routes/safe/components/Balances/SendModal/screens/SendFunds/index.jsx
src/routes/safe/components/Balances/index.jsx
src/routes/safe/components/Layout.jsx

Also, this commit includes an intent to unify/simplify SendModal component
fixes #632

(Fix) send tx from address book

---

package.json
src/components/ConnectButton/index.jsx
yarn.lock

There are a few things the gnosis legal team suggested we change in the copy of this modal.
- “connect to Gnosis Safe Multisig” instead of “connect to this dapp”.
- “digital assets like Ether” instead of “assets like Ethereum”.
- Remove last sentence entirely.
The last two items are not currently configurable, but Blocknative team would make a new release with that changes. EDIT: This changes are updated with the `1.5.0` version

Customize the info shown in the Onboardjs modal

---

src/routes/opening/index.jsx

Fix safe creation from walletConnect 

---

src/routes/opening/index.jsx
src/routes/safe/store/actions/fetchEtherBalance.js

- Pass `newEthBalance` value for key `ethBalance` to `updateSafe` action in `fetchEtherBalance`

Bug: Eth balance not updating

---

src/logic/tokens/store/actions/fetchTokens.js
src/logic/tokens/store/actions/loadActiveTokens.js

Closes #751
- As described in the ticket, we found that some decimals from the backend where wrong, so we decided to fix this taking the decimals from the blockchain.

#751 fix - Replaces decimals from backend with decimals from blockchain

---

.travis.yml

Enable region for s3 provider to allow upload development environment to different S3 regions

Add region to travis CI develop

---

src/components-v2/layouts/ListContentLayout/Layout.jsx
src/components/layout/Page/index.scss
src/routes/safe/components/AddressBook/style.js
src/routes/safe/components/Settings/style.js
src/routes/safe/components/Transactions/TxsTable/style.js

(Enhancement) #773 Scroll bar in tabs that are not necessary 

---

src/routes/safe/components/Transactions/TxsTable/columns.js
src/routes/safe/store/actions/fetchTransactions.js

This is @Agupane finding, we were working on fixes.
- wrong parameters order: https://github.com/gnosis/safe-react/commit/c887c71b05df409213e6b3825e320a0e88f2d15c
- wrong logic for some sendTokens: https://github.com/gnosis/safe-react/commit/cdcdd07b234d1af472f97220bc96652bedfbb2ec
- invalid display of txs amount with long decimals: https://github.com/gnosis/safe-react/commit/55eee73ea735c11a445f3d717797bfd10ca9f94e

(Fix) Tx Table fails to display OutgoingTx data

---

src/components/forms/AddressInput/index.jsx
src/components/forms/validator.js
src/routes/load/components/DetailsForm/index.jsx
src/routes/safe/components/Apps/ManageApps.js

(Fix) - 794 safe load empty

---

src/routes/safe/components/Balances/Tokens/screens/AddCustomToken/index.jsx

(Fix) - Converts custom token address to checksum version

---

src/logic/safe/transactions/gasNew.js

This PR adds support for openethereum/parity revert messages

SafeTxGas calculation: Add check for openethereum/parity revert messages

---

.github/workflows/release.yml
yarn.lock

@mikheevm this PR fixes the conflicts between master and development.
we should merge it to development so I can create the PR from development -> master.

Fix master conflicts

---

.travis.yml

Handle REACT_APP_GNOSIS_APPS_URL env variable to use at build time on Travis CI configuration.

Handle REACT_APP_GNOSIS_APPS_URL env variable on Travis CI configuration

---

.env.example
src/routes/safe/components/Layout/Tabs/index.jsx
src/routes/safe/components/Layout/index.jsx

Adding `REACT_APP_APPS_DISABLED` env. var. to feature-flag Safe apps:
- When env does not exist, apps tab will show up
- When env exists, apps tab will not show up

Add Apps feature flag

---

.env.example
src/routes/safe/components/Layout/Tabs/index.jsx
src/routes/safe/components/Layout/index.jsx

* add Apps feature flag
* re-trigger build

Add Apps feature flag (#842)

---

src/logic/tokens/store/actions/activateAssetsByBalance.js
src/routes/safe/container/Hooks/useFetchTokens.jsx

Fixs #825: Race condition when loading collectibles

---

src/routes/safe/components/Apps/confirmTransactions.js
src/routes/safe/components/Apps/index.jsx
src/routes/safe/components/Layout/Tabs/index.jsx
src/routes/safe/components/Layout/index.jsx
src/utils/url.js

Apps fixes

---

src/routes/safe/components/AddressBook/EllipsisTransactionDetails/index.jsx

(Fix) Click away listener

---

.github/workflows/release.yml

Upload Artifacts when building desktop

---

src/routes/opening/index.jsx

improve calculation of TX mined when creating a Safe

---

src/components/ScanQRModal/ScanQRWrapper/index.jsx
src/logic/addressBook/utils/index.js
src/routes/load/components/DetailsForm/index.jsx
src/routes/safe/components/AddressBook/CreateEditEntryModal/index.jsx
src/routes/safe/components/Balances/SendModal/screens/SendCollectible/index.jsx
src/routes/safe/components/Balances/SendModal/screens/SendCustomTx/index.jsx
src/routes/safe/components/Balances/SendModal/screens/SendFunds/index.jsx
src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/screens/OwnerForm/index.jsx
src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/OwnerForm/index.jsx

Closes #480 
Closes #511 
Adds QR code scan button on the following pages:
- Add Owner
- Replace Owner
- Load Safe
- Create new address book entry
Also fixs the add recipient by qr

(Fix) #511 - QR scan button

---

package.json

Set version to `v2.1.1`

---

src/routes/safe/components/Settings/ManageOwners/index.jsx

(Feature) - Adds copy to clipboard in owners table

---

src/routes/safe/store/middleware/notificationsMiddleware.ts
yarn.lock

Fixes this issue when the safe loads:

(Fix) Load safe error

---

.env.example
src/routes/safe/components/Layout/Tabs/index.tsx
src/routes/safe/components/Layout/index.tsx

This PR:
- Remove env var to disable react apps

Remove env var to disable react apps

---

src/routes/safe/components/Layout/Header/index.tsx

(Fix) - Fix send and receive button icons

---

src/routes/safe/components/Balances/index.tsx

(Fix) - Fixs tab selection

---

src/routes/safe/components/CurrencyDropdown/index.tsx

(Fix) Flags css import

---

package.json
src/logic/contractInteraction/sources/ABIService/index.ts
src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/RenderInputParams/InputComponent/ArrayTypeInput.tsx
src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/RenderInputParams/InputComponent/index.tsx
src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/RenderInputParams/index.tsx
src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/Review/index.tsx
src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/utils/index.ts
yarn.lock

This PR closes #975, by creating an `ArrayTypeInput` to handle and validate solidity array-type values.

(Fix) [Contract Interaction] Support array-like arguments

---

package.json
src/config/development.ts
src/routes/safe/components/Apps/AddAppForm.tsx
src/routes/safe/components/Apps/index.tsx
yarn.lock

hide sapp iframe until it loads completely

---

src/routes/safe/components/Apps/confirmTransactions.tsx

Fix condition in TX sent from safe-apps

---

package.json
yarn.lock

(Fix) `master`-`development` conflicts

---

package.json
yarn.lock

Update onboardjs version

---

src/routes/safe/components/Apps/utils.ts

- Add Aave app from IPFS.
- Remove coming soon apps.

Add Aave app

---

src/routes/safe/components/Apps/utils.ts
yarn.lock

- Add Idle Sapp.
- Update Aave Sapp.
- Sort Apps Alphabetically.
closes #1083.

Add Idle app

---

package.json
src/routes/safe/store/actions/transactions/fetchTransactions/loadOutgoingTransactions.ts

Including 2.5.1 release with a hotfix to development

2.5.1 Dev <- master backmerge

---

package.json
src/routes/safe/components/Apps/utils.ts

This PR:
- Adds 1inch exchange app

Add 1inch app

---

package.json
src/routes/safe/components/Apps/utils.ts

update Request URL

---

package.json
src/routes/safe/components/Apps/utils.ts

This PR backmerges changes from 2.6.1 implemented on master branch

2.6.1 dev <- master backmerge

---

package.json
src/routes/safe/components/Apps/utils.ts

Add Synthetix app. Closes #1117

Add synthetix app

---

src/routes/safe/store/actions/fetchSafe.ts

(BugFix) Add guard type for modules

---

.github/workflows/lint.yml

This PR:
- Changes ESLint action to a different one which generates a nice report with warnings/errors

CI: Use a different ESLint action

---

src/components/CookiesBanner/index.tsx
src/components/Footer/index.tsx
src/routes/load/components/DetailsForm/index.tsx
src/routes/open/components/SafeNameForm/index.tsx
src/routes/welcome/components/Layout.tsx

Replace links and legal text

---

src/routes/safe/components/Apps/utils.ts

As synthetix app is not working correctly on mainnet this app will be disabled for this release

Disable synthetix app for mainnet deployment

---

package.json
src/routes/safe/components/Apps/utils.ts
yarn.lock

Fix: [SafeApps] add app input

---

src/routes/safe/components/Apps/utils.ts

Update Synthetix app IPFS link

Update Synthetix app IPFS link

---

package.json

Create new version to deployment
- Adds fix for build desktop app in windows and linux environment
- Update Synthetix app link

Set v2.7.2

---

GNOSISCLA.md

Add Gnosis CLA

---

src/routes/load/container/Load.tsx

This PR:
- Closes https://github.com/gnosis/safe-react/issues/1195

Bug 1195: Fix safe loading

---

src/routes/safe/components/Layout/Tabs/index.tsx
src/routes/safe/components/Layout/Tabs/style.ts
src/routes/safe/components/Layout/index.tsx
src/routes/safe/components/Layout/style.ts
src/routes/safe/components/Settings/ManageOwners/OwnerAddressTableCell/index.tsx
src/routes/safe/components/Transactions/TxsTable/ExpandedTx/OwnersColumn/OwnerComponent.tsx
src/routes/safe/components/Transactions/TxsTable/ExpandedTx/OwnersColumn/OwnersList.tsx
src/routes/safe/components/Transactions/TxsTable/ExpandedTx/OwnersColumn/index.tsx
src/routes/safe/components/Transactions/TxsTable/ExpandedTx/OwnersColumn/style.ts
src/store/index.ts

(Feature) - 1068 Don't show unknown when unknown

---

.github/workflows/release.yml

Fix - Desktop CI

---

package.json
src/routes/safe/components/Apps/utils.ts

This PR:
- Bumps version to 2.10.0
- Adds OpenZeppelin safe app

V2.10.0: OpenZeppelin app

---

package.json
src/routes/safe/components/Apps/utils.ts

This PR:
- backmerges v2.10.0 release

V2.10.0 backmerge

---

.github/workflows/release.yml
yarn.lock

Fix an issue where windows broke build pipeline before cleaning cache directory

Fix windows directory issue on yarn install

---

src/routes/safe/components/Apps/utils.ts

Update IDLE IPFS link to use latest version
Closes #1287

Update IDLE safe app link

---

src/components/SafeListSidebar/index.tsx
src/routes/safe/components/AddressBook/index.tsx
src/routes/safe/components/Apps/index.tsx
src/routes/safe/components/Balances/Coins/index.tsx
src/routes/safe/components/Balances/Collectibles/index.tsx
src/routes/safe/components/Settings/Advanced/index.tsx
src/routes/safe/components/Settings/ManageOwners/EditOwnerModal/index.tsx
src/routes/safe/components/Settings/ManageOwners/index.tsx
src/routes/safe/components/Settings/ManageOwners/style.ts
src/routes/safe/components/Settings/SafeDetails/index.tsx
src/routes/safe/components/Settings/ThresholdSettings/index.tsx
src/routes/safe/components/Transactions/TxsTable/index.tsx
src/utils/googleAnalytics.ts

Closes https://github.com/gnosis/safe-react/issues/1213
Add the following GA events for specific page views:
SafelistSidebar
Assets
Collectibles
Transactions
Apps (name)
Settings
- SafeDetails
- Owners
- Policies
- Advanced
- SpendingLimits

Track GA for safe actions

---

package.json
src/logic/safe/store/actions/createTransaction.ts
src/logic/safe/store/actions/processTransaction.ts
yarn.lock

This PR backmerges 2.11.0 release to development

Backmerge: Release 2.11.0 to development

---

src/logic/currentSession/store/actions/addViewedSafe.ts
src/logic/currentSession/store/actions/loadCurrentSessionFromStorage.ts
src/logic/currentSession/store/model/currentSession.ts
src/logic/currentSession/store/reducer/currentSession.ts
src/logic/currentSession/utils/index.ts
src/logic/safe/store/actions/utils.ts
src/logic/safe/store/middleware/notificationsMiddleware.ts
src/logic/safe/store/reducer/safe.ts
src/store/index.ts

Fix existent bugs in 1265 PRs that break the app when doing a clean load and when trying to send a transaction

Fix bugs in 1265 strict null checks

---

package.json
src/routes/safe/components/Apps/utils.ts

This release updates Idle app to use v4 contracts and Sablier app to add mUSD token

Release v2.11.1

---

src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/Review/index.tsx
src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/style.ts

(Bugfix) - #925 [Contract Interaction] UI Glitch

---

src/routes/safe/components/Apps/utils.ts

Add Yearn Vaults from Yearn finance

Add Yearn Finance app

---

src/logic/safe/store/actions/updateActiveAssets.ts
src/logic/safe/store/actions/updateActiveTokens.ts
src/logic/safe/store/actions/updateAssetsList.ts
src/logic/safe/store/actions/updateBlacklistedAssets.ts
src/logic/safe/store/actions/updateBlacklistedTokens.ts
src/logic/safe/store/actions/updateTokensList.ts
src/logic/safe/store/middleware/safeStorage.ts
src/logic/safe/store/reducer/safe.ts
src/logic/safe/store/tests/safe.balances.test.ts
src/routes/safe/components/Balances/Tokens/screens/AssetsList/index.tsx
src/routes/safe/components/Balances/Tokens/screens/TokenList/index.tsx

This fixes #1399 
Disabling tokens in the token list is not working correctly.

v2.12.0 Bugfix -  Fix Activate/Blacklist tokens

---

src/components/ConnectButton/index.tsx
src/components/EtherscanBtn/index.tsx
src/components/Header/components/NetworkLabel.tsx
src/components/Header/components/ProviderDetails/UserDetails.tsx
src/components/Header/components/ProviderInfo/ProviderAccessible.tsx
src/config/index.ts
src/logic/wallets/getWeb3.ts
src/logic/wallets/store/actions/fetchProvider.ts
src/logic/wallets/store/model/provider.ts
src/logic/wallets/store/selectors/index.ts
src/logic/wallets/utils/walletList.ts
src/routes/opening/components/Footer.tsx
src/routes/safe/components/Settings/RemoveSafeModal/index.tsx
yarn.lock

This PR adds support for **two additional networks**:
- **Volta Testnet** (id 73799)
- **Energy Web Chain** (id 246)
_Note: Currently still a draft PR, will rebase if needed before merging._

feat: Support for Volta and EWC

---

.travis.yml
package.json

Tweak travis build to generate necessary builds for production environment
Upgrade patch version

New patch version with travis release tweak

---

src/components/forms/AddressInput/index.tsx

(Feature) #1022 - Checksum the address on inputs

---

.travis.yml
src/config/networks/xdai.ts

Add travis configuration to deploy xDai to staging env

Add staging configuration for deployment using xDai

---

package.json
src/routes/safe/components/Apps/utils.ts

Update Sablier app adding the new RLY token

[v2.12.2] - Update Sablier app

---

src/logic/safe/utils/buildSafeCreationTxUrl.ts
src/routes/safe/components/Apps/hooks/useIframeMessageHandler.ts
src/routes/safe/components/Apps/index.tsx
src/routes/safe/components/Transactions/TxsTable/ExpandedTx/CreationTx/index.tsx

This PR fixes some issues that were found during the xDai feature testing.
-

(Fix) xDai feature issues

---

.env.example
src/config/networks/xdai.ts
src/utils/constants.ts

This PR updates the xDai RPC and changes `GOOGLE_ANALYTICS` env variable

(Feature) xDai configs

---

src/components/App/ReceiveModal.tsx
src/components/SafeListSidebar/SafeList/AddresWrapper.tsx
src/routes/open/components/ReviewInformation/index.tsx
src/routes/safe/components/Apps/components/ConfirmTransactionModal.tsx
src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/NativeCoinValue/index.tsx
src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/Review/index.tsx
src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/ReviewCustomTx/index.tsx
src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/SendCustomTx/index.tsx
src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/index.tsx
src/routes/safe/components/Balances/SendModal/screens/ReviewCollectible/index.tsx
src/routes/safe/components/Balances/SendModal/screens/ReviewTx/index.tsx
src/routes/safe/components/Balances/SendModal/screens/SendFunds/index.tsx
src/routes/safe/components/Balances/Tokens/screens/AssetsList/AssetRow.tsx
src/routes/safe/components/Balances/Tokens/screens/TokenList/TokenRow.tsx
src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/screens/Review/index.tsx
src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/screens/Review/index.tsx
src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/Review/index.tsx
src/routes/safe/components/Settings/ThresholdSettings/ChangeThreshold/index.tsx
src/routes/safe/components/Transactions/TxsTable/ExpandedTx/ApproveTxModal/index.tsx
src/routes/safe/components/Transactions/TxsTable/ExpandedTx/RejectTxModal/index.tsx
src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/CustomDescription.tsx
src/routes/safe/components/Transactions/TxsTable/ExpandedTx/index.tsx

(Feature) - Replaces ETH with network native coin

---

package.json
public/electron.js
yarn.lock

Fix electron builder and patch electron version
Get v2.12 ready to release desktop app

Hotfix v2.12.3 - Desktop release

---

src/routes/safe/components/Apps/utils.ts

Update Sablier app

---

src/config/networks/energy_web_chain.ts
src/logic/wallets/ethTransactions.ts

Closes #1531 
- The gas station for EWC seems to have a rounding problem and they are always returning `0`, we added a fixed value for EWC of `1e6` while EWC team check it, meanwhile I also opened an [issue](https://github.com/energywebfoundation/origin/issues/1648) for the ewc team with the possible error (credits to @fernandomg)

(Feature) - #1531 EWC estimate fee on modal

---

src/routes/safe/components/Apps/utils.ts

Remove request app from rinkeby

---

src/logic/collectibles/store/selectors/index.ts
src/routes/safe/components/Balances/Collectibles/index.tsx

(Feature) - #1535 Alphabetical sort collectibles

---

.travis.yml

Add semicolon to fix travis sentry upload documents

Fix travis instruction

---

package.json

Create new version to build and deploy desktop app

Set v2.14.1

---

src/routes/safe/components/Apps/index.tsx

(Feature) - Update legal text

---

src/logic/safe/store/models/safe.ts
src/logic/safe/utils/__tests__/modules.test.ts
src/logic/safe/utils/modules.ts
src/routes/safe/components/Settings/Advanced/ModulesTable.tsx
src/routes/safe/components/Settings/Advanced/RemoveModuleModal.tsx

This PR closes #1367, by:
- changing how the module pair is organized, now it's more natural: (prev, module) tuple
- also added comments to better explain what's going on

(Fix) remove module feature

---

package.json
src/routes/safe/components/Apps/utils.ts

Add Gnosis Custom Market Maker app

Add CMM app

---

config/jest/Web3Mock.js
package.json
src/components/AppLayout/Header/components/Layout.tsx
src/components/hoc/OpenHoc/index.tsx
src/index.tsx
src/logic/contracts/generateBatchRequests.ts
src/logic/hooks/useStateHandler.tsx
src/logic/wallets/getWeb3.ts
src/logic/wallets/store/middlewares/providerWatcher.ts
src/test/utils/accounts.ts
src/types/definitions.d.ts
src/utils/mm_warnings.ts
yarn.lock

closes #1650 
- I have fixed some MM warnings.
- fixed an error in the safe-creation process. 
- did a ~fix~ workaround for this warning
For the other errors reported in the ticket, I could not reproduce them.

Handle console erros and warnings

---

package.json
src/routes/safe/components/Apps/utils.ts
yarn.lock

This is a merge to fix safe-react-components version in `development`

Fix safe-react-components

---

src/components/TransactionsFees/index.tsx
src/components/TransactionsFeesText/index.tsx
src/logic/hooks/useEstimateTransactionGas.tsx
src/logic/safe/safeTxSigner.ts
src/logic/safe/store/actions/__tests__/utils.test.ts
src/logic/safe/store/actions/createTransaction.ts
src/logic/safe/store/actions/processTransaction.ts
src/logic/safe/store/actions/utils.ts
src/logic/safe/transactions/gas.ts
src/routes/safe/components/Apps/components/AppFrame.tsx
src/routes/safe/components/Apps/components/ConfirmTransactionModal.tsx
src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/Review/index.tsx
src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/ReviewCustomTx/index.tsx
src/routes/safe/components/Balances/SendModal/screens/ReviewCollectible/index.tsx
src/routes/safe/components/Balances/SendModal/screens/ReviewTx/index.tsx
src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/screens/Review/index.tsx
src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/screens/Review/index.tsx
src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/Review/index.tsx
src/routes/safe/components/Settings/ThresholdSettings/ChangeThreshold/index.tsx
src/routes/safe/components/Transactions/TxsTable/ExpandedTx/ApproveTxModal/index.tsx
src/routes/safe/components/Transactions/TxsTable/ExpandedTx/OwnersColumn/index.tsx
src/routes/safe/components/Transactions/TxsTable/ExpandedTx/RejectTxModal/index.tsx
src/routes/safe/components/Transactions/TxsTable/ExpandedTx/index.tsx
src/routes/safe/store/actions/transactions/__tests__/utils.test.ts
src/test/signatures.blockchain.ts

Closes #1752 
Depends on #1675

(Feature) Refactor gas calculation

---

src/components/App/index.tsx
src/components/SafeListSidebar/SafeList/AddressWrapper.tsx
src/components/SafeListSidebar/SafeList/index.tsx
src/components/SafeListSidebar/index.tsx
src/logic/safe/store/actions/removeLocalSafe.ts
src/logic/safe/store/reducer/safe.ts
src/routes/open/components/Layout.tsx
src/routes/safe/components/Settings/ManageOwners/EditOwnerModal/index.tsx
src/routes/safe/components/Settings/ManageOwners/index.tsx
src/routes/safe/components/Settings/RemoveSafeModal/index.tsx
src/routes/safe/components/Transactions/TxsTable/ExpandedTx/index.tsx
src/routes/welcome/components/index.tsx
src/routes/welcome/container/index.tsx
src/routes/welcome/container/selector.ts

Closes #441 
Closes #1452 
Closes #1199 
- Not only default safes, the other safes wasn't possible to delete, this pr fixes that

(Fix) - Remove safe fix 

---

src/routes/safe/components/Balances/Coins/styles.ts
src/routes/safe/components/Balances/dataFetcher.ts

(Bug) Value column aligmnet

---

src/routes/safe/components/Apps/components/ConfirmTransactionModal.tsx

Adds `estimationFees` component within the review tx app modal to check if the safe app transaction will fail or not

(Feature) Estimate gas safe apps

---

package.json
src/logic/safe/store/actions/__tests__/transactionHelpers.test.ts
src/logic/safe/store/actions/transactions/utils/transactionHelpers.ts
src/logic/wallets/ethAddresses.ts

(Hotfix) Refund displayed as transaction rejection

---

src/routes/safe/components/Apps/utils.ts

Update 1 Inch app to v1.2.3

---

src/routes/safe/components/Apps/utils.ts

Closes #1718 update IDLE Safe app with a different Infura ID

Update IDLE Safe app

---

.travis.yml
src/routes/safe/components/Apps/utils.ts

Add  dHedge safe app
@francovenica This app only works on mainnet. Can be tested using this link:
https://ipfs.io/ipfs/QmaiemnumMaaK9wE1pbMfm3YSBUpcFNgDh3Bf6VZCZq57Q/

Add dHedge safe app

---

package.json
src/logic/safe/transactions/gas.ts

- Check that the estimation of the node is bigger than 0 before returning the valid gas amount

(Hotix) - xDAI Gas estimation fix 

---

package.json
src/components/TransactionsFees/index.tsx
src/index.tsx
src/logic/safe/transactions/gas.ts
src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/index.tsx
src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/index.tsx
src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/screens/Review/index.tsx
src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/index.tsx
src/routes/safe/components/Settings/SpendingLimit/NewLimitModal/Review.tsx

Merge latest release fixes back to development

Merge release v2.19.0 back to development

---

src/routes/safe/components/Transactions/GatewayTransactions/HistoryTxList.tsx
src/routes/safe/components/Transactions/GatewayTransactions/TxCollapsed.tsx
src/routes/safe/components/Transactions/GatewayTransactions/TxInfoCreation.tsx
src/routes/safe/components/Transactions/GatewayTransactions/TxSummary.tsx
src/routes/safe/components/Transactions/GatewayTransactions/styled.tsx
src/routes/safe/components/Transactions/GatewayTransactions/utils.ts
src/utils/date.ts

Add relative times in tx-v2 queue lists.

Add relative time in queue lists

---

src/routes/safe/components/Transactions/GatewayTransactions/styled.tsx

This PR closes #1870, by fixing styles for grid rows

[Transaction List v2] Dark row beneath safe creation tx

---

src/routes/safe/components/Transactions/GatewayTransactions/MethodDetails.tsx
src/routes/safe/components/Transactions/GatewayTransactions/TxData.tsx

This PR closes #1874, by adding the `TxInfoDetails` where missing.

[Transaction List v2] - "Send to" action missing 

---

src/logic/safe/store/reducer/gatewayTransactions.ts
src/utils/date.ts

| before | after fix |
|---|---|
|![image](https://user-images.githubusercontent.com/3315606/107574153-1f263f00-6bcd-11eb-80fe-03a8ae5f361a.png)|![image](https://user-images.githubusercontent.com/3315606/107573960-f3a35480-6bcc-11eb-8b40-ef0f1944213a.png)|

[Transaction List v2] Adjust tx-date grouping to Local TZ

---

src/routes/safe/components/Transactions/GatewayTransactions/hooks/useActionButtonsHandlers.ts

[Transaction List v2] Update buttons status after confirm

---

src/routes/safe/components/Transactions/GatewayTransactions/TxInfoDetails.tsx

[Transaction List v2] Prevent "Send Again" for ERC721 transfers

---

src/logic/safe/store/actions/processTransaction.ts
src/logic/safe/store/reducer/gatewayTransactions.ts

[Transaction List v2] Pending status only if user signs the tx

---

src/routes/safe/components/Settings/ThresholdSettings/ChangeThreshold/index.tsx
src/routes/safe/components/Settings/ThresholdSettings/index.tsx

Closes #1898 
We fix gas check for threshold update transactions

Fix safe tx parameters not used in threshold change

---

src/routes/safe/components/Transactions/helpers/EditTxParametersForm/index.tsx

Fix link in advanced params

---

package.json
src/routes/safe/components/Settings/ThresholdSettings/ChangeThreshold/index.tsx
src/routes/safe/components/Transactions/helpers/EditableTxParameters.tsx

- Threshold can not be changed ( #1919 )
- Threshold value not stored when editing transaction parameters ( #1905 )

Hotfix v3.0.1

---

src/logic/safe/store/actions/createTransaction.ts
src/routes/safe/container/hooks/useTransactionParameters.ts

Closes #1775
There was a problem with the solution proposed in #1886 
This PR is created to fix it

Fix nonce 0 check

---

src/logic/hooks/useEstimateTransactionGas.tsx
src/logic/safe/transactions/gas.ts

Closes #1938.
Add to the estimated gas the gas required to estimate signatures (threshold * 7000)

Fix gas estimation

---

.github/workflows/deploy-ewc.yml
.github/workflows/deploy-mainnet.yml
.github/workflows/deploy-rinkeby.yml
.github/workflows/deploy-volta.yml
.github/workflows/deploy-xdai.yml

Fix script route with missing folder

Fix wrong script route in S3 deployment

---

.github/workflows/deploy-rinkeby.yml

Fix branch name to development deployment

Change develop to development branch name

---

src/routes/safe/components/Apps/utils.ts

This PR:
- Updates wc app to the new version with a bugfix for `eth_sign`: https://github.com/gnosis/safe-react-apps/issues/100

Feature: Update wc app

---

src/logic/safe/transactions/txHistory.ts

Update name of deprecated transaction service endpoint

Update endpoint to use new name

---

src/routes/safe/components/Transactions/GatewayTransactions/hooks/usePagedHistoryTransactions.ts

Description:
- Fixes the infinite loading gift

(Fix) Transaction list infinite loading

---

src/routes/safe/components/Transactions/GatewayTransactions/TxOwners.tsx
src/routes/safe/components/Transactions/GatewayTransactions/hooks/useTransactionActions.ts

Fix execute if collected signs is > to threshold

---

src/routes/safe/components/Apps/utils.ts

This PR:
- Updates static app list by adding lido finance app

 Feature: Add lido finance app

---

src/routes/safe/components/Apps/utils.ts

This PR:
- Closes https://github.com/gnosis/safe-react/issues/1945 by adding the app to static app list
Testing vids
https://www.loom.com/share/e3b3ddf1764648dcb8077a01c70d11c6
https://www.loom.com/share/9133af2d6b444abf85ef9af77327b8cf

Feature: Add pooltogether safe app

---

src/logic/hooks/useEstimateTransactionGas.tsx

fix isExecute inuseEstimateTransactionGas

---

.github/workflows/deploy-ewc.yml
.github/workflows/deploy-mainnet.yml
.github/workflows/deploy-rinkeby.yml
.github/workflows/deploy-volta.yml
.github/workflows/deploy-xdai.yml
package.json

Fix to upload files to correct server in production deploy

Fix v3.1.1. Production deploy

---

.github/workflows/deploy-ewc.yml
.github/workflows/deploy-mainnet.yml
.github/workflows/deploy-rinkeby.yml
.github/workflows/deploy-volta.yml
.github/workflows/deploy-xdai.yml
package.json

Fix tagged builds not using production services

Enable production builds for tagged builds in CI

---

.github/workflows/deploy-ewc.yml
.github/workflows/deploy-mainnet.yml
.github/workflows/deploy-rinkeby.yml
.github/workflows/deploy-volta.yml
.github/workflows/deploy-xdai.yml
package.json

Merge CI fixes for production deployment back to development

Mergeback CI fixes to development

---

package.json
yarn.lock

Reverts gnosis/safe-react#1995

Revert "Fix - Copy to clipboard button prevents submit"

---

package.json
yarn.lock

Reverts gnosis/safe-react#2001

Revert "Revert "Fix - Copy to clipboard button prevents submit""

---

src/logic/safe/transactions/gas.ts

Closes #1970 and #1975
We were trusting safeTxGas would be enough or we would should a "transaction would fail" message when all signatures are gathered and only execution is pending.
But safeTxGas 0 means that the operation can use up to all gasLimit if necessary to execute the operation.
In this case we have to assume this is a correct safeTxGas but estimate the value in order to set a correct gasLimit so transaction will be correctly executed

Fix wrong estimation when only executing and selected safeTxGas is 0

---

src/routes/open/components/fields.ts

This PR closes #2004, by adding leading zeroes to the form field counter.

(Fix) Wrong owners name assignment on Safe Load

---

src/components/forms/validator.ts

Closes #2051 
Steps to test:
Go to 'New transaction' button. Then 'Contract interaction'
Complete Contract Address input with '0x5eC429cB23bC903DeeB8112334a576A0c091a7d0'

(Fix) change error message Contract address input

---

src/logic/safe/hooks/useLoadSafe.tsx

No issue related.
I just saw this error and I'm fixing it.

Fxi: Add missing dependency for useEffect

---

src/routes/safe/components/Transactions/TxList/TxSummary.tsx

Closes #1641.
Add safeTxHash in transaction details for queue and history.

Add safeTxHash in Txs queue & history

---

src/config/networks/rinkeby.ts

Disable Fortmatic on Rinkeby

---

package.json
src/logic/tokens/store/actions/fetchSafeTokens.ts

A hotfix:
* remove exponential back-off strategy for balance fetching (#2225)

Release 3.5.2 🔥 

---

package.json
src/logic/tokens/store/actions/fetchSafeTokens.ts

A hotfix:
* remove exponential back-off strategy for balance fetching (#2225)

Backmerge 3.5.2

---

package.json

Backmerge from master 3.5.2

---

package.json
src/components/Modal/index.tsx
src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/style.ts

Backmerge 3.6.0

---

readme.md

The readme had one last mention of Flow that isn't used anymore.
Also edited a few lines of text.

Remove Flow from the readme

---

readme.md

Changed http:// to https:// on SemVer link in readme.md

Changed http:// to https:// on SemVer link

---

src/components/App/index.tsx
src/components/SafeListSidebar/SafeList/AddressWrapper.tsx
src/components/SafeListSidebar/index.tsx
src/logic/addressBook/hooks/useSafeName.tsx
src/logic/addressBook/utils/index.ts
src/logic/safe/store/selectors/index.ts
src/routes/load/components/DetailsForm/index.tsx
src/routes/safe/components/Apps/components/AppFrame.tsx
src/routes/safe/components/Apps/hooks/useIframeMessageHandler.ts
src/routes/safe/components/Balances/index.tsx
src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/screens/Review/index.tsx
src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/screens/Review/index.tsx
src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/Review/index.tsx
src/routes/safe/components/Settings/ManageOwners/index.tsx
src/routes/safe/components/Settings/RemoveSafeModal/index.tsx
src/routes/safe/components/Settings/SafeDetails/index.tsx

**What**:
Closes #2240 #2252 
This PR is intended to do a check on the address book add, update and remove events. It will ensure that in each place where a name can be added or edited its value is stored in the address book
**Why**:
We want to ensure that we use a central source of truth, and so we are relaying on the address book to create the relationship between an address and a name, instead of keeping update in two places for the case of safe owners and an added safe
**How**:
I did a review of all places where an address name can be edited and ensured that this changes were persisted in the address book. Then I also ensured that on every place that we show an address name this value is picked from the address book
**Checklist**:

[Address book v2] Address book update events

---

src/logic/wallets/getWeb3.ts

**What:**
Closes #2301
**How to test it:**
I wasn't able to replicate it. In the linked issue there are more details.
**Checklist:**

Catch the TypeError which occours when contractCode is undefined

---

package.json
src/components/AppLayout/Header/components/WalletIcon/icons/icon-coinbase.svg
src/components/AppLayout/Header/components/WalletIcon/icons/index.ts
src/logic/wallets/getWeb3.ts

- Safe crashing when connecting with Coinbase Wallet owner (#2359)

Hotfix v3.6.6

---

package.json

Merge back v3.6.7

---

src/logic/addressBook/store/selectors/index.ts
src/logic/addressBook/utils/__tests__/addressBookUtils.test.ts
src/logic/addressBook/utils/index.ts
src/logic/safe/store/selectors/index.ts
src/routes/load/components/OwnerList/index.tsx
src/routes/open/components/Layout.tsx
src/routes/open/components/SafeOwnersConfirmationsForm/index.tsx
src/routes/safe/components/AddressBook/CreateEditEntryModal/index.tsx
src/routes/safe/components/AddressBook/EllipsisTransactionDetails/index.tsx
src/routes/safe/components/AddressBook/ExportEntriesModal/index.tsx
src/routes/safe/components/AddressBook/index.tsx
src/routes/safe/components/Balances/SendModal/screens/AddressBookInput/index.tsx
src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/Review/index.tsx
src/routes/safe/components/Balances/SendModal/screens/SendCollectible/index.tsx
src/routes/safe/components/Balances/SendModal/screens/SendFunds/index.tsx
src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/screens/OwnerForm/index.tsx
src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/OwnerForm/index.tsx
src/routes/safe/components/Settings/SpendingLimit/FormFields/Beneficiary.tsx
src/routes/safe/components/Settings/SpendingLimit/InfoDisplay/AddressInfo.tsx
src/routes/safe/components/Transactions/TxList/OwnerRow.tsx
src/routes/safe/components/Transactions/TxList/hooks/useKnownAddress.ts

Address Book selectors
- Following with what was done in #2357 for Safe selectors.
- Replacing helper functions with selectors whenever was possible
Everything should work as before.

[Address Book v2] - Refactor addressBook selectors

---

package.json
src/logic/addressBook/utils/v2-migration.ts

Back-merge master

---

README.md

Added this diagram to the readme:

Add app diagram in the readme

---

src/components/CookiesBanner/index.tsx
src/logic/hooks/useSafeAppUrl.tsx
src/routes/safe/components/Apps/index.tsx

Closes #2238
Checks if the current view is the safe app view and hides the intercom
Enter any safe app view and check if intercom is hidden in the bottom right side

Hide intercom insde safe app view

---

src/routes/safe/components/Balances/SendModal/screens/ReviewSendFundsTx/index.tsx

Adds a data test id for the e2e tests
Adds the data test id so the e2e test can test it
Use this branch to test the send funds e2e test

Send funds e2e test fix

---

package.json
src/components/AppLayout/Sidebar/SafeHeader/index.tsx
src/components/ButtonHelper/index.tsx
src/routes/safe/components/AddressBook/style.ts
yarn.lock

#2433 needs to be merged to development.

Add hover state to Icons (#2433)

---

src/logic/contracts/safeContracts.ts

For some reason the code wasn't prettified before merging.

Format safeContracts.ts

---

package.json
yarn.lock

Solves issues with Ledger and Chrome
Bump bnc-onboard to latest version that includes a fix to deal with this
Test that connection and transaction sending is working with all wallets, at least on Rinkeby, specially Ledger in Chrome

Bump bnc-onboard to latest version

---

.github/workflows/deploy-mainnet.yml

As per @liliya-soroka's request, restore automatic mainnet deployments removed in #2449.

Restore mainnet deployments in PRs

---

package.json
src/logic/addressBook/utils/index.ts
src/logic/addressBook/utils/v2-migration.ts

A hot fix for address autocomplete

Release 3.8.2

---

package.json
src/logic/addressBook/utils/index.ts
src/logic/addressBook/utils/v2-migration.ts

Back-merge main into dev

---

src/config/networks/bsc.ts

Enable Apps section on BSC network

Enable apps for BSC

---

docs/release-procedure.md

There was a minor readme edit on main to re-trigger a build.

Back-merge main

---

src/routes/open/components/ReviewInformation/index.tsx

Resolves https://github.com/gnosis/safe-react-e2e-tests/issues/12
Added a test id where it's needed
Run the create safe test using this pr

Fix create safe e2e test

---

scripts/github/prepare_production_deployment.sh

The reference is to the gitlab project branch, not this repo.

Fix prod deployment: main -> master

---

package.json
src/components/AppLayout/Sidebar/useSidebarItems.tsx

Merge last changes for release v3.10.0 to dev

Merge back Release 3.10.0

---

.github/workflows/comment-on-e2e-success.yml

Resolves [Issue](https://github.com/gnosis/safe-react-e2e-tests/issues/38)
Check status with 'success' and 'failure'

Check test status with a string

---

package.json
src/routes/safe/components/Settings/RemoveSafeModal/index.tsx

Backmerge release v3.11.0 to dev

---

.github/workflows/comment-on-e2e-success.yml

Resolves [Issue](https://github.com/gnosis/safe-react-e2e-tests/issues/37)
Comments the thread with the link to the e2e run related to the current PR

Added comment with link to the current e2e run

---

.github/workflows/comment-on-e2e-success.yml

Hotfix on the link in the e2e tests result comment on each PR

Fixed link on e2e test comment

---

src/config/index.ts
src/config/networks/bsc.ts
src/config/networks/energy_web_chain.ts
src/config/networks/local.ts
src/config/networks/mainnet.ts
src/config/networks/network.d.ts
src/config/networks/polygon.ts
src/config/networks/rinkeby.ts
src/config/networks/volta.ts
src/logic/exceptions/registry.ts
src/logic/wallets/ethTransactions.ts

Resolves #2579 
The oracle variable from where we get the gasPrices is now a list so we can fallback into other sources.

Get gasprice from multiple oracles and edited config files

---

src/logic/wallets/ethTransactions.ts

Deletes some console logs that aren't needed

Deleted console logs

---

.github/workflows/deploy-rinkeby.yml

Renamed repository dispatch

---

src/routes/safe/components/AddressBook/ImportEntriesModal/index.tsx

Resolves #2648 
When importing, empty rows get deleted

Delete empty csv empty rows

---

package.json
src/logic/safe/transactions/txHistory.ts
yarn.lock

Updates the Gateway SDK package and adjusts the propose call.
* Make a transaction
* It should work like before

Update the gateway SDK and the propose call

---

package.json
src/components/ConnectButton/index.tsx
src/logic/addressBook/store/selectors/index.ts
src/logic/safe/store/actions/createTransaction.ts

Merge main back into dev

---

.github/workflows/cla.yml
src/components/GlobalErrorBoundary/__tests__/index.test.ts
src/components/GlobalErrorBoundary/index.tsx
src/utils/storage/index.ts
src/utils/wrapInSuspense.tsx

Resolves #2693 
Error boundary checks for chunk failure and reloads app if no prior chunk failure reload occurred within the last 10 seconds.
Disable chunk(s) in Network tab and test app.

Chunk loading error

---

.github/workflows/cla.yml

When you sign the CLA, it doesn't re-trigger the action.
Relaxes the re-trigger condition.
This PR is testing it.

Fix the re-triggering of the CLA action

---

package.json
src/logic/hooks/useEstimateTransactionGas.tsx
src/logic/safe/store/actions/__tests__/transactionHelpers.test.ts
src/logic/safe/store/actions/createTransaction.ts
src/logic/safe/store/actions/processTransaction.ts
src/logic/safe/store/models/types/transaction.ts
src/logic/safe/transactions/gas.ts
src/routes/safe/components/Apps/components/ConfirmTxModal/ReviewConfirm.tsx
src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/Review/index.tsx
src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/ReviewCustomTx/index.tsx
src/routes/safe/components/Balances/SendModal/screens/ReviewCollectible/index.tsx
src/routes/safe/components/Balances/SendModal/screens/ReviewSendFundsTx/index.tsx
src/routes/safe/components/Settings/Advanced/RemoveGuardModal.tsx
src/routes/safe/components/Settings/Advanced/RemoveModuleModal.tsx
src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/index.tsx
src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/screens/Review/index.tsx
src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/index.tsx
src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/screens/Review/index.tsx
src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/index.tsx
src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/Review/index.tsx
src/routes/safe/components/Settings/SpendingLimit/NewLimitModal/Review.tsx
src/routes/safe/components/Settings/SpendingLimit/RemoveLimitModal.tsx
src/routes/safe/components/Settings/ThresholdSettings/ChangeThreshold/index.tsx
src/routes/safe/components/Settings/UpdateSafeModal/index.tsx
src/routes/safe/components/Transactions/TxList/modals/ApproveTxModal.tsx
src/routes/safe/components/Transactions/TxList/modals/RejectTxModal.tsx
yarn.lock

Resolves https://github.com/gnosis/safe-react-gateway-sdk/issues/17

Change baseGas and safeTxGas to string

---

package.json
src/components/GlobalErrorBoundary/index.tsx
src/config/networks/bsc.ts
yarn.lock

Merge latest changes from v3.14.1 to dev

Merge back release v3.14.1 to dev

---

src/logic/safe/hooks/useSafeScheduledUpdates.tsx
src/logic/tokens/store/actions/fetchSafeTokens.ts
src/routes/safe/components/CurrencyDropdown/index.tsx

Resolves #2752
Calls a balance update action when selecting a currency.
Try switching the currency.
Try throttling the network to check that it won't switch it until tokens are fetched.

Fix token fetching on currency switch

---

src/logic/safe/hooks/useLoadSafe.tsx

Effect loop causing continuous polling.
Remove continuous state setting and add depancy.

Fix polling effect loop

---

public/migrate-local-storage.html

Resolves #2632
This PR is purely to include the iframe that we will later use for localStorage migration in the upcoming release.

Add iframe for later localStorage migration

---

src/config/networks/mainnet.ts
src/config/networks/rinkeby.ts

Resolves #2792
Temporarily disables GridPlus until it's fixed in onboard.js

Fix: temporarily disable GridPlus (Lattice)

---

src/logic/wallets/ethTransactions.ts

Fix EthAdapterTransaction import from Core SDK

---

src/components/SafeListSidebar/SafeList/SafeListItem.tsx
src/components/SafeListSidebar/SafeList/index.tsx
src/logic/safe/hooks/useLocalSafes.tsx
src/routes/routes.ts
src/utils/checksumAddress.ts

Resolves #3005
Every address used in the sidebar is checksummed.
Add a duplicate safe to the state and check that it isn't displayed twice.

Fix: checksum sidebar addresses

---

.github/workflows/comment-on-e2e-success.yml
.github/workflows/deploy.yml

Adds a direct link for xDai deployment and colored circles

Chore: add xDai to the PR link list

---

package.json
src/components/SafeListSidebar/SafeList/SafeListItem.tsx
src/components/SafeListSidebar/SafeList/index.tsx
src/config/networks/arbitrum.ts
src/config/networks/rinkeby.ts
src/config/networks/xdai.ts
src/logic/safe/hooks/useLocalSafes.tsx
src/routes/routes.ts
src/utils/checksumAddress.ts

* Fix: duplicate Safes in sidebar, safes loaded from a URL
* Fix: dynamic gas price on xDai and Arbitrum

Release 3.15.3

---

.dockerignore
Dockerfile
docker-compose.yml

Fix: docker compose build

---

package.json
src/components/AppLayout/AppLayout.stories.tsx
src/routes/welcome/Welcome.tsx
yarn.lock

Remove Multisig from a piece of text on the Welcome page.
Also install a missing dev dependency.

Fix: rm Multisig in copy

---

src/logic/wallets/getWeb3.ts

Resolves #3081
Same as:
Issue: #3032
PR: #3034

Fix ENS resolver fn using getWeb3ReadOnly

---

src/logic/exceptions/CodedException.test.ts
src/logic/exceptions/CodedException.ts
src/setupTests.js

I dunno why they broke, but moving the mocks to the top of describe seems to have helped.

Fix CodedException tests

---

package.json
src/logic/safe/store/models/types/gateway.d.ts
src/routes/safe/components/Transactions/TxList/MultiSendDetails.tsx
src/routes/safe/components/Transactions/TxList/TxInfoMultiSend.tsx
src/routes/safe/components/Transactions/TxList/TxSummary.tsx
src/routes/safe/components/Transactions/TxList/styled.tsx

- Multisend contract addresses are now shown
- Delegate calls to unknown addresses now show a warning

Release 3.15.6 🔥 

---

src/logic/safe/store/actions/createTransaction.ts

Comments out the navigating to a specific tx.

Chore: disable tx deep link navigation

---

src/logic/wallets/ethTransactions.ts

This was a workaround that we don't need/want anymore.

Fix: remove the fixed extra 2.5 Gwei gas price

---

src/components/AppLayout/Sidebar/useSidebarItems.tsx

Unhides the Appearance SideBar item

Fix: unhide Appearance page

---

src/components/SafeListSidebar/SafeList/SafeListItem.tsx
src/logic/safe/utils/mocks/remoteConfig.json
src/logic/safe/utils/safeStorage.ts
src/utils/storage/Storage.ts
src/utils/storage/__tests__/index.test.ts
src/utils/storage/__tests__/local.test.ts
src/utils/storage/index.ts

Release fixes

---

src/components/AppLayout/Sidebar/DebugToggle/index.tsx
src/components/AppLayout/Sidebar/index.tsx
src/logic/safe/utils/mocks/remoteConfig.json
src/utils/constants.ts
src/utils/storage/Storage.ts

Adds a switch in the sidebar to enable production CGW on dev/staging.

Chore: add a debug toggle for prod CGW

---

src/logic/safe/store/actions/utils.ts

Resolves #3190
Returns the maximum nonce between the reducer and the current safe nonce

Fix: do not return a nonce smaller than the current Safe nonce

---

src/logic/safe/store/reducer/gatewayTransactions.ts
src/routes/routes.ts
src/routes/safe/components/Transactions/TxList/TxShareButton.tsx
src/routes/safe/components/Transactions/TxList/TxSingularDetails.tsx
src/routes/safe/components/Transactions/TxList/TxSummary.tsx
src/routes/safe/components/Transactions/TxList/hooks/useQueueTransactions.ts
src/routes/safe/container/index.tsx

Reverts gnosis/safe-react#3210

Revert "Fix: deeplinked, out of nonce order transactions allow confirmation "

---

.github/workflows/cla.yml
src/components/SafeListSidebar/SafeList/SafeListItem.tsx
src/logic/safe/utils/mocks/remoteConfig.json

Resolves #2925
Changed the Add Safe Link to a Button Element
- Open the Safe List Sidebar
- Hover over "Add Safe" next to an existing Safe

Fix: Increase clickable area of Add Safe button

---

src/logic/safe/store/reducer/gatewayTransactions.ts

Resolves #3292
Existing transactions in the history payload are no longer cached and instead overwritten with the 'fresh' data instead.
This is trivial to test, but the current cancel bug that we are experiencing is a good reference to use: (aka no manul refresh needed)
1. Create a transaction and execute it immediately on a 1/? Safe.
2. Copy the (deeplink) URL and open it immediately in another tab. The status should show that it is cancelled.
3. Remain in the new tab and observe that after the automatic polling, the status should now update.
Note: we were able to reproduce this on production Rinkeby on a 1/1 Safe.

Do not cache transactions from history payload

---

package.json
src/components/AppLayout/Sidebar/DevTools/index.tsx
src/components/AppLayout/Sidebar/index.tsx
src/components/Root/LegacyRouteRedirection.tsx
src/routes/safe/components/Balances/SendModal/screens/SendFunds/TokenSelectField/index.tsx
yarn.lock

A basic implementation of Safe-related developer tools are now visible in the sidebar when not in the production envrionment. 
These include links to:
- Transaction queue
- Transaction history
- Safe status (courtest of Richard's personal tool)
Macros for:
- Creating a queued transaction
- Creeating and immediately executing a transaction (where possible)
These can, of course, be improved and expanded upon in the future.

Developer tools

---

src/components/Root/LegacyRouteRedirection.tsx
src/config/__tests__/index.test.ts
src/config/chain.d.ts
src/logic/addressBook/store/__tests__/addressBookReducer.test.ts
src/logic/safe/transactions/__tests__/gas.test.ts
src/utils/storage/index.ts

Resolves #3315
Replaces them with string literals. No bueno, but it's mostly tests.
Everything should work like before when switching networks.

chore: clean up CHAIN_ID

---

package.json
src/routes/safe/components/Apps/components/AppFrame.tsx
src/routes/safe/components/Apps/hooks/useIframeMessageHandler.ts
src/routes/safe/components/Apps/utils.ts

Merge back hotfix v3.17.2

---

.github/workflows/cla.yml
src/utils/constants.ts

Resolves #
Configurable default chain via env var.
Reads the env var!

configure default chain via env var

---

src/routes/safe/components/Transactions/TxList/TxDataRow.tsx
src/routes/safe/components/Transactions/TxList/TxSummary.tsx
src/routes/safe/components/Transactions/helpers/TxModalWrapper/index.tsx

Addresses small code improvements proposed in https://github.com/gnosis/safe-react/pull/3373

refactor: Advanced tx data code improvements

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/PULL_REQUEST_TEMPLATE.md

I've added structured markup to the bug template, so that it's easier to fill out details.
Also added a section about Analytics in the PR template.

chore: update issue & PR templates

---

.github/workflows/codeql-analysis.yml
src/components/forms/validator.test.ts
src/components/forms/validator.ts

Trying out this code analyser thing.

chore: create codeql-analysis.yml

---

package.json

Merging release v3.19.0 from `main` into `dev`

chore: merge v3.19.0 from `main` into `dev`

---

src/logic/wallets/onboard.ts
src/logic/wallets/pairing/utils.ts

Release 3.20.0 – followup fix

---

.github/workflows/cla.yml

Removes an external contributor from the CLA allowlist

fix: Remove external contributor from CLA allowlist

---

src/components/AppLayout/Footer/Footer.test.tsx
src/components/AppLayout/Sidebar/index.tsx
src/components/CookiesBanner/index.tsx
src/logic/cookies/utils/index.ts
src/routes/safe/components/Apps/components/AppsList.test.tsx
src/routes/safe/components/Apps/hooks/appList/useCustomSafeApps.ts
src/routes/safe/components/Apps/hooks/appList/usePinnedSafeApps.ts
src/utils/beamer.ts
src/utils/googleAnalytics.ts
src/utils/intercom.ts
src/utils/storage/Storage.ts

The CookieBanner was a hot mess and wasn't saving the state when changing two values at the same time.

Fix: remove Beamer LS + refactor CookieBanner

---

.github/workflows/deploy.yml

Relates to #3515 
Adds the Beamer ID env variable to `deploy.yml` for prod build.

chore: Add beamer id env to deploy.yml

---

.github/workflows/mint.yml

The success comment wasn't being posted after minting an NFT.

Chore: fix mint comment job

---

src/components/AppLayout/Header/components/ProviderDetails/PairingDetails.tsx
src/components/AppLayout/Header/components/ProviderDetails/hidePairingModule.css
src/components/CookiesBanner/index.tsx

3.21.0 follow-ups

---

src/routes/CreateSafePage/steps/NameNewSafeStep.tsx
src/routes/LoadSafePage/steps/LoadSafeAddressStep.tsx

Resolves #1129
The legal text has been updated to:
> By continuing you consent to the terms of use and privacy policy.
Open load/create Safe stepper and observe the updated text.

fix: update legal text

---

src/logic/safe/store/reducer/gatewayTransactions.ts

Resolves https://sentry.io/organizations/gnosis/issues/3096665536/?project=5436884&query=is%3Aunresolved

Fix: clonedStoredTxs can be undefined

---

src/routes/LoadSafePage/steps/ReviewLoadStep.tsx

Resolves #3673
Sets "md" instead of "lg".

Fix: font-size in Load Safe review step

---

src/logic/collectibles/sources/Gnosis.ts
src/logic/collectibles/sources/collectibles.d.ts
src/logic/collectibles/store/reducer/collectibles.ts
src/logic/collectibles/store/selectors/index.ts
src/routes/safe/components/Balances/Collectibles/index.tsx

Adds a loading state by modifying the stored NFTTokens type.

Fix: add a Loading state for Collectibles

---

cypress.json
cypress/integration/landing.spec.js
cypress/support/index.js
package.json
yarn.lock

Adds Cypress to the repo
Run `yarn cypress:open` to display the test suit

Chore: add Cypress

---

src/logic/safe/hooks/useSafeScheduledUpdates.tsx

Missing effect dependency
https://github.com/gnosis/safe-react/pull/3728 was merged with a missing effect dependency. This add its.

fix: missing dependency

---

src/components/Dashboard/AddSafe.tsx
src/components/Dashboard/CreateSafe.tsx
src/routes/Home/index.tsx

Dashboard: create/add safe widgets

---

package.json
src/components/AppLayout/Sidebar/useSidebarItems.tsx
src/routes/routes.ts
src/routes/safe/components/Balances/Collectibles/index.tsx
src/routes/safe/components/Balances/SendModal/screens/ChooseTxType/index.tsx
src/routes/safe/components/Balances/SendModal/screens/ReviewCollectible/index.tsx
src/routes/safe/components/Balances/SendModal/screens/SendCollectible/index.tsx
src/routes/safe/components/Balances/index.tsx
src/routes/safe/container/index.tsx

* Fix: rename Collectibles to NFTs (#3768)

Release 3.23.2

---

package.json
src/logic/appearance/actions/toggleBatchExecute.ts
src/logic/appearance/reducer/appearance.ts
src/logic/appearance/selectors/index.ts
src/logic/exceptions/registry.ts
src/logic/safe/store/actions/TxMultiSender.ts
src/logic/safe/store/actions/fetchTransactionDetails.ts
src/logic/safe/store/selectors/__tests__/gatewayTransactions.test.ts
src/logic/safe/store/selectors/gatewayTransactions.ts
src/logic/safe/store/selectors/pendingTransactions.ts
src/logic/safe/transactions/multisend.ts
src/routes/safe/components/Settings/Advanced/Advanced.test.tsx
src/routes/safe/components/Settings/Advanced/index.tsx
src/routes/safe/components/Transactions/TxList/BatchExecute.tsx
src/routes/safe/components/Transactions/TxList/BatchExecuteHoverProvider.tsx
src/routes/safe/components/Transactions/TxList/QueueTransactions.tsx
src/routes/safe/components/Transactions/TxList/TxQueueRow.tsx
src/routes/safe/components/Transactions/TxList/styled.tsx
src/routes/safe/components/Transactions/TxList/utils.ts
src/utils/events/txList.ts

* feat: Add multi send option for queued transactions (#3705)

Release 3.24.0

---

src/routes/opening/index.tsx

Resolves #3773
Although I wasn't able to reproduce the bug, I adjusted the code to remove the error state when the Safe is created successfully.
🤷

Fix: reset error on success

---

src/components/Dashboard/Overview/Overview.tsx
src/logic/collectibles/sources/Gnosis.ts
src/logic/collectibles/sources/collectibles.d.ts
src/logic/collectibles/store/actions/addCollectibles.ts
src/logic/collectibles/store/actions/fetchCollectibles.ts
src/logic/collectibles/store/reducer/collectibles.ts
src/logic/collectibles/store/selectors/index.ts
src/logic/safe/store/actions/fetchSafe.ts
src/logic/safe/store/models/safe.ts
src/logic/safe/store/reducer/safe.ts
src/logic/safe/store/selectors/index.ts
src/logic/safe/utils/__tests__/shouldSafeStoreBeUpdated.test.ts
src/logic/tokens/store/actions/fetchSafeTokens.ts
src/routes/Home/index.tsx
src/routes/safe/container/index.tsx
src/store/index.ts

Resolves #3785 
Adds an overview widget to the dashboard
2. Select a Safe
3. Observe the Overview Widget at the top left of the screen

feat: Add Overview widget for dashboard

---

src/components/AppLayout/index.tsx
src/components/Dashboard/FeaturedApps/FeaturedApps.tsx
src/components/Dashboard/PendingTxs/PendingTxsList.tsx
src/components/Dashboard/SafeApps/Card.tsx
src/components/Dashboard/SafeApps/Grid.tsx
src/routes/Home/index.tsx
src/routes/safe/components/Apps/components/AppFrame.tsx
src/routes/safe/components/Transactions/TxList/styled.tsx

fix: Dashboard styles

---

package.json

Hotfix v3.24.1

---

docs/environments.md

Docs on how we work on features and which environments we use.

Docs: app environments and deployments

---

docs/release-procedure.md

Docs: add info about hotfix releases

---

src/components/AppLayout/Header/components/KeyRing.tsx
src/components/AppLayout/Header/components/NetworkSelector.tsx
src/components/FlexSpacer/index.tsx
src/components/GlobalErrorBoundary/index.tsx
src/components/ReviewInfoText/index.tsx
src/routes/safe/components/AddressBook/ExportEntriesModal/index.tsx
src/routes/safe/components/Apps/components/ConfirmTxModal/SafeAppLoadError.tsx
src/routes/safe/components/Balances/SendModal/screens/AddressBookInput/index.tsx
src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/EthAddressInput/index.tsx
src/routes/safe/components/Balances/SendModal/screens/SendCollectible/index.tsx
src/routes/safe/components/Settings/SpendingLimit/LimitsTable/index.tsx
src/routes/safe/components/Settings/SpendingLimit/index.tsx
src/routes/safe/components/Settings/ThresholdSettings/ChangeThreshold/index.tsx
src/routes/safe/components/Settings/index.tsx

More lint was fixed by running `yarn lint:fixed`

Chore: fix lint

---

src/components/Dashboard/Overview/Overview.tsx

The wrong Link component was used.

Fix: links in the Dashboard Overview

---

.github/workflows/cla.yml

Update CLA user allowlist: `mikheevm -> mikhailxyz`

chore: update cla allowlist

---

src/routes/safe/components/Transactions/TxList/BatchExecute.tsx

Resolves #3863 
Disabled Submit button in batch execution modal for self-connected safes.
Also removes batch execution button if no wallet is connected. This is consistent to all other execution buttons.
Disabled submit button:
1. Enable batch execution in advanced settings.
2. Connect safe via wallet connect to itself.
3. Try to batch execute txs in the queue.
Removed batch execution button:
1. Enable batch execution in advanced settings.
2. Disconnect wallet
3. Navigate to Queue
None
Disabled button:
Hide button without connected wallet

fix: prevent batch execution for self-connected safes

---

.github/workflows/cla.yml

Chore: use latest CLA action

---

package.json
src/components/CookiesBanner/index.tsx
src/logic/hooks/useSafeAppUrl.tsx

Release 3.25.2

---

package.json
src/logic/safe/store/reducer/safe.ts

A hot fix for Safe ABIs not being retrieved correctly on L2 chains.

Release 3.25.3

---

src/routes/safe/components/Transactions/TxList/TxSingularDetails.tsx

Repeating #3905 but to main, so that we can test on staging quickly.

Fix: fallback tx location (based on main)

---

src/components/AppLayout/Header/components/Layout.tsx
src/components/AppLayout/Header/components/Provider.tsx
src/components/AppLayout/Header/components/ProviderDetails/ConnectDetails.tsx
src/components/AppLayout/Header/components/ProviderDetails/PairingDetails.tsx
src/components/AppLayout/Header/index.tsx

Resolves #3909
There were a few CSS problems introduced in #3867.
I've made sure both unconnected and connected state are displayed correctly.
Connect to a wallet on Gnosis Chain, disconnect.

Fix: wallet details CSS

---

src/utils/googleTagManager.ts

Just a small fix for the pageView hook.
It was calling `TagManager.dataLayer` directly, now it calls `track` like the other two events.
* Check that the pageView event is still sent to GTM
* It should now also log to the console

Fix: use the track function in the pageView hook

---

cypress/integration/address_book.spec.js
cypress/integration/smoke/balances.spec.js
src/routes/safe/components/AddressBook/index.tsx

- Finds the close button in the new snackbar
- Refactor one big `it` into multiple test suites

chore: fix close snackbar

---

cypress/integration/smoke/balances.spec.js

Resolves accessing assets entries per fixed index
The test suit finds the row per text

chore: get assets row by contained text instead of index

---

package.json
src/components/TransactionQueueBar/TransactionQueueBar.test.tsx
src/logic/contracts/safeContracts.ts
src/logic/safe/store/actions/TxMultiSender.ts
src/logic/safe/transactions/__tests__/multisend.test.ts
src/logic/safe/transactions/multisend.ts
src/logic/safe/utils/__tests__/upgradeSafe.test.ts
src/logic/safe/utils/spendingLimits.ts
src/routes/safe/components/Apps/components/ConfirmTxModal/ConfirmTxModal.test.tsx
src/routes/safe/components/Apps/components/ConfirmTxModal/ReviewConfirm.tsx
src/routes/safe/components/Settings/Advanced/Advanced.test.tsx
src/routes/safe/components/Settings/UpdateSafeModal/index.tsx
src/routes/safe/components/Transactions/TxList/BatchExecute.tsx
src/routes/safe/components/Transactions/TxList/styled.tsx
yarn.lock

* fix: Check both multisend contract addresses for isSupportedMultiSendAddress (#4040)
* style: Fix tree lines for grouped txs (#4028)
* Build(deps): Bump @openzeppelin/contracts from 4.4.2 to 4.7.1 (#4029)
* Build(deps): Bump terser from 4.8.0 to 4.8.1 (#4026)

Release 3.29.1

---

package.json

This PR bumps the package version to 3.31

chore: bump version to 3.31.0

---

src/utils/constants.ts

Chore: update staging CGW host

---

src/utils/constants.ts

* Chore: update staging CGW host

Chore: update staging CGW host (#4083)

---

src/components/App/index.tsx
src/components/PsaBanner/index.tsx

Adds a feature-toggled banner with a pre-defined text per chain.

Feat: warning banner

---

package.json
src/components/PsaBanner/index.module.scss
src/components/PsaBanner/index.tsx

Add a link to the forum.
I also moved the CSS to a module, so that we can color the link white.

Fix: banner text

---

src/utils/constants.ts

Updates the CGW host.
Also see https://github.com/safe-global/web-core/pull/981

Fix: update CGW URL

---

src/components/PsaBanner/Countdown.tsx
src/components/PsaBanner/index.module.scss
src/components/PsaBanner/index.tsx

Shows a banner with our new URL and a redirect after a 10-second countdown.

Feat: new app banner with redirect

---

package.json

Bump version here so we don't have to backmerge main

chore: Bump version to 3.33.3

---

package.json
src/routes/export/Export.tsx
src/routes/safe/components/Settings/DataExport/index.tsx

* Fix: add a link to the new app import
DO NOT MERGE VIA GITHUB!

Release 3.33.4

---

package.json
src/components/PsaBanner/index.tsx

Update the migration banner with a deprecation date.

Chore: update the migration banner
